// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "App.pb.h"

@implementation AppRoot
static PBExtensionRegistry* extensionRegistry = nil;
+ (PBExtensionRegistry*) extensionRegistry {
  return extensionRegistry;
}

+ (void) initialize {
  if (self == [AppRoot class]) {
    PBMutableExtensionRegistry* registry = [PBMutableExtensionRegistry registry];
    [self registerAllExtensions:registry];
    extensionRegistry = [registry retain];
  }
}
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry {
}
@end

@interface Message ()
@property Message_MessageType type;
@property (retain) Message_SubMessageRequest* subRequest;
@property (retain) Message_SubMessageResponse* subResponse;
@property (retain) Message_LoginMessageRequest* loginRequest;
@property (retain) Message_LoginMessageResponse* loginResponse;
@property (retain) Message_LogoutMessageRequest* logoutRequest;
@property (retain) Message_LogoutMessageResponse* logoutResponse;
@property (retain) Message_ForgetPasswordMessageRequest* forgetPwdRequest;
@property (retain) Message_ForgetPasswordMessageResponse* forgetPwdResponse;
@end

@implementation Message

- (BOOL) hasType {
  return !!hasType_;
}
- (void) setHasType:(BOOL) value {
  hasType_ = !!value;
}
@synthesize type;
- (BOOL) hasSubRequest {
  return !!hasSubRequest_;
}
- (void) setHasSubRequest:(BOOL) value {
  hasSubRequest_ = !!value;
}
@synthesize subRequest;
- (BOOL) hasSubResponse {
  return !!hasSubResponse_;
}
- (void) setHasSubResponse:(BOOL) value {
  hasSubResponse_ = !!value;
}
@synthesize subResponse;
- (BOOL) hasLoginRequest {
  return !!hasLoginRequest_;
}
- (void) setHasLoginRequest:(BOOL) value {
  hasLoginRequest_ = !!value;
}
@synthesize loginRequest;
- (BOOL) hasLoginResponse {
  return !!hasLoginResponse_;
}
- (void) setHasLoginResponse:(BOOL) value {
  hasLoginResponse_ = !!value;
}
@synthesize loginResponse;
- (BOOL) hasLogoutRequest {
  return !!hasLogoutRequest_;
}
- (void) setHasLogoutRequest:(BOOL) value {
  hasLogoutRequest_ = !!value;
}
@synthesize logoutRequest;
- (BOOL) hasLogoutResponse {
  return !!hasLogoutResponse_;
}
- (void) setHasLogoutResponse:(BOOL) value {
  hasLogoutResponse_ = !!value;
}
@synthesize logoutResponse;
- (BOOL) hasForgetPwdRequest {
  return !!hasForgetPwdRequest_;
}
- (void) setHasForgetPwdRequest:(BOOL) value {
  hasForgetPwdRequest_ = !!value;
}
@synthesize forgetPwdRequest;
- (BOOL) hasForgetPwdResponse {
  return !!hasForgetPwdResponse_;
}
- (void) setHasForgetPwdResponse:(BOOL) value {
  hasForgetPwdResponse_ = !!value;
}
@synthesize forgetPwdResponse;
- (void) dealloc {
  self.subRequest = nil;
  self.subResponse = nil;
  self.loginRequest = nil;
  self.loginResponse = nil;
  self.logoutRequest = nil;
  self.logoutResponse = nil;
  self.forgetPwdRequest = nil;
  self.forgetPwdResponse = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.type = Message_MessageTypeSubscribeReq;
    self.subRequest = [Message_SubMessageRequest defaultInstance];
    self.subResponse = [Message_SubMessageResponse defaultInstance];
    self.loginRequest = [Message_LoginMessageRequest defaultInstance];
    self.loginResponse = [Message_LoginMessageResponse defaultInstance];
    self.logoutRequest = [Message_LogoutMessageRequest defaultInstance];
    self.logoutResponse = [Message_LogoutMessageResponse defaultInstance];
    self.forgetPwdRequest = [Message_ForgetPasswordMessageRequest defaultInstance];
    self.forgetPwdResponse = [Message_ForgetPasswordMessageResponse defaultInstance];
  }
  return self;
}
static Message* defaultMessageInstance = nil;
+ (void) initialize {
  if (self == [Message class]) {
    defaultMessageInstance = [[Message alloc] init];
  }
}
+ (Message*) defaultInstance {
  return defaultMessageInstance;
}
- (Message*) defaultInstance {
  return defaultMessageInstance;
}
- (BOOL) isInitialized {
  if (!self.hasType) {
    return NO;
  }
  if (self.hasSubRequest) {
    if (!self.subRequest.isInitialized) {
      return NO;
    }
  }
  if (self.hasSubResponse) {
    if (!self.subResponse.isInitialized) {
      return NO;
    }
  }
  if (self.hasLoginRequest) {
    if (!self.loginRequest.isInitialized) {
      return NO;
    }
  }
  if (self.hasLoginResponse) {
    if (!self.loginResponse.isInitialized) {
      return NO;
    }
  }
  if (self.hasLogoutResponse) {
    if (!self.logoutResponse.isInitialized) {
      return NO;
    }
  }
  if (self.hasForgetPwdResponse) {
    if (!self.forgetPwdResponse.isInitialized) {
      return NO;
    }
  }
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasType) {
    [output writeEnum:1 value:self.type];
  }
  if (self.hasSubRequest) {
    [output writeMessage:2 value:self.subRequest];
  }
  if (self.hasSubResponse) {
    [output writeMessage:3 value:self.subResponse];
  }
  if (self.hasLoginRequest) {
    [output writeMessage:4 value:self.loginRequest];
  }
  if (self.hasLoginResponse) {
    [output writeMessage:5 value:self.loginResponse];
  }
  if (self.hasLogoutRequest) {
    [output writeMessage:6 value:self.logoutRequest];
  }
  if (self.hasLogoutResponse) {
    [output writeMessage:7 value:self.logoutResponse];
  }
  if (self.hasForgetPwdRequest) {
    [output writeMessage:8 value:self.forgetPwdRequest];
  }
  if (self.hasForgetPwdResponse) {
    [output writeMessage:9 value:self.forgetPwdResponse];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (int32_t) serializedSize {
  int32_t size = memoizedSerializedSize;
  if (size != -1) {
    return size;
  }

  size = 0;
  if (self.hasType) {
    size += computeEnumSize(1, self.type);
  }
  if (self.hasSubRequest) {
    size += computeMessageSize(2, self.subRequest);
  }
  if (self.hasSubResponse) {
    size += computeMessageSize(3, self.subResponse);
  }
  if (self.hasLoginRequest) {
    size += computeMessageSize(4, self.loginRequest);
  }
  if (self.hasLoginResponse) {
    size += computeMessageSize(5, self.loginResponse);
  }
  if (self.hasLogoutRequest) {
    size += computeMessageSize(6, self.logoutRequest);
  }
  if (self.hasLogoutResponse) {
    size += computeMessageSize(7, self.logoutResponse);
  }
  if (self.hasForgetPwdRequest) {
    size += computeMessageSize(8, self.forgetPwdRequest);
  }
  if (self.hasForgetPwdResponse) {
    size += computeMessageSize(9, self.forgetPwdResponse);
  }
  size += self.unknownFields.serializedSize;
  memoizedSerializedSize = size;
  return size;
}
+ (Message*) parseFromData:(NSData*) data {
  return (Message*)[[[Message builder] mergeFromData:data] build];
}
+ (Message*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (Message*)[[[Message builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (Message*) parseFromInputStream:(NSInputStream*) input {
  return (Message*)[[[Message builder] mergeFromInputStream:input] build];
}
+ (Message*) parseDelimitedFromInputStream:(NSInputStream*) input {
  return (Message*)[[[Message builder] mergeDelimitedFromInputStream:input] build];
}
+ (Message*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (Message*)[[[Message builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (Message*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (Message*)[[[Message builder] mergeFromCodedInputStream:input] build];
}
+ (Message*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (Message*)[[[Message builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (Message_Builder*) builder {
  return [[[Message_Builder alloc] init] autorelease];
}
+ (Message_Builder*) builderWithPrototype:(Message*) prototype {
  return [[Message builder] mergeFrom:prototype];
}
- (Message_Builder*) builder {
  return [Message builder];
}
@end

BOOL Message_MessageTypeIsValidValue(Message_MessageType value) {
  switch (value) {
    case Message_MessageTypeSubscribeReq:
    case Message_MessageTypeSubscribeResp:
    case Message_MessageTypeLoginReq:
    case Message_MessageTypeLoginResp:
    case Message_MessageTypeLogoutReq:
    case Message_MessageTypeLogoutResp:
    case Message_MessageTypeForgetPwdReq:
    case Message_MessageTypeForgetPwdResp:
      return YES;
    default:
      return NO;
  }
}
@interface Message_SubMessageRequest ()
@property (retain) NSString* phoneNumber;
@property (retain) NSString* email;
@property (retain) NSString* password;
@property int32_t sex;
@end

@implementation Message_SubMessageRequest

- (BOOL) hasPhoneNumber {
  return !!hasPhoneNumber_;
}
- (void) setHasPhoneNumber:(BOOL) value {
  hasPhoneNumber_ = !!value;
}
@synthesize phoneNumber;
- (BOOL) hasEmail {
  return !!hasEmail_;
}
- (void) setHasEmail:(BOOL) value {
  hasEmail_ = !!value;
}
@synthesize email;
- (BOOL) hasPassword {
  return !!hasPassword_;
}
- (void) setHasPassword:(BOOL) value {
  hasPassword_ = !!value;
}
@synthesize password;
- (BOOL) hasSex {
  return !!hasSex_;
}
- (void) setHasSex:(BOOL) value {
  hasSex_ = !!value;
}
@synthesize sex;
- (void) dealloc {
  self.phoneNumber = nil;
  self.email = nil;
  self.password = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.phoneNumber = @"";
    self.email = @"";
    self.password = @"";
    self.sex = 0;
  }
  return self;
}
static Message_SubMessageRequest* defaultMessage_SubMessageRequestInstance = nil;
+ (void) initialize {
  if (self == [Message_SubMessageRequest class]) {
    defaultMessage_SubMessageRequestInstance = [[Message_SubMessageRequest alloc] init];
  }
}
+ (Message_SubMessageRequest*) defaultInstance {
  return defaultMessage_SubMessageRequestInstance;
}
- (Message_SubMessageRequest*) defaultInstance {
  return defaultMessage_SubMessageRequestInstance;
}
- (BOOL) isInitialized {
  if (!self.hasPassword) {
    return NO;
  }
  if (!self.hasSex) {
    return NO;
  }
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasPhoneNumber) {
    [output writeString:1 value:self.phoneNumber];
  }
  if (self.hasEmail) {
    [output writeString:2 value:self.email];
  }
  if (self.hasPassword) {
    [output writeString:3 value:self.password];
  }
  if (self.hasSex) {
    [output writeInt32:4 value:self.sex];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (int32_t) serializedSize {
  int32_t size = memoizedSerializedSize;
  if (size != -1) {
    return size;
  }

  size = 0;
  if (self.hasPhoneNumber) {
    size += computeStringSize(1, self.phoneNumber);
  }
  if (self.hasEmail) {
    size += computeStringSize(2, self.email);
  }
  if (self.hasPassword) {
    size += computeStringSize(3, self.password);
  }
  if (self.hasSex) {
    size += computeInt32Size(4, self.sex);
  }
  size += self.unknownFields.serializedSize;
  memoizedSerializedSize = size;
  return size;
}
+ (Message_SubMessageRequest*) parseFromData:(NSData*) data {
  return (Message_SubMessageRequest*)[[[Message_SubMessageRequest builder] mergeFromData:data] build];
}
+ (Message_SubMessageRequest*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (Message_SubMessageRequest*)[[[Message_SubMessageRequest builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (Message_SubMessageRequest*) parseFromInputStream:(NSInputStream*) input {
  return (Message_SubMessageRequest*)[[[Message_SubMessageRequest builder] mergeFromInputStream:input] build];
}
+ (Message_SubMessageRequest*) parseDelimitedFromInputStream:(NSInputStream*) input {
  return (Message_SubMessageRequest*)[[[Message_SubMessageRequest builder] mergeDelimitedFromInputStream:input] build];
}
+ (Message_SubMessageRequest*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (Message_SubMessageRequest*)[[[Message_SubMessageRequest builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (Message_SubMessageRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (Message_SubMessageRequest*)[[[Message_SubMessageRequest builder] mergeFromCodedInputStream:input] build];
}
+ (Message_SubMessageRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (Message_SubMessageRequest*)[[[Message_SubMessageRequest builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (Message_SubMessageRequest_Builder*) builder {
  return [[[Message_SubMessageRequest_Builder alloc] init] autorelease];
}
+ (Message_SubMessageRequest_Builder*) builderWithPrototype:(Message_SubMessageRequest*) prototype {
  return [[Message_SubMessageRequest builder] mergeFrom:prototype];
}
- (Message_SubMessageRequest_Builder*) builder {
  return [Message_SubMessageRequest builder];
}
@end

@interface Message_SubMessageRequest_Builder()
@property (retain) Message_SubMessageRequest* result;
@end

@implementation Message_SubMessageRequest_Builder
@synthesize result;
- (void) dealloc {
  self.result = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.result = [[[Message_SubMessageRequest alloc] init] autorelease];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return result;
}
- (Message_SubMessageRequest_Builder*) clear {
  self.result = [[[Message_SubMessageRequest alloc] init] autorelease];
  return self;
}
- (Message_SubMessageRequest_Builder*) clone {
  return [Message_SubMessageRequest builderWithPrototype:result];
}
- (Message_SubMessageRequest*) defaultInstance {
  return [Message_SubMessageRequest defaultInstance];
}
- (Message_SubMessageRequest*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (Message_SubMessageRequest*) buildPartial {
  Message_SubMessageRequest* returnMe = [[result retain] autorelease];
  self.result = nil;
  return returnMe;
}
- (Message_SubMessageRequest_Builder*) mergeFrom:(Message_SubMessageRequest*) other {
  if (other == [Message_SubMessageRequest defaultInstance]) {
    return self;
  }
  if (other.hasPhoneNumber) {
    [self setPhoneNumber:other.phoneNumber];
  }
  if (other.hasEmail) {
    [self setEmail:other.email];
  }
  if (other.hasPassword) {
    [self setPassword:other.password];
  }
  if (other.hasSex) {
    [self setSex:other.sex];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (Message_SubMessageRequest_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (Message_SubMessageRequest_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSet_Builder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    int32_t tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 10: {
        [self setPhoneNumber:[input readString]];
        break;
      }
      case 18: {
        [self setEmail:[input readString]];
        break;
      }
      case 26: {
        [self setPassword:[input readString]];
        break;
      }
      case 32: {
        [self setSex:[input readInt32]];
        break;
      }
    }
  }
}
- (BOOL) hasPhoneNumber {
  return result.hasPhoneNumber;
}
- (NSString*) phoneNumber {
  return result.phoneNumber;
}
- (Message_SubMessageRequest_Builder*) setPhoneNumber:(NSString*) value {
  result.hasPhoneNumber = YES;
  result.phoneNumber = value;
  return self;
}
- (Message_SubMessageRequest_Builder*) clearPhoneNumber {
  result.hasPhoneNumber = NO;
  result.phoneNumber = @"";
  return self;
}
- (BOOL) hasEmail {
  return result.hasEmail;
}
- (NSString*) email {
  return result.email;
}
- (Message_SubMessageRequest_Builder*) setEmail:(NSString*) value {
  result.hasEmail = YES;
  result.email = value;
  return self;
}
- (Message_SubMessageRequest_Builder*) clearEmail {
  result.hasEmail = NO;
  result.email = @"";
  return self;
}
- (BOOL) hasPassword {
  return result.hasPassword;
}
- (NSString*) password {
  return result.password;
}
- (Message_SubMessageRequest_Builder*) setPassword:(NSString*) value {
  result.hasPassword = YES;
  result.password = value;
  return self;
}
- (Message_SubMessageRequest_Builder*) clearPassword {
  result.hasPassword = NO;
  result.password = @"";
  return self;
}
- (BOOL) hasSex {
  return result.hasSex;
}
- (int32_t) sex {
  return result.sex;
}
- (Message_SubMessageRequest_Builder*) setSex:(int32_t) value {
  result.hasSex = YES;
  result.sex = value;
  return self;
}
- (Message_SubMessageRequest_Builder*) clearSex {
  result.hasSex = NO;
  result.sex = 0;
  return self;
}
@end

@interface Message_SubMessageResponse ()
@property int32_t status;
@property (retain) NSString* userId;
@property (retain) NSString* userName;
@property (retain) NSString* password;
@property (retain) NSString* nickName;
@property int32_t sex;
@property (retain) NSString* birthday;
@property (retain) NSString* avatarUrl;
@property int32_t avatarId;
@property (retain) NSString* appId;
@end

@implementation Message_SubMessageResponse

- (BOOL) hasStatus {
  return !!hasStatus_;
}
- (void) setHasStatus:(BOOL) value {
  hasStatus_ = !!value;
}
@synthesize status;
- (BOOL) hasUserId {
  return !!hasUserId_;
}
- (void) setHasUserId:(BOOL) value {
  hasUserId_ = !!value;
}
@synthesize userId;
- (BOOL) hasUserName {
  return !!hasUserName_;
}
- (void) setHasUserName:(BOOL) value {
  hasUserName_ = !!value;
}
@synthesize userName;
- (BOOL) hasPassword {
  return !!hasPassword_;
}
- (void) setHasPassword:(BOOL) value {
  hasPassword_ = !!value;
}
@synthesize password;
- (BOOL) hasNickName {
  return !!hasNickName_;
}
- (void) setHasNickName:(BOOL) value {
  hasNickName_ = !!value;
}
@synthesize nickName;
- (BOOL) hasSex {
  return !!hasSex_;
}
- (void) setHasSex:(BOOL) value {
  hasSex_ = !!value;
}
@synthesize sex;
- (BOOL) hasBirthday {
  return !!hasBirthday_;
}
- (void) setHasBirthday:(BOOL) value {
  hasBirthday_ = !!value;
}
@synthesize birthday;
- (BOOL) hasAvatarUrl {
  return !!hasAvatarUrl_;
}
- (void) setHasAvatarUrl:(BOOL) value {
  hasAvatarUrl_ = !!value;
}
@synthesize avatarUrl;
- (BOOL) hasAvatarId {
  return !!hasAvatarId_;
}
- (void) setHasAvatarId:(BOOL) value {
  hasAvatarId_ = !!value;
}
@synthesize avatarId;
- (BOOL) hasAppId {
  return !!hasAppId_;
}
- (void) setHasAppId:(BOOL) value {
  hasAppId_ = !!value;
}
@synthesize appId;
- (void) dealloc {
  self.userId = nil;
  self.userName = nil;
  self.password = nil;
  self.nickName = nil;
  self.birthday = nil;
  self.avatarUrl = nil;
  self.appId = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.status = 0;
    self.userId = @"";
    self.userName = @"";
    self.password = @"";
    self.nickName = @"";
    self.sex = 0;
    self.birthday = @"";
    self.avatarUrl = @"";
    self.avatarId = 0;
    self.appId = @"";
  }
  return self;
}
static Message_SubMessageResponse* defaultMessage_SubMessageResponseInstance = nil;
+ (void) initialize {
  if (self == [Message_SubMessageResponse class]) {
    defaultMessage_SubMessageResponseInstance = [[Message_SubMessageResponse alloc] init];
  }
}
+ (Message_SubMessageResponse*) defaultInstance {
  return defaultMessage_SubMessageResponseInstance;
}
- (Message_SubMessageResponse*) defaultInstance {
  return defaultMessage_SubMessageResponseInstance;
}
- (BOOL) isInitialized {
  if (!self.hasStatus) {
    return NO;
  }
  if (!self.hasUserId) {
    return NO;
  }
  if (!self.hasUserName) {
    return NO;
  }
  if (!self.hasPassword) {
    return NO;
  }
  if (!self.hasNickName) {
    return NO;
  }
  if (!self.hasSex) {
    return NO;
  }
  if (!self.hasBirthday) {
    return NO;
  }
  if (!self.hasAvatarUrl) {
    return NO;
  }
  if (!self.hasAvatarId) {
    return NO;
  }
  if (!self.hasAppId) {
    return NO;
  }
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasStatus) {
    [output writeInt32:1 value:self.status];
  }
  if (self.hasUserId) {
    [output writeString:2 value:self.userId];
  }
  if (self.hasUserName) {
    [output writeString:3 value:self.userName];
  }
  if (self.hasPassword) {
    [output writeString:4 value:self.password];
  }
  if (self.hasNickName) {
    [output writeString:5 value:self.nickName];
  }
  if (self.hasSex) {
    [output writeInt32:6 value:self.sex];
  }
  if (self.hasBirthday) {
    [output writeString:7 value:self.birthday];
  }
  if (self.hasAvatarUrl) {
    [output writeString:8 value:self.avatarUrl];
  }
  if (self.hasAvatarId) {
    [output writeInt32:9 value:self.avatarId];
  }
  if (self.hasAppId) {
    [output writeString:10 value:self.appId];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (int32_t) serializedSize {
  int32_t size = memoizedSerializedSize;
  if (size != -1) {
    return size;
  }

  size = 0;
  if (self.hasStatus) {
    size += computeInt32Size(1, self.status);
  }
  if (self.hasUserId) {
    size += computeStringSize(2, self.userId);
  }
  if (self.hasUserName) {
    size += computeStringSize(3, self.userName);
  }
  if (self.hasPassword) {
    size += computeStringSize(4, self.password);
  }
  if (self.hasNickName) {
    size += computeStringSize(5, self.nickName);
  }
  if (self.hasSex) {
    size += computeInt32Size(6, self.sex);
  }
  if (self.hasBirthday) {
    size += computeStringSize(7, self.birthday);
  }
  if (self.hasAvatarUrl) {
    size += computeStringSize(8, self.avatarUrl);
  }
  if (self.hasAvatarId) {
    size += computeInt32Size(9, self.avatarId);
  }
  if (self.hasAppId) {
    size += computeStringSize(10, self.appId);
  }
  size += self.unknownFields.serializedSize;
  memoizedSerializedSize = size;
  return size;
}
+ (Message_SubMessageResponse*) parseFromData:(NSData*) data {
  return (Message_SubMessageResponse*)[[[Message_SubMessageResponse builder] mergeFromData:data] build];
}
+ (Message_SubMessageResponse*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (Message_SubMessageResponse*)[[[Message_SubMessageResponse builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (Message_SubMessageResponse*) parseFromInputStream:(NSInputStream*) input {
  return (Message_SubMessageResponse*)[[[Message_SubMessageResponse builder] mergeFromInputStream:input] build];
}
+ (Message_SubMessageResponse*) parseDelimitedFromInputStream:(NSInputStream*) input {
  return (Message_SubMessageResponse*)[[[Message_SubMessageResponse builder] mergeDelimitedFromInputStream:input] build];
}
+ (Message_SubMessageResponse*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (Message_SubMessageResponse*)[[[Message_SubMessageResponse builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (Message_SubMessageResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (Message_SubMessageResponse*)[[[Message_SubMessageResponse builder] mergeFromCodedInputStream:input] build];
}
+ (Message_SubMessageResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (Message_SubMessageResponse*)[[[Message_SubMessageResponse builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (Message_SubMessageResponse_Builder*) builder {
  return [[[Message_SubMessageResponse_Builder alloc] init] autorelease];
}
+ (Message_SubMessageResponse_Builder*) builderWithPrototype:(Message_SubMessageResponse*) prototype {
  return [[Message_SubMessageResponse builder] mergeFrom:prototype];
}
- (Message_SubMessageResponse_Builder*) builder {
  return [Message_SubMessageResponse builder];
}
@end

@interface Message_SubMessageResponse_Builder()
@property (retain) Message_SubMessageResponse* result;
@end

@implementation Message_SubMessageResponse_Builder
@synthesize result;
- (void) dealloc {
  self.result = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.result = [[[Message_SubMessageResponse alloc] init] autorelease];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return result;
}
- (Message_SubMessageResponse_Builder*) clear {
  self.result = [[[Message_SubMessageResponse alloc] init] autorelease];
  return self;
}
- (Message_SubMessageResponse_Builder*) clone {
  return [Message_SubMessageResponse builderWithPrototype:result];
}
- (Message_SubMessageResponse*) defaultInstance {
  return [Message_SubMessageResponse defaultInstance];
}
- (Message_SubMessageResponse*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (Message_SubMessageResponse*) buildPartial {
  Message_SubMessageResponse* returnMe = [[result retain] autorelease];
  self.result = nil;
  return returnMe;
}
- (Message_SubMessageResponse_Builder*) mergeFrom:(Message_SubMessageResponse*) other {
  if (other == [Message_SubMessageResponse defaultInstance]) {
    return self;
  }
  if (other.hasStatus) {
    [self setStatus:other.status];
  }
  if (other.hasUserId) {
    [self setUserId:other.userId];
  }
  if (other.hasUserName) {
    [self setUserName:other.userName];
  }
  if (other.hasPassword) {
    [self setPassword:other.password];
  }
  if (other.hasNickName) {
    [self setNickName:other.nickName];
  }
  if (other.hasSex) {
    [self setSex:other.sex];
  }
  if (other.hasBirthday) {
    [self setBirthday:other.birthday];
  }
  if (other.hasAvatarUrl) {
    [self setAvatarUrl:other.avatarUrl];
  }
  if (other.hasAvatarId) {
    [self setAvatarId:other.avatarId];
  }
  if (other.hasAppId) {
    [self setAppId:other.appId];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (Message_SubMessageResponse_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (Message_SubMessageResponse_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSet_Builder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    int32_t tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 8: {
        [self setStatus:[input readInt32]];
        break;
      }
      case 18: {
        [self setUserId:[input readString]];
        break;
      }
      case 26: {
        [self setUserName:[input readString]];
        break;
      }
      case 34: {
        [self setPassword:[input readString]];
        break;
      }
      case 42: {
        [self setNickName:[input readString]];
        break;
      }
      case 48: {
        [self setSex:[input readInt32]];
        break;
      }
      case 58: {
        [self setBirthday:[input readString]];
        break;
      }
      case 66: {
        [self setAvatarUrl:[input readString]];
        break;
      }
      case 72: {
        [self setAvatarId:[input readInt32]];
        break;
      }
      case 82: {
        [self setAppId:[input readString]];
        break;
      }
    }
  }
}
- (BOOL) hasStatus {
  return result.hasStatus;
}
- (int32_t) status {
  return result.status;
}
- (Message_SubMessageResponse_Builder*) setStatus:(int32_t) value {
  result.hasStatus = YES;
  result.status = value;
  return self;
}
- (Message_SubMessageResponse_Builder*) clearStatus {
  result.hasStatus = NO;
  result.status = 0;
  return self;
}
- (BOOL) hasUserId {
  return result.hasUserId;
}
- (NSString*) userId {
  return result.userId;
}
- (Message_SubMessageResponse_Builder*) setUserId:(NSString*) value {
  result.hasUserId = YES;
  result.userId = value;
  return self;
}
- (Message_SubMessageResponse_Builder*) clearUserId {
  result.hasUserId = NO;
  result.userId = @"";
  return self;
}
- (BOOL) hasUserName {
  return result.hasUserName;
}
- (NSString*) userName {
  return result.userName;
}
- (Message_SubMessageResponse_Builder*) setUserName:(NSString*) value {
  result.hasUserName = YES;
  result.userName = value;
  return self;
}
- (Message_SubMessageResponse_Builder*) clearUserName {
  result.hasUserName = NO;
  result.userName = @"";
  return self;
}
- (BOOL) hasPassword {
  return result.hasPassword;
}
- (NSString*) password {
  return result.password;
}
- (Message_SubMessageResponse_Builder*) setPassword:(NSString*) value {
  result.hasPassword = YES;
  result.password = value;
  return self;
}
- (Message_SubMessageResponse_Builder*) clearPassword {
  result.hasPassword = NO;
  result.password = @"";
  return self;
}
- (BOOL) hasNickName {
  return result.hasNickName;
}
- (NSString*) nickName {
  return result.nickName;
}
- (Message_SubMessageResponse_Builder*) setNickName:(NSString*) value {
  result.hasNickName = YES;
  result.nickName = value;
  return self;
}
- (Message_SubMessageResponse_Builder*) clearNickName {
  result.hasNickName = NO;
  result.nickName = @"";
  return self;
}
- (BOOL) hasSex {
  return result.hasSex;
}
- (int32_t) sex {
  return result.sex;
}
- (Message_SubMessageResponse_Builder*) setSex:(int32_t) value {
  result.hasSex = YES;
  result.sex = value;
  return self;
}
- (Message_SubMessageResponse_Builder*) clearSex {
  result.hasSex = NO;
  result.sex = 0;
  return self;
}
- (BOOL) hasBirthday {
  return result.hasBirthday;
}
- (NSString*) birthday {
  return result.birthday;
}
- (Message_SubMessageResponse_Builder*) setBirthday:(NSString*) value {
  result.hasBirthday = YES;
  result.birthday = value;
  return self;
}
- (Message_SubMessageResponse_Builder*) clearBirthday {
  result.hasBirthday = NO;
  result.birthday = @"";
  return self;
}
- (BOOL) hasAvatarUrl {
  return result.hasAvatarUrl;
}
- (NSString*) avatarUrl {
  return result.avatarUrl;
}
- (Message_SubMessageResponse_Builder*) setAvatarUrl:(NSString*) value {
  result.hasAvatarUrl = YES;
  result.avatarUrl = value;
  return self;
}
- (Message_SubMessageResponse_Builder*) clearAvatarUrl {
  result.hasAvatarUrl = NO;
  result.avatarUrl = @"";
  return self;
}
- (BOOL) hasAvatarId {
  return result.hasAvatarId;
}
- (int32_t) avatarId {
  return result.avatarId;
}
- (Message_SubMessageResponse_Builder*) setAvatarId:(int32_t) value {
  result.hasAvatarId = YES;
  result.avatarId = value;
  return self;
}
- (Message_SubMessageResponse_Builder*) clearAvatarId {
  result.hasAvatarId = NO;
  result.avatarId = 0;
  return self;
}
- (BOOL) hasAppId {
  return result.hasAppId;
}
- (NSString*) appId {
  return result.appId;
}
- (Message_SubMessageResponse_Builder*) setAppId:(NSString*) value {
  result.hasAppId = YES;
  result.appId = value;
  return self;
}
- (Message_SubMessageResponse_Builder*) clearAppId {
  result.hasAppId = NO;
  result.appId = @"";
  return self;
}
@end

@interface Message_LoginMessageRequest ()
@property (retain) NSString* phoneNumber;
@property (retain) NSString* email;
@property (retain) NSString* password;
@end

@implementation Message_LoginMessageRequest

- (BOOL) hasPhoneNumber {
  return !!hasPhoneNumber_;
}
- (void) setHasPhoneNumber:(BOOL) value {
  hasPhoneNumber_ = !!value;
}
@synthesize phoneNumber;
- (BOOL) hasEmail {
  return !!hasEmail_;
}
- (void) setHasEmail:(BOOL) value {
  hasEmail_ = !!value;
}
@synthesize email;
- (BOOL) hasPassword {
  return !!hasPassword_;
}
- (void) setHasPassword:(BOOL) value {
  hasPassword_ = !!value;
}
@synthesize password;
- (void) dealloc {
  self.phoneNumber = nil;
  self.email = nil;
  self.password = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.phoneNumber = @"";
    self.email = @"";
    self.password = @"";
  }
  return self;
}
static Message_LoginMessageRequest* defaultMessage_LoginMessageRequestInstance = nil;
+ (void) initialize {
  if (self == [Message_LoginMessageRequest class]) {
    defaultMessage_LoginMessageRequestInstance = [[Message_LoginMessageRequest alloc] init];
  }
}
+ (Message_LoginMessageRequest*) defaultInstance {
  return defaultMessage_LoginMessageRequestInstance;
}
- (Message_LoginMessageRequest*) defaultInstance {
  return defaultMessage_LoginMessageRequestInstance;
}
- (BOOL) isInitialized {
  if (!self.hasPassword) {
    return NO;
  }
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasPhoneNumber) {
    [output writeString:1 value:self.phoneNumber];
  }
  if (self.hasEmail) {
    [output writeString:2 value:self.email];
  }
  if (self.hasPassword) {
    [output writeString:3 value:self.password];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (int32_t) serializedSize {
  int32_t size = memoizedSerializedSize;
  if (size != -1) {
    return size;
  }

  size = 0;
  if (self.hasPhoneNumber) {
    size += computeStringSize(1, self.phoneNumber);
  }
  if (self.hasEmail) {
    size += computeStringSize(2, self.email);
  }
  if (self.hasPassword) {
    size += computeStringSize(3, self.password);
  }
  size += self.unknownFields.serializedSize;
  memoizedSerializedSize = size;
  return size;
}
+ (Message_LoginMessageRequest*) parseFromData:(NSData*) data {
  return (Message_LoginMessageRequest*)[[[Message_LoginMessageRequest builder] mergeFromData:data] build];
}
+ (Message_LoginMessageRequest*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (Message_LoginMessageRequest*)[[[Message_LoginMessageRequest builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (Message_LoginMessageRequest*) parseFromInputStream:(NSInputStream*) input {
  return (Message_LoginMessageRequest*)[[[Message_LoginMessageRequest builder] mergeFromInputStream:input] build];
}
+ (Message_LoginMessageRequest*) parseDelimitedFromInputStream:(NSInputStream*) input {
  return (Message_LoginMessageRequest*)[[[Message_LoginMessageRequest builder] mergeDelimitedFromInputStream:input] build];
}
+ (Message_LoginMessageRequest*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (Message_LoginMessageRequest*)[[[Message_LoginMessageRequest builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (Message_LoginMessageRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (Message_LoginMessageRequest*)[[[Message_LoginMessageRequest builder] mergeFromCodedInputStream:input] build];
}
+ (Message_LoginMessageRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (Message_LoginMessageRequest*)[[[Message_LoginMessageRequest builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (Message_LoginMessageRequest_Builder*) builder {
  return [[[Message_LoginMessageRequest_Builder alloc] init] autorelease];
}
+ (Message_LoginMessageRequest_Builder*) builderWithPrototype:(Message_LoginMessageRequest*) prototype {
  return [[Message_LoginMessageRequest builder] mergeFrom:prototype];
}
- (Message_LoginMessageRequest_Builder*) builder {
  return [Message_LoginMessageRequest builder];
}
@end

@interface Message_LoginMessageRequest_Builder()
@property (retain) Message_LoginMessageRequest* result;
@end

@implementation Message_LoginMessageRequest_Builder
@synthesize result;
- (void) dealloc {
  self.result = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.result = [[[Message_LoginMessageRequest alloc] init] autorelease];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return result;
}
- (Message_LoginMessageRequest_Builder*) clear {
  self.result = [[[Message_LoginMessageRequest alloc] init] autorelease];
  return self;
}
- (Message_LoginMessageRequest_Builder*) clone {
  return [Message_LoginMessageRequest builderWithPrototype:result];
}
- (Message_LoginMessageRequest*) defaultInstance {
  return [Message_LoginMessageRequest defaultInstance];
}
- (Message_LoginMessageRequest*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (Message_LoginMessageRequest*) buildPartial {
  Message_LoginMessageRequest* returnMe = [[result retain] autorelease];
  self.result = nil;
  return returnMe;
}
- (Message_LoginMessageRequest_Builder*) mergeFrom:(Message_LoginMessageRequest*) other {
  if (other == [Message_LoginMessageRequest defaultInstance]) {
    return self;
  }
  if (other.hasPhoneNumber) {
    [self setPhoneNumber:other.phoneNumber];
  }
  if (other.hasEmail) {
    [self setEmail:other.email];
  }
  if (other.hasPassword) {
    [self setPassword:other.password];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (Message_LoginMessageRequest_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (Message_LoginMessageRequest_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSet_Builder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    int32_t tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 10: {
        [self setPhoneNumber:[input readString]];
        break;
      }
      case 18: {
        [self setEmail:[input readString]];
        break;
      }
      case 26: {
        [self setPassword:[input readString]];
        break;
      }
    }
  }
}
- (BOOL) hasPhoneNumber {
  return result.hasPhoneNumber;
}
- (NSString*) phoneNumber {
  return result.phoneNumber;
}
- (Message_LoginMessageRequest_Builder*) setPhoneNumber:(NSString*) value {
  result.hasPhoneNumber = YES;
  result.phoneNumber = value;
  return self;
}
- (Message_LoginMessageRequest_Builder*) clearPhoneNumber {
  result.hasPhoneNumber = NO;
  result.phoneNumber = @"";
  return self;
}
- (BOOL) hasEmail {
  return result.hasEmail;
}
- (NSString*) email {
  return result.email;
}
- (Message_LoginMessageRequest_Builder*) setEmail:(NSString*) value {
  result.hasEmail = YES;
  result.email = value;
  return self;
}
- (Message_LoginMessageRequest_Builder*) clearEmail {
  result.hasEmail = NO;
  result.email = @"";
  return self;
}
- (BOOL) hasPassword {
  return result.hasPassword;
}
- (NSString*) password {
  return result.password;
}
- (Message_LoginMessageRequest_Builder*) setPassword:(NSString*) value {
  result.hasPassword = YES;
  result.password = value;
  return self;
}
- (Message_LoginMessageRequest_Builder*) clearPassword {
  result.hasPassword = NO;
  result.password = @"";
  return self;
}
@end

@interface Message_LoginMessageResponse ()
@property int32_t status;
@property (retain) NSString* userId;
@property (retain) NSString* userName;
@property (retain) NSString* password;
@property (retain) NSString* nickName;
@property int32_t sex;
@property (retain) NSString* birthday;
@property (retain) NSString* avatarUrl;
@property int32_t avatarId;
@property (retain) NSString* appId;
@end

@implementation Message_LoginMessageResponse

- (BOOL) hasStatus {
  return !!hasStatus_;
}
- (void) setHasStatus:(BOOL) value {
  hasStatus_ = !!value;
}
@synthesize status;
- (BOOL) hasUserId {
  return !!hasUserId_;
}
- (void) setHasUserId:(BOOL) value {
  hasUserId_ = !!value;
}
@synthesize userId;
- (BOOL) hasUserName {
  return !!hasUserName_;
}
- (void) setHasUserName:(BOOL) value {
  hasUserName_ = !!value;
}
@synthesize userName;
- (BOOL) hasPassword {
  return !!hasPassword_;
}
- (void) setHasPassword:(BOOL) value {
  hasPassword_ = !!value;
}
@synthesize password;
- (BOOL) hasNickName {
  return !!hasNickName_;
}
- (void) setHasNickName:(BOOL) value {
  hasNickName_ = !!value;
}
@synthesize nickName;
- (BOOL) hasSex {
  return !!hasSex_;
}
- (void) setHasSex:(BOOL) value {
  hasSex_ = !!value;
}
@synthesize sex;
- (BOOL) hasBirthday {
  return !!hasBirthday_;
}
- (void) setHasBirthday:(BOOL) value {
  hasBirthday_ = !!value;
}
@synthesize birthday;
- (BOOL) hasAvatarUrl {
  return !!hasAvatarUrl_;
}
- (void) setHasAvatarUrl:(BOOL) value {
  hasAvatarUrl_ = !!value;
}
@synthesize avatarUrl;
- (BOOL) hasAvatarId {
  return !!hasAvatarId_;
}
- (void) setHasAvatarId:(BOOL) value {
  hasAvatarId_ = !!value;
}
@synthesize avatarId;
- (BOOL) hasAppId {
  return !!hasAppId_;
}
- (void) setHasAppId:(BOOL) value {
  hasAppId_ = !!value;
}
@synthesize appId;
- (void) dealloc {
  self.userId = nil;
  self.userName = nil;
  self.password = nil;
  self.nickName = nil;
  self.birthday = nil;
  self.avatarUrl = nil;
  self.appId = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.status = 0;
    self.userId = @"";
    self.userName = @"";
    self.password = @"";
    self.nickName = @"";
    self.sex = 0;
    self.birthday = @"";
    self.avatarUrl = @"";
    self.avatarId = 0;
    self.appId = @"";
  }
  return self;
}
static Message_LoginMessageResponse* defaultMessage_LoginMessageResponseInstance = nil;
+ (void) initialize {
  if (self == [Message_LoginMessageResponse class]) {
    defaultMessage_LoginMessageResponseInstance = [[Message_LoginMessageResponse alloc] init];
  }
}
+ (Message_LoginMessageResponse*) defaultInstance {
  return defaultMessage_LoginMessageResponseInstance;
}
- (Message_LoginMessageResponse*) defaultInstance {
  return defaultMessage_LoginMessageResponseInstance;
}
- (BOOL) isInitialized {
  if (!self.hasStatus) {
    return NO;
  }
  if (!self.hasUserId) {
    return NO;
  }
  if (!self.hasUserName) {
    return NO;
  }
  if (!self.hasPassword) {
    return NO;
  }
  if (!self.hasNickName) {
    return NO;
  }
  if (!self.hasSex) {
    return NO;
  }
  if (!self.hasBirthday) {
    return NO;
  }
  if (!self.hasAvatarUrl) {
    return NO;
  }
  if (!self.hasAvatarId) {
    return NO;
  }
  if (!self.hasAppId) {
    return NO;
  }
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasStatus) {
    [output writeInt32:1 value:self.status];
  }
  if (self.hasUserId) {
    [output writeString:2 value:self.userId];
  }
  if (self.hasUserName) {
    [output writeString:3 value:self.userName];
  }
  if (self.hasPassword) {
    [output writeString:4 value:self.password];
  }
  if (self.hasNickName) {
    [output writeString:5 value:self.nickName];
  }
  if (self.hasSex) {
    [output writeInt32:6 value:self.sex];
  }
  if (self.hasBirthday) {
    [output writeString:7 value:self.birthday];
  }
  if (self.hasAvatarUrl) {
    [output writeString:8 value:self.avatarUrl];
  }
  if (self.hasAvatarId) {
    [output writeInt32:9 value:self.avatarId];
  }
  if (self.hasAppId) {
    [output writeString:10 value:self.appId];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (int32_t) serializedSize {
  int32_t size = memoizedSerializedSize;
  if (size != -1) {
    return size;
  }

  size = 0;
  if (self.hasStatus) {
    size += computeInt32Size(1, self.status);
  }
  if (self.hasUserId) {
    size += computeStringSize(2, self.userId);
  }
  if (self.hasUserName) {
    size += computeStringSize(3, self.userName);
  }
  if (self.hasPassword) {
    size += computeStringSize(4, self.password);
  }
  if (self.hasNickName) {
    size += computeStringSize(5, self.nickName);
  }
  if (self.hasSex) {
    size += computeInt32Size(6, self.sex);
  }
  if (self.hasBirthday) {
    size += computeStringSize(7, self.birthday);
  }
  if (self.hasAvatarUrl) {
    size += computeStringSize(8, self.avatarUrl);
  }
  if (self.hasAvatarId) {
    size += computeInt32Size(9, self.avatarId);
  }
  if (self.hasAppId) {
    size += computeStringSize(10, self.appId);
  }
  size += self.unknownFields.serializedSize;
  memoizedSerializedSize = size;
  return size;
}
+ (Message_LoginMessageResponse*) parseFromData:(NSData*) data {
  return (Message_LoginMessageResponse*)[[[Message_LoginMessageResponse builder] mergeFromData:data] build];
}
+ (Message_LoginMessageResponse*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (Message_LoginMessageResponse*)[[[Message_LoginMessageResponse builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (Message_LoginMessageResponse*) parseFromInputStream:(NSInputStream*) input {
  return (Message_LoginMessageResponse*)[[[Message_LoginMessageResponse builder] mergeFromInputStream:input] build];
}
+ (Message_LoginMessageResponse*) parseDelimitedFromInputStream:(NSInputStream*) input {
  return (Message_LoginMessageResponse*)[[[Message_LoginMessageResponse builder] mergeDelimitedFromInputStream:input] build];
}
+ (Message_LoginMessageResponse*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (Message_LoginMessageResponse*)[[[Message_LoginMessageResponse builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (Message_LoginMessageResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (Message_LoginMessageResponse*)[[[Message_LoginMessageResponse builder] mergeFromCodedInputStream:input] build];
}
+ (Message_LoginMessageResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (Message_LoginMessageResponse*)[[[Message_LoginMessageResponse builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (Message_LoginMessageResponse_Builder*) builder {
  return [[[Message_LoginMessageResponse_Builder alloc] init] autorelease];
}
+ (Message_LoginMessageResponse_Builder*) builderWithPrototype:(Message_LoginMessageResponse*) prototype {
  return [[Message_LoginMessageResponse builder] mergeFrom:prototype];
}
- (Message_LoginMessageResponse_Builder*) builder {
  return [Message_LoginMessageResponse builder];
}
@end

@interface Message_LoginMessageResponse_Builder()
@property (retain) Message_LoginMessageResponse* result;
@end

@implementation Message_LoginMessageResponse_Builder
@synthesize result;
- (void) dealloc {
  self.result = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.result = [[[Message_LoginMessageResponse alloc] init] autorelease];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return result;
}
- (Message_LoginMessageResponse_Builder*) clear {
  self.result = [[[Message_LoginMessageResponse alloc] init] autorelease];
  return self;
}
- (Message_LoginMessageResponse_Builder*) clone {
  return [Message_LoginMessageResponse builderWithPrototype:result];
}
- (Message_LoginMessageResponse*) defaultInstance {
  return [Message_LoginMessageResponse defaultInstance];
}
- (Message_LoginMessageResponse*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (Message_LoginMessageResponse*) buildPartial {
  Message_LoginMessageResponse* returnMe = [[result retain] autorelease];
  self.result = nil;
  return returnMe;
}
- (Message_LoginMessageResponse_Builder*) mergeFrom:(Message_LoginMessageResponse*) other {
  if (other == [Message_LoginMessageResponse defaultInstance]) {
    return self;
  }
  if (other.hasStatus) {
    [self setStatus:other.status];
  }
  if (other.hasUserId) {
    [self setUserId:other.userId];
  }
  if (other.hasUserName) {
    [self setUserName:other.userName];
  }
  if (other.hasPassword) {
    [self setPassword:other.password];
  }
  if (other.hasNickName) {
    [self setNickName:other.nickName];
  }
  if (other.hasSex) {
    [self setSex:other.sex];
  }
  if (other.hasBirthday) {
    [self setBirthday:other.birthday];
  }
  if (other.hasAvatarUrl) {
    [self setAvatarUrl:other.avatarUrl];
  }
  if (other.hasAvatarId) {
    [self setAvatarId:other.avatarId];
  }
  if (other.hasAppId) {
    [self setAppId:other.appId];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (Message_LoginMessageResponse_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (Message_LoginMessageResponse_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSet_Builder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    int32_t tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 8: {
        [self setStatus:[input readInt32]];
        break;
      }
      case 18: {
        [self setUserId:[input readString]];
        break;
      }
      case 26: {
        [self setUserName:[input readString]];
        break;
      }
      case 34: {
        [self setPassword:[input readString]];
        break;
      }
      case 42: {
        [self setNickName:[input readString]];
        break;
      }
      case 48: {
        [self setSex:[input readInt32]];
        break;
      }
      case 58: {
        [self setBirthday:[input readString]];
        break;
      }
      case 66: {
        [self setAvatarUrl:[input readString]];
        break;
      }
      case 72: {
        [self setAvatarId:[input readInt32]];
        break;
      }
      case 82: {
        [self setAppId:[input readString]];
        break;
      }
    }
  }
}
- (BOOL) hasStatus {
  return result.hasStatus;
}
- (int32_t) status {
  return result.status;
}
- (Message_LoginMessageResponse_Builder*) setStatus:(int32_t) value {
  result.hasStatus = YES;
  result.status = value;
  return self;
}
- (Message_LoginMessageResponse_Builder*) clearStatus {
  result.hasStatus = NO;
  result.status = 0;
  return self;
}
- (BOOL) hasUserId {
  return result.hasUserId;
}
- (NSString*) userId {
  return result.userId;
}
- (Message_LoginMessageResponse_Builder*) setUserId:(NSString*) value {
  result.hasUserId = YES;
  result.userId = value;
  return self;
}
- (Message_LoginMessageResponse_Builder*) clearUserId {
  result.hasUserId = NO;
  result.userId = @"";
  return self;
}
- (BOOL) hasUserName {
  return result.hasUserName;
}
- (NSString*) userName {
  return result.userName;
}
- (Message_LoginMessageResponse_Builder*) setUserName:(NSString*) value {
  result.hasUserName = YES;
  result.userName = value;
  return self;
}
- (Message_LoginMessageResponse_Builder*) clearUserName {
  result.hasUserName = NO;
  result.userName = @"";
  return self;
}
- (BOOL) hasPassword {
  return result.hasPassword;
}
- (NSString*) password {
  return result.password;
}
- (Message_LoginMessageResponse_Builder*) setPassword:(NSString*) value {
  result.hasPassword = YES;
  result.password = value;
  return self;
}
- (Message_LoginMessageResponse_Builder*) clearPassword {
  result.hasPassword = NO;
  result.password = @"";
  return self;
}
- (BOOL) hasNickName {
  return result.hasNickName;
}
- (NSString*) nickName {
  return result.nickName;
}
- (Message_LoginMessageResponse_Builder*) setNickName:(NSString*) value {
  result.hasNickName = YES;
  result.nickName = value;
  return self;
}
- (Message_LoginMessageResponse_Builder*) clearNickName {
  result.hasNickName = NO;
  result.nickName = @"";
  return self;
}
- (BOOL) hasSex {
  return result.hasSex;
}
- (int32_t) sex {
  return result.sex;
}
- (Message_LoginMessageResponse_Builder*) setSex:(int32_t) value {
  result.hasSex = YES;
  result.sex = value;
  return self;
}
- (Message_LoginMessageResponse_Builder*) clearSex {
  result.hasSex = NO;
  result.sex = 0;
  return self;
}
- (BOOL) hasBirthday {
  return result.hasBirthday;
}
- (NSString*) birthday {
  return result.birthday;
}
- (Message_LoginMessageResponse_Builder*) setBirthday:(NSString*) value {
  result.hasBirthday = YES;
  result.birthday = value;
  return self;
}
- (Message_LoginMessageResponse_Builder*) clearBirthday {
  result.hasBirthday = NO;
  result.birthday = @"";
  return self;
}
- (BOOL) hasAvatarUrl {
  return result.hasAvatarUrl;
}
- (NSString*) avatarUrl {
  return result.avatarUrl;
}
- (Message_LoginMessageResponse_Builder*) setAvatarUrl:(NSString*) value {
  result.hasAvatarUrl = YES;
  result.avatarUrl = value;
  return self;
}
- (Message_LoginMessageResponse_Builder*) clearAvatarUrl {
  result.hasAvatarUrl = NO;
  result.avatarUrl = @"";
  return self;
}
- (BOOL) hasAvatarId {
  return result.hasAvatarId;
}
- (int32_t) avatarId {
  return result.avatarId;
}
- (Message_LoginMessageResponse_Builder*) setAvatarId:(int32_t) value {
  result.hasAvatarId = YES;
  result.avatarId = value;
  return self;
}
- (Message_LoginMessageResponse_Builder*) clearAvatarId {
  result.hasAvatarId = NO;
  result.avatarId = 0;
  return self;
}
- (BOOL) hasAppId {
  return result.hasAppId;
}
- (NSString*) appId {
  return result.appId;
}
- (Message_LoginMessageResponse_Builder*) setAppId:(NSString*) value {
  result.hasAppId = YES;
  result.appId = value;
  return self;
}
- (Message_LoginMessageResponse_Builder*) clearAppId {
  result.hasAppId = NO;
  result.appId = @"";
  return self;
}
@end

@interface Message_LogoutMessageRequest ()
@property (retain) NSString* phoneNumber;
@property (retain) NSString* email;
@end

@implementation Message_LogoutMessageRequest

- (BOOL) hasPhoneNumber {
  return !!hasPhoneNumber_;
}
- (void) setHasPhoneNumber:(BOOL) value {
  hasPhoneNumber_ = !!value;
}
@synthesize phoneNumber;
- (BOOL) hasEmail {
  return !!hasEmail_;
}
- (void) setHasEmail:(BOOL) value {
  hasEmail_ = !!value;
}
@synthesize email;
- (void) dealloc {
  self.phoneNumber = nil;
  self.email = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.phoneNumber = @"";
    self.email = @"";
  }
  return self;
}
static Message_LogoutMessageRequest* defaultMessage_LogoutMessageRequestInstance = nil;
+ (void) initialize {
  if (self == [Message_LogoutMessageRequest class]) {
    defaultMessage_LogoutMessageRequestInstance = [[Message_LogoutMessageRequest alloc] init];
  }
}
+ (Message_LogoutMessageRequest*) defaultInstance {
  return defaultMessage_LogoutMessageRequestInstance;
}
- (Message_LogoutMessageRequest*) defaultInstance {
  return defaultMessage_LogoutMessageRequestInstance;
}
- (BOOL) isInitialized {
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasPhoneNumber) {
    [output writeString:1 value:self.phoneNumber];
  }
  if (self.hasEmail) {
    [output writeString:2 value:self.email];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (int32_t) serializedSize {
  int32_t size = memoizedSerializedSize;
  if (size != -1) {
    return size;
  }

  size = 0;
  if (self.hasPhoneNumber) {
    size += computeStringSize(1, self.phoneNumber);
  }
  if (self.hasEmail) {
    size += computeStringSize(2, self.email);
  }
  size += self.unknownFields.serializedSize;
  memoizedSerializedSize = size;
  return size;
}
+ (Message_LogoutMessageRequest*) parseFromData:(NSData*) data {
  return (Message_LogoutMessageRequest*)[[[Message_LogoutMessageRequest builder] mergeFromData:data] build];
}
+ (Message_LogoutMessageRequest*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (Message_LogoutMessageRequest*)[[[Message_LogoutMessageRequest builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (Message_LogoutMessageRequest*) parseFromInputStream:(NSInputStream*) input {
  return (Message_LogoutMessageRequest*)[[[Message_LogoutMessageRequest builder] mergeFromInputStream:input] build];
}
+ (Message_LogoutMessageRequest*) parseDelimitedFromInputStream:(NSInputStream*) input {
  return (Message_LogoutMessageRequest*)[[[Message_LogoutMessageRequest builder] mergeDelimitedFromInputStream:input] build];
}
+ (Message_LogoutMessageRequest*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (Message_LogoutMessageRequest*)[[[Message_LogoutMessageRequest builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (Message_LogoutMessageRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (Message_LogoutMessageRequest*)[[[Message_LogoutMessageRequest builder] mergeFromCodedInputStream:input] build];
}
+ (Message_LogoutMessageRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (Message_LogoutMessageRequest*)[[[Message_LogoutMessageRequest builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (Message_LogoutMessageRequest_Builder*) builder {
  return [[[Message_LogoutMessageRequest_Builder alloc] init] autorelease];
}
+ (Message_LogoutMessageRequest_Builder*) builderWithPrototype:(Message_LogoutMessageRequest*) prototype {
  return [[Message_LogoutMessageRequest builder] mergeFrom:prototype];
}
- (Message_LogoutMessageRequest_Builder*) builder {
  return [Message_LogoutMessageRequest builder];
}
@end

@interface Message_LogoutMessageRequest_Builder()
@property (retain) Message_LogoutMessageRequest* result;
@end

@implementation Message_LogoutMessageRequest_Builder
@synthesize result;
- (void) dealloc {
  self.result = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.result = [[[Message_LogoutMessageRequest alloc] init] autorelease];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return result;
}
- (Message_LogoutMessageRequest_Builder*) clear {
  self.result = [[[Message_LogoutMessageRequest alloc] init] autorelease];
  return self;
}
- (Message_LogoutMessageRequest_Builder*) clone {
  return [Message_LogoutMessageRequest builderWithPrototype:result];
}
- (Message_LogoutMessageRequest*) defaultInstance {
  return [Message_LogoutMessageRequest defaultInstance];
}
- (Message_LogoutMessageRequest*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (Message_LogoutMessageRequest*) buildPartial {
  Message_LogoutMessageRequest* returnMe = [[result retain] autorelease];
  self.result = nil;
  return returnMe;
}
- (Message_LogoutMessageRequest_Builder*) mergeFrom:(Message_LogoutMessageRequest*) other {
  if (other == [Message_LogoutMessageRequest defaultInstance]) {
    return self;
  }
  if (other.hasPhoneNumber) {
    [self setPhoneNumber:other.phoneNumber];
  }
  if (other.hasEmail) {
    [self setEmail:other.email];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (Message_LogoutMessageRequest_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (Message_LogoutMessageRequest_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSet_Builder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    int32_t tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 10: {
        [self setPhoneNumber:[input readString]];
        break;
      }
      case 18: {
        [self setEmail:[input readString]];
        break;
      }
    }
  }
}
- (BOOL) hasPhoneNumber {
  return result.hasPhoneNumber;
}
- (NSString*) phoneNumber {
  return result.phoneNumber;
}
- (Message_LogoutMessageRequest_Builder*) setPhoneNumber:(NSString*) value {
  result.hasPhoneNumber = YES;
  result.phoneNumber = value;
  return self;
}
- (Message_LogoutMessageRequest_Builder*) clearPhoneNumber {
  result.hasPhoneNumber = NO;
  result.phoneNumber = @"";
  return self;
}
- (BOOL) hasEmail {
  return result.hasEmail;
}
- (NSString*) email {
  return result.email;
}
- (Message_LogoutMessageRequest_Builder*) setEmail:(NSString*) value {
  result.hasEmail = YES;
  result.email = value;
  return self;
}
- (Message_LogoutMessageRequest_Builder*) clearEmail {
  result.hasEmail = NO;
  result.email = @"";
  return self;
}
@end

@interface Message_LogoutMessageResponse ()
@property int32_t status;
@end

@implementation Message_LogoutMessageResponse

- (BOOL) hasStatus {
  return !!hasStatus_;
}
- (void) setHasStatus:(BOOL) value {
  hasStatus_ = !!value;
}
@synthesize status;
- (void) dealloc {
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.status = 0;
  }
  return self;
}
static Message_LogoutMessageResponse* defaultMessage_LogoutMessageResponseInstance = nil;
+ (void) initialize {
  if (self == [Message_LogoutMessageResponse class]) {
    defaultMessage_LogoutMessageResponseInstance = [[Message_LogoutMessageResponse alloc] init];
  }
}
+ (Message_LogoutMessageResponse*) defaultInstance {
  return defaultMessage_LogoutMessageResponseInstance;
}
- (Message_LogoutMessageResponse*) defaultInstance {
  return defaultMessage_LogoutMessageResponseInstance;
}
- (BOOL) isInitialized {
  if (!self.hasStatus) {
    return NO;
  }
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasStatus) {
    [output writeInt32:1 value:self.status];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (int32_t) serializedSize {
  int32_t size = memoizedSerializedSize;
  if (size != -1) {
    return size;
  }

  size = 0;
  if (self.hasStatus) {
    size += computeInt32Size(1, self.status);
  }
  size += self.unknownFields.serializedSize;
  memoizedSerializedSize = size;
  return size;
}
+ (Message_LogoutMessageResponse*) parseFromData:(NSData*) data {
  return (Message_LogoutMessageResponse*)[[[Message_LogoutMessageResponse builder] mergeFromData:data] build];
}
+ (Message_LogoutMessageResponse*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (Message_LogoutMessageResponse*)[[[Message_LogoutMessageResponse builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (Message_LogoutMessageResponse*) parseFromInputStream:(NSInputStream*) input {
  return (Message_LogoutMessageResponse*)[[[Message_LogoutMessageResponse builder] mergeFromInputStream:input] build];
}
+ (Message_LogoutMessageResponse*) parseDelimitedFromInputStream:(NSInputStream*) input {
  return (Message_LogoutMessageResponse*)[[[Message_LogoutMessageResponse builder] mergeDelimitedFromInputStream:input] build];
}
+ (Message_LogoutMessageResponse*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (Message_LogoutMessageResponse*)[[[Message_LogoutMessageResponse builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (Message_LogoutMessageResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (Message_LogoutMessageResponse*)[[[Message_LogoutMessageResponse builder] mergeFromCodedInputStream:input] build];
}
+ (Message_LogoutMessageResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (Message_LogoutMessageResponse*)[[[Message_LogoutMessageResponse builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (Message_LogoutMessageResponse_Builder*) builder {
  return [[[Message_LogoutMessageResponse_Builder alloc] init] autorelease];
}
+ (Message_LogoutMessageResponse_Builder*) builderWithPrototype:(Message_LogoutMessageResponse*) prototype {
  return [[Message_LogoutMessageResponse builder] mergeFrom:prototype];
}
- (Message_LogoutMessageResponse_Builder*) builder {
  return [Message_LogoutMessageResponse builder];
}
@end

@interface Message_LogoutMessageResponse_Builder()
@property (retain) Message_LogoutMessageResponse* result;
@end

@implementation Message_LogoutMessageResponse_Builder
@synthesize result;
- (void) dealloc {
  self.result = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.result = [[[Message_LogoutMessageResponse alloc] init] autorelease];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return result;
}
- (Message_LogoutMessageResponse_Builder*) clear {
  self.result = [[[Message_LogoutMessageResponse alloc] init] autorelease];
  return self;
}
- (Message_LogoutMessageResponse_Builder*) clone {
  return [Message_LogoutMessageResponse builderWithPrototype:result];
}
- (Message_LogoutMessageResponse*) defaultInstance {
  return [Message_LogoutMessageResponse defaultInstance];
}
- (Message_LogoutMessageResponse*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (Message_LogoutMessageResponse*) buildPartial {
  Message_LogoutMessageResponse* returnMe = [[result retain] autorelease];
  self.result = nil;
  return returnMe;
}
- (Message_LogoutMessageResponse_Builder*) mergeFrom:(Message_LogoutMessageResponse*) other {
  if (other == [Message_LogoutMessageResponse defaultInstance]) {
    return self;
  }
  if (other.hasStatus) {
    [self setStatus:other.status];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (Message_LogoutMessageResponse_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (Message_LogoutMessageResponse_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSet_Builder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    int32_t tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 8: {
        [self setStatus:[input readInt32]];
        break;
      }
    }
  }
}
- (BOOL) hasStatus {
  return result.hasStatus;
}
- (int32_t) status {
  return result.status;
}
- (Message_LogoutMessageResponse_Builder*) setStatus:(int32_t) value {
  result.hasStatus = YES;
  result.status = value;
  return self;
}
- (Message_LogoutMessageResponse_Builder*) clearStatus {
  result.hasStatus = NO;
  result.status = 0;
  return self;
}
@end

@interface Message_ForgetPasswordMessageRequest ()
@property (retain) NSString* phoneNumber;
@property (retain) NSString* email;
@end

@implementation Message_ForgetPasswordMessageRequest

- (BOOL) hasPhoneNumber {
  return !!hasPhoneNumber_;
}
- (void) setHasPhoneNumber:(BOOL) value {
  hasPhoneNumber_ = !!value;
}
@synthesize phoneNumber;
- (BOOL) hasEmail {
  return !!hasEmail_;
}
- (void) setHasEmail:(BOOL) value {
  hasEmail_ = !!value;
}
@synthesize email;
- (void) dealloc {
  self.phoneNumber = nil;
  self.email = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.phoneNumber = @"";
    self.email = @"";
  }
  return self;
}
static Message_ForgetPasswordMessageRequest* defaultMessage_ForgetPasswordMessageRequestInstance = nil;
+ (void) initialize {
  if (self == [Message_ForgetPasswordMessageRequest class]) {
    defaultMessage_ForgetPasswordMessageRequestInstance = [[Message_ForgetPasswordMessageRequest alloc] init];
  }
}
+ (Message_ForgetPasswordMessageRequest*) defaultInstance {
  return defaultMessage_ForgetPasswordMessageRequestInstance;
}
- (Message_ForgetPasswordMessageRequest*) defaultInstance {
  return defaultMessage_ForgetPasswordMessageRequestInstance;
}
- (BOOL) isInitialized {
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasPhoneNumber) {
    [output writeString:1 value:self.phoneNumber];
  }
  if (self.hasEmail) {
    [output writeString:2 value:self.email];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (int32_t) serializedSize {
  int32_t size = memoizedSerializedSize;
  if (size != -1) {
    return size;
  }

  size = 0;
  if (self.hasPhoneNumber) {
    size += computeStringSize(1, self.phoneNumber);
  }
  if (self.hasEmail) {
    size += computeStringSize(2, self.email);
  }
  size += self.unknownFields.serializedSize;
  memoizedSerializedSize = size;
  return size;
}
+ (Message_ForgetPasswordMessageRequest*) parseFromData:(NSData*) data {
  return (Message_ForgetPasswordMessageRequest*)[[[Message_ForgetPasswordMessageRequest builder] mergeFromData:data] build];
}
+ (Message_ForgetPasswordMessageRequest*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (Message_ForgetPasswordMessageRequest*)[[[Message_ForgetPasswordMessageRequest builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (Message_ForgetPasswordMessageRequest*) parseFromInputStream:(NSInputStream*) input {
  return (Message_ForgetPasswordMessageRequest*)[[[Message_ForgetPasswordMessageRequest builder] mergeFromInputStream:input] build];
}
+ (Message_ForgetPasswordMessageRequest*) parseDelimitedFromInputStream:(NSInputStream*) input {
  return (Message_ForgetPasswordMessageRequest*)[[[Message_ForgetPasswordMessageRequest builder] mergeDelimitedFromInputStream:input] build];
}
+ (Message_ForgetPasswordMessageRequest*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (Message_ForgetPasswordMessageRequest*)[[[Message_ForgetPasswordMessageRequest builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (Message_ForgetPasswordMessageRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (Message_ForgetPasswordMessageRequest*)[[[Message_ForgetPasswordMessageRequest builder] mergeFromCodedInputStream:input] build];
}
+ (Message_ForgetPasswordMessageRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (Message_ForgetPasswordMessageRequest*)[[[Message_ForgetPasswordMessageRequest builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (Message_ForgetPasswordMessageRequest_Builder*) builder {
  return [[[Message_ForgetPasswordMessageRequest_Builder alloc] init] autorelease];
}
+ (Message_ForgetPasswordMessageRequest_Builder*) builderWithPrototype:(Message_ForgetPasswordMessageRequest*) prototype {
  return [[Message_ForgetPasswordMessageRequest builder] mergeFrom:prototype];
}
- (Message_ForgetPasswordMessageRequest_Builder*) builder {
  return [Message_ForgetPasswordMessageRequest builder];
}
@end

@interface Message_ForgetPasswordMessageRequest_Builder()
@property (retain) Message_ForgetPasswordMessageRequest* result;
@end

@implementation Message_ForgetPasswordMessageRequest_Builder
@synthesize result;
- (void) dealloc {
  self.result = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.result = [[[Message_ForgetPasswordMessageRequest alloc] init] autorelease];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return result;
}
- (Message_ForgetPasswordMessageRequest_Builder*) clear {
  self.result = [[[Message_ForgetPasswordMessageRequest alloc] init] autorelease];
  return self;
}
- (Message_ForgetPasswordMessageRequest_Builder*) clone {
  return [Message_ForgetPasswordMessageRequest builderWithPrototype:result];
}
- (Message_ForgetPasswordMessageRequest*) defaultInstance {
  return [Message_ForgetPasswordMessageRequest defaultInstance];
}
- (Message_ForgetPasswordMessageRequest*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (Message_ForgetPasswordMessageRequest*) buildPartial {
  Message_ForgetPasswordMessageRequest* returnMe = [[result retain] autorelease];
  self.result = nil;
  return returnMe;
}
- (Message_ForgetPasswordMessageRequest_Builder*) mergeFrom:(Message_ForgetPasswordMessageRequest*) other {
  if (other == [Message_ForgetPasswordMessageRequest defaultInstance]) {
    return self;
  }
  if (other.hasPhoneNumber) {
    [self setPhoneNumber:other.phoneNumber];
  }
  if (other.hasEmail) {
    [self setEmail:other.email];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (Message_ForgetPasswordMessageRequest_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (Message_ForgetPasswordMessageRequest_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSet_Builder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    int32_t tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 10: {
        [self setPhoneNumber:[input readString]];
        break;
      }
      case 18: {
        [self setEmail:[input readString]];
        break;
      }
    }
  }
}
- (BOOL) hasPhoneNumber {
  return result.hasPhoneNumber;
}
- (NSString*) phoneNumber {
  return result.phoneNumber;
}
- (Message_ForgetPasswordMessageRequest_Builder*) setPhoneNumber:(NSString*) value {
  result.hasPhoneNumber = YES;
  result.phoneNumber = value;
  return self;
}
- (Message_ForgetPasswordMessageRequest_Builder*) clearPhoneNumber {
  result.hasPhoneNumber = NO;
  result.phoneNumber = @"";
  return self;
}
- (BOOL) hasEmail {
  return result.hasEmail;
}
- (NSString*) email {
  return result.email;
}
- (Message_ForgetPasswordMessageRequest_Builder*) setEmail:(NSString*) value {
  result.hasEmail = YES;
  result.email = value;
  return self;
}
- (Message_ForgetPasswordMessageRequest_Builder*) clearEmail {
  result.hasEmail = NO;
  result.email = @"";
  return self;
}
@end

@interface Message_ForgetPasswordMessageResponse ()
@property int32_t status;
@end

@implementation Message_ForgetPasswordMessageResponse

- (BOOL) hasStatus {
  return !!hasStatus_;
}
- (void) setHasStatus:(BOOL) value {
  hasStatus_ = !!value;
}
@synthesize status;
- (void) dealloc {
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.status = 0;
  }
  return self;
}
static Message_ForgetPasswordMessageResponse* defaultMessage_ForgetPasswordMessageResponseInstance = nil;
+ (void) initialize {
  if (self == [Message_ForgetPasswordMessageResponse class]) {
    defaultMessage_ForgetPasswordMessageResponseInstance = [[Message_ForgetPasswordMessageResponse alloc] init];
  }
}
+ (Message_ForgetPasswordMessageResponse*) defaultInstance {
  return defaultMessage_ForgetPasswordMessageResponseInstance;
}
- (Message_ForgetPasswordMessageResponse*) defaultInstance {
  return defaultMessage_ForgetPasswordMessageResponseInstance;
}
- (BOOL) isInitialized {
  if (!self.hasStatus) {
    return NO;
  }
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasStatus) {
    [output writeInt32:1 value:self.status];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (int32_t) serializedSize {
  int32_t size = memoizedSerializedSize;
  if (size != -1) {
    return size;
  }

  size = 0;
  if (self.hasStatus) {
    size += computeInt32Size(1, self.status);
  }
  size += self.unknownFields.serializedSize;
  memoizedSerializedSize = size;
  return size;
}
+ (Message_ForgetPasswordMessageResponse*) parseFromData:(NSData*) data {
  return (Message_ForgetPasswordMessageResponse*)[[[Message_ForgetPasswordMessageResponse builder] mergeFromData:data] build];
}
+ (Message_ForgetPasswordMessageResponse*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (Message_ForgetPasswordMessageResponse*)[[[Message_ForgetPasswordMessageResponse builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (Message_ForgetPasswordMessageResponse*) parseFromInputStream:(NSInputStream*) input {
  return (Message_ForgetPasswordMessageResponse*)[[[Message_ForgetPasswordMessageResponse builder] mergeFromInputStream:input] build];
}
+ (Message_ForgetPasswordMessageResponse*) parseDelimitedFromInputStream:(NSInputStream*) input {
  return (Message_ForgetPasswordMessageResponse*)[[[Message_ForgetPasswordMessageResponse builder] mergeDelimitedFromInputStream:input] build];
}
+ (Message_ForgetPasswordMessageResponse*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (Message_ForgetPasswordMessageResponse*)[[[Message_ForgetPasswordMessageResponse builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (Message_ForgetPasswordMessageResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (Message_ForgetPasswordMessageResponse*)[[[Message_ForgetPasswordMessageResponse builder] mergeFromCodedInputStream:input] build];
}
+ (Message_ForgetPasswordMessageResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (Message_ForgetPasswordMessageResponse*)[[[Message_ForgetPasswordMessageResponse builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (Message_ForgetPasswordMessageResponse_Builder*) builder {
  return [[[Message_ForgetPasswordMessageResponse_Builder alloc] init] autorelease];
}
+ (Message_ForgetPasswordMessageResponse_Builder*) builderWithPrototype:(Message_ForgetPasswordMessageResponse*) prototype {
  return [[Message_ForgetPasswordMessageResponse builder] mergeFrom:prototype];
}
- (Message_ForgetPasswordMessageResponse_Builder*) builder {
  return [Message_ForgetPasswordMessageResponse builder];
}
@end

@interface Message_ForgetPasswordMessageResponse_Builder()
@property (retain) Message_ForgetPasswordMessageResponse* result;
@end

@implementation Message_ForgetPasswordMessageResponse_Builder
@synthesize result;
- (void) dealloc {
  self.result = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.result = [[[Message_ForgetPasswordMessageResponse alloc] init] autorelease];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return result;
}
- (Message_ForgetPasswordMessageResponse_Builder*) clear {
  self.result = [[[Message_ForgetPasswordMessageResponse alloc] init] autorelease];
  return self;
}
- (Message_ForgetPasswordMessageResponse_Builder*) clone {
  return [Message_ForgetPasswordMessageResponse builderWithPrototype:result];
}
- (Message_ForgetPasswordMessageResponse*) defaultInstance {
  return [Message_ForgetPasswordMessageResponse defaultInstance];
}
- (Message_ForgetPasswordMessageResponse*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (Message_ForgetPasswordMessageResponse*) buildPartial {
  Message_ForgetPasswordMessageResponse* returnMe = [[result retain] autorelease];
  self.result = nil;
  return returnMe;
}
- (Message_ForgetPasswordMessageResponse_Builder*) mergeFrom:(Message_ForgetPasswordMessageResponse*) other {
  if (other == [Message_ForgetPasswordMessageResponse defaultInstance]) {
    return self;
  }
  if (other.hasStatus) {
    [self setStatus:other.status];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (Message_ForgetPasswordMessageResponse_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (Message_ForgetPasswordMessageResponse_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSet_Builder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    int32_t tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 8: {
        [self setStatus:[input readInt32]];
        break;
      }
    }
  }
}
- (BOOL) hasStatus {
  return result.hasStatus;
}
- (int32_t) status {
  return result.status;
}
- (Message_ForgetPasswordMessageResponse_Builder*) setStatus:(int32_t) value {
  result.hasStatus = YES;
  result.status = value;
  return self;
}
- (Message_ForgetPasswordMessageResponse_Builder*) clearStatus {
  result.hasStatus = NO;
  result.status = 0;
  return self;
}
@end

@interface Message_Builder()
@property (retain) Message* result;
@end

@implementation Message_Builder
@synthesize result;
- (void) dealloc {
  self.result = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.result = [[[Message alloc] init] autorelease];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return result;
}
- (Message_Builder*) clear {
  self.result = [[[Message alloc] init] autorelease];
  return self;
}
- (Message_Builder*) clone {
  return [Message builderWithPrototype:result];
}
- (Message*) defaultInstance {
  return [Message defaultInstance];
}
- (Message*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (Message*) buildPartial {
  Message* returnMe = [[result retain] autorelease];
  self.result = nil;
  return returnMe;
}
- (Message_Builder*) mergeFrom:(Message*) other {
  if (other == [Message defaultInstance]) {
    return self;
  }
  if (other.hasType) {
    [self setType:other.type];
  }
  if (other.hasSubRequest) {
    [self mergeSubRequest:other.subRequest];
  }
  if (other.hasSubResponse) {
    [self mergeSubResponse:other.subResponse];
  }
  if (other.hasLoginRequest) {
    [self mergeLoginRequest:other.loginRequest];
  }
  if (other.hasLoginResponse) {
    [self mergeLoginResponse:other.loginResponse];
  }
  if (other.hasLogoutRequest) {
    [self mergeLogoutRequest:other.logoutRequest];
  }
  if (other.hasLogoutResponse) {
    [self mergeLogoutResponse:other.logoutResponse];
  }
  if (other.hasForgetPwdRequest) {
    [self mergeForgetPwdRequest:other.forgetPwdRequest];
  }
  if (other.hasForgetPwdResponse) {
    [self mergeForgetPwdResponse:other.forgetPwdResponse];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (Message_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (Message_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSet_Builder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    int32_t tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 8: {
        int32_t value = [input readEnum];
        if (Message_MessageTypeIsValidValue(value)) {
          [self setType:value];
        } else {
          [unknownFields mergeVarintField:1 value:value];
        }
        break;
      }
      case 18: {
        Message_SubMessageRequest_Builder* subBuilder = [Message_SubMessageRequest builder];
        if (self.hasSubRequest) {
          [subBuilder mergeFrom:self.subRequest];
        }
        [input readMessage:subBuilder extensionRegistry:extensionRegistry];
        [self setSubRequest:[subBuilder buildPartial]];
        break;
      }
      case 26: {
        Message_SubMessageResponse_Builder* subBuilder = [Message_SubMessageResponse builder];
        if (self.hasSubResponse) {
          [subBuilder mergeFrom:self.subResponse];
        }
        [input readMessage:subBuilder extensionRegistry:extensionRegistry];
        [self setSubResponse:[subBuilder buildPartial]];
        break;
      }
      case 34: {
        Message_LoginMessageRequest_Builder* subBuilder = [Message_LoginMessageRequest builder];
        if (self.hasLoginRequest) {
          [subBuilder mergeFrom:self.loginRequest];
        }
        [input readMessage:subBuilder extensionRegistry:extensionRegistry];
        [self setLoginRequest:[subBuilder buildPartial]];
        break;
      }
      case 42: {
        Message_LoginMessageResponse_Builder* subBuilder = [Message_LoginMessageResponse builder];
        if (self.hasLoginResponse) {
          [subBuilder mergeFrom:self.loginResponse];
        }
        [input readMessage:subBuilder extensionRegistry:extensionRegistry];
        [self setLoginResponse:[subBuilder buildPartial]];
        break;
      }
      case 50: {
        Message_LogoutMessageRequest_Builder* subBuilder = [Message_LogoutMessageRequest builder];
        if (self.hasLogoutRequest) {
          [subBuilder mergeFrom:self.logoutRequest];
        }
        [input readMessage:subBuilder extensionRegistry:extensionRegistry];
        [self setLogoutRequest:[subBuilder buildPartial]];
        break;
      }
      case 58: {
        Message_LogoutMessageResponse_Builder* subBuilder = [Message_LogoutMessageResponse builder];
        if (self.hasLogoutResponse) {
          [subBuilder mergeFrom:self.logoutResponse];
        }
        [input readMessage:subBuilder extensionRegistry:extensionRegistry];
        [self setLogoutResponse:[subBuilder buildPartial]];
        break;
      }
      case 66: {
        Message_ForgetPasswordMessageRequest_Builder* subBuilder = [Message_ForgetPasswordMessageRequest builder];
        if (self.hasForgetPwdRequest) {
          [subBuilder mergeFrom:self.forgetPwdRequest];
        }
        [input readMessage:subBuilder extensionRegistry:extensionRegistry];
        [self setForgetPwdRequest:[subBuilder buildPartial]];
        break;
      }
      case 74: {
        Message_ForgetPasswordMessageResponse_Builder* subBuilder = [Message_ForgetPasswordMessageResponse builder];
        if (self.hasForgetPwdResponse) {
          [subBuilder mergeFrom:self.forgetPwdResponse];
        }
        [input readMessage:subBuilder extensionRegistry:extensionRegistry];
        [self setForgetPwdResponse:[subBuilder buildPartial]];
        break;
      }
    }
  }
}
- (BOOL) hasType {
  return result.hasType;
}
- (Message_MessageType) type {
  return result.type;
}
- (Message_Builder*) setType:(Message_MessageType) value {
  result.hasType = YES;
  result.type = value;
  return self;
}
- (Message_Builder*) clearType {
  result.hasType = NO;
  result.type = Message_MessageTypeSubscribeReq;
  return self;
}
- (BOOL) hasSubRequest {
  return result.hasSubRequest;
}
- (Message_SubMessageRequest*) subRequest {
  return result.subRequest;
}
- (Message_Builder*) setSubRequest:(Message_SubMessageRequest*) value {
  result.hasSubRequest = YES;
  result.subRequest = value;
  return self;
}
- (Message_Builder*) setSubRequestBuilder:(Message_SubMessageRequest_Builder*) builderForValue {
  return [self setSubRequest:[builderForValue build]];
}
- (Message_Builder*) mergeSubRequest:(Message_SubMessageRequest*) value {
  if (result.hasSubRequest &&
      result.subRequest != [Message_SubMessageRequest defaultInstance]) {
    result.subRequest =
      [[[Message_SubMessageRequest builderWithPrototype:result.subRequest] mergeFrom:value] buildPartial];
  } else {
    result.subRequest = value;
  }
  result.hasSubRequest = YES;
  return self;
}
- (Message_Builder*) clearSubRequest {
  result.hasSubRequest = NO;
  result.subRequest = [Message_SubMessageRequest defaultInstance];
  return self;
}
- (BOOL) hasSubResponse {
  return result.hasSubResponse;
}
- (Message_SubMessageResponse*) subResponse {
  return result.subResponse;
}
- (Message_Builder*) setSubResponse:(Message_SubMessageResponse*) value {
  result.hasSubResponse = YES;
  result.subResponse = value;
  return self;
}
- (Message_Builder*) setSubResponseBuilder:(Message_SubMessageResponse_Builder*) builderForValue {
  return [self setSubResponse:[builderForValue build]];
}
- (Message_Builder*) mergeSubResponse:(Message_SubMessageResponse*) value {
  if (result.hasSubResponse &&
      result.subResponse != [Message_SubMessageResponse defaultInstance]) {
    result.subResponse =
      [[[Message_SubMessageResponse builderWithPrototype:result.subResponse] mergeFrom:value] buildPartial];
  } else {
    result.subResponse = value;
  }
  result.hasSubResponse = YES;
  return self;
}
- (Message_Builder*) clearSubResponse {
  result.hasSubResponse = NO;
  result.subResponse = [Message_SubMessageResponse defaultInstance];
  return self;
}
- (BOOL) hasLoginRequest {
  return result.hasLoginRequest;
}
- (Message_LoginMessageRequest*) loginRequest {
  return result.loginRequest;
}
- (Message_Builder*) setLoginRequest:(Message_LoginMessageRequest*) value {
  result.hasLoginRequest = YES;
  result.loginRequest = value;
  return self;
}
- (Message_Builder*) setLoginRequestBuilder:(Message_LoginMessageRequest_Builder*) builderForValue {
  return [self setLoginRequest:[builderForValue build]];
}
- (Message_Builder*) mergeLoginRequest:(Message_LoginMessageRequest*) value {
  if (result.hasLoginRequest &&
      result.loginRequest != [Message_LoginMessageRequest defaultInstance]) {
    result.loginRequest =
      [[[Message_LoginMessageRequest builderWithPrototype:result.loginRequest] mergeFrom:value] buildPartial];
  } else {
    result.loginRequest = value;
  }
  result.hasLoginRequest = YES;
  return self;
}
- (Message_Builder*) clearLoginRequest {
  result.hasLoginRequest = NO;
  result.loginRequest = [Message_LoginMessageRequest defaultInstance];
  return self;
}
- (BOOL) hasLoginResponse {
  return result.hasLoginResponse;
}
- (Message_LoginMessageResponse*) loginResponse {
  return result.loginResponse;
}
- (Message_Builder*) setLoginResponse:(Message_LoginMessageResponse*) value {
  result.hasLoginResponse = YES;
  result.loginResponse = value;
  return self;
}
- (Message_Builder*) setLoginResponseBuilder:(Message_LoginMessageResponse_Builder*) builderForValue {
  return [self setLoginResponse:[builderForValue build]];
}
- (Message_Builder*) mergeLoginResponse:(Message_LoginMessageResponse*) value {
  if (result.hasLoginResponse &&
      result.loginResponse != [Message_LoginMessageResponse defaultInstance]) {
    result.loginResponse =
      [[[Message_LoginMessageResponse builderWithPrototype:result.loginResponse] mergeFrom:value] buildPartial];
  } else {
    result.loginResponse = value;
  }
  result.hasLoginResponse = YES;
  return self;
}
- (Message_Builder*) clearLoginResponse {
  result.hasLoginResponse = NO;
  result.loginResponse = [Message_LoginMessageResponse defaultInstance];
  return self;
}
- (BOOL) hasLogoutRequest {
  return result.hasLogoutRequest;
}
- (Message_LogoutMessageRequest*) logoutRequest {
  return result.logoutRequest;
}
- (Message_Builder*) setLogoutRequest:(Message_LogoutMessageRequest*) value {
  result.hasLogoutRequest = YES;
  result.logoutRequest = value;
  return self;
}
- (Message_Builder*) setLogoutRequestBuilder:(Message_LogoutMessageRequest_Builder*) builderForValue {
  return [self setLogoutRequest:[builderForValue build]];
}
- (Message_Builder*) mergeLogoutRequest:(Message_LogoutMessageRequest*) value {
  if (result.hasLogoutRequest &&
      result.logoutRequest != [Message_LogoutMessageRequest defaultInstance]) {
    result.logoutRequest =
      [[[Message_LogoutMessageRequest builderWithPrototype:result.logoutRequest] mergeFrom:value] buildPartial];
  } else {
    result.logoutRequest = value;
  }
  result.hasLogoutRequest = YES;
  return self;
}
- (Message_Builder*) clearLogoutRequest {
  result.hasLogoutRequest = NO;
  result.logoutRequest = [Message_LogoutMessageRequest defaultInstance];
  return self;
}
- (BOOL) hasLogoutResponse {
  return result.hasLogoutResponse;
}
- (Message_LogoutMessageResponse*) logoutResponse {
  return result.logoutResponse;
}
- (Message_Builder*) setLogoutResponse:(Message_LogoutMessageResponse*) value {
  result.hasLogoutResponse = YES;
  result.logoutResponse = value;
  return self;
}
- (Message_Builder*) setLogoutResponseBuilder:(Message_LogoutMessageResponse_Builder*) builderForValue {
  return [self setLogoutResponse:[builderForValue build]];
}
- (Message_Builder*) mergeLogoutResponse:(Message_LogoutMessageResponse*) value {
  if (result.hasLogoutResponse &&
      result.logoutResponse != [Message_LogoutMessageResponse defaultInstance]) {
    result.logoutResponse =
      [[[Message_LogoutMessageResponse builderWithPrototype:result.logoutResponse] mergeFrom:value] buildPartial];
  } else {
    result.logoutResponse = value;
  }
  result.hasLogoutResponse = YES;
  return self;
}
- (Message_Builder*) clearLogoutResponse {
  result.hasLogoutResponse = NO;
  result.logoutResponse = [Message_LogoutMessageResponse defaultInstance];
  return self;
}
- (BOOL) hasForgetPwdRequest {
  return result.hasForgetPwdRequest;
}
- (Message_ForgetPasswordMessageRequest*) forgetPwdRequest {
  return result.forgetPwdRequest;
}
- (Message_Builder*) setForgetPwdRequest:(Message_ForgetPasswordMessageRequest*) value {
  result.hasForgetPwdRequest = YES;
  result.forgetPwdRequest = value;
  return self;
}
- (Message_Builder*) setForgetPwdRequestBuilder:(Message_ForgetPasswordMessageRequest_Builder*) builderForValue {
  return [self setForgetPwdRequest:[builderForValue build]];
}
- (Message_Builder*) mergeForgetPwdRequest:(Message_ForgetPasswordMessageRequest*) value {
  if (result.hasForgetPwdRequest &&
      result.forgetPwdRequest != [Message_ForgetPasswordMessageRequest defaultInstance]) {
    result.forgetPwdRequest =
      [[[Message_ForgetPasswordMessageRequest builderWithPrototype:result.forgetPwdRequest] mergeFrom:value] buildPartial];
  } else {
    result.forgetPwdRequest = value;
  }
  result.hasForgetPwdRequest = YES;
  return self;
}
- (Message_Builder*) clearForgetPwdRequest {
  result.hasForgetPwdRequest = NO;
  result.forgetPwdRequest = [Message_ForgetPasswordMessageRequest defaultInstance];
  return self;
}
- (BOOL) hasForgetPwdResponse {
  return result.hasForgetPwdResponse;
}
- (Message_ForgetPasswordMessageResponse*) forgetPwdResponse {
  return result.forgetPwdResponse;
}
- (Message_Builder*) setForgetPwdResponse:(Message_ForgetPasswordMessageResponse*) value {
  result.hasForgetPwdResponse = YES;
  result.forgetPwdResponse = value;
  return self;
}
- (Message_Builder*) setForgetPwdResponseBuilder:(Message_ForgetPasswordMessageResponse_Builder*) builderForValue {
  return [self setForgetPwdResponse:[builderForValue build]];
}
- (Message_Builder*) mergeForgetPwdResponse:(Message_ForgetPasswordMessageResponse*) value {
  if (result.hasForgetPwdResponse &&
      result.forgetPwdResponse != [Message_ForgetPasswordMessageResponse defaultInstance]) {
    result.forgetPwdResponse =
      [[[Message_ForgetPasswordMessageResponse builderWithPrototype:result.forgetPwdResponse] mergeFrom:value] buildPartial];
  } else {
    result.forgetPwdResponse = value;
  }
  result.hasForgetPwdResponse = YES;
  return self;
}
- (Message_Builder*) clearForgetPwdResponse {
  result.hasForgetPwdResponse = NO;
  result.forgetPwdResponse = [Message_ForgetPasswordMessageResponse defaultInstance];
  return self;
}
@end

