// Generated by the protocol buffer compiler.  DO NOT EDIT!
#import "UIKit/UIKit.h"
#import "ProtocolBuffers.h"

@class Message;
@class Message_Builder;
@class Message_ForgetPasswordMessageRequest;
@class Message_ForgetPasswordMessageRequest_Builder;
@class Message_ForgetPasswordMessageResponse;
@class Message_ForgetPasswordMessageResponse_Builder;
@class Message_LoginMessageRequest;
@class Message_LoginMessageRequest_Builder;
@class Message_LoginMessageResponse;
@class Message_LoginMessageResponse_Builder;
@class Message_LogoutMessageRequest;
@class Message_LogoutMessageRequest_Builder;
@class Message_LogoutMessageResponse;
@class Message_LogoutMessageResponse_Builder;
@class Message_PictureChatMessageRequest;
@class Message_PictureChatMessageRequest_Builder;
@class Message_PictureChatMessageResponse;
@class Message_PictureChatMessageResponse_Builder;
@class Message_PictureFromServerRequest;
@class Message_PictureFromServerRequest_Builder;
@class Message_PictureFromServerResponse;
@class Message_PictureFromServerResponse_Builder;
@class Message_SubMessageRequest;
@class Message_SubMessageRequest_Builder;
@class Message_SubMessageResponse;
@class Message_SubMessageResponse_Builder;
@class Message_TextChatMessageRequest;
@class Message_TextChatMessageRequest_Builder;
@class Message_TextChatMessageResponse;
@class Message_TextChatMessageResponse_Builder;
@class Message_TextFromServerRequest;
@class Message_TextFromServerRequest_Builder;
@class Message_TextFromServerResponse;
@class Message_TextFromServerResponse_Builder;
@class Message_VideoChatMessageRequest;
@class Message_VideoChatMessageRequest_Builder;
@class Message_VideoChatMessageResponse;
@class Message_VideoChatMessageResponse_Builder;
@class Message_VoiceChatMessageRequest;
@class Message_VoiceChatMessageRequest_Builder;
@class Message_VoiceChatMessageResponse;
@class Message_VoiceChatMessageResponse_Builder;
@class Message_WhoAmIRequest;
@class Message_WhoAmIRequest_Builder;
@class Message_WhoAmIResponse;
@class Message_WhoAmIResponse_Builder;
typedef enum {
  Message_MessageTypeSubscribeReq = 0,
  Message_MessageTypeSubscribeResp = 1,
  Message_MessageTypeLoginReq = 2,
  Message_MessageTypeLoginResp = 3,
  Message_MessageTypeLogoutReq = 4,
  Message_MessageTypeLogoutResp = 5,
  Message_MessageTypeForgetPwdReq = 6,
  Message_MessageTypeForgetPwdResp = 7,
  Message_MessageTypeWhoAmIReq = 8,
  Message_MessageTypeWhoAmIResp = 9,
  Message_MessageTypeTextReq = 10,
  Message_MessageTypeTextResp = 11,
  Message_MessageTypeTextFromServerReq = 12,
  Message_MessageTypeTextFromServerResp = 13,
  Message_MessageTypePictureReq = 14,
  Message_MessageTypePictureResp = 15,
  Message_MessageTypePictureFromServerReq = 16,
  Message_MessageTypePictureFromServerResp = 17,
  Message_MessageTypeVoiceReq = 18,
  Message_MessageTypeVoiceResp = 19,
  Message_MessageTypeVoiceFromServerReq = 20,
  Message_MessageTypeVoiceFromServerResp = 21,
  Message_MessageTypeVideoReq = 22,
  Message_MessageTypeVideoResp = 23,
  Message_MessageTypeVideoFromServerReq = 24,
  Message_MessageTypeVideoFromServerResp = 25,
} Message_MessageType;

BOOL Message_MessageTypeIsValidValue(Message_MessageType value);


@interface AppRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface Message : PBGeneratedMessage {
@private
  BOOL hasSubRequest_:1;
  BOOL hasSubResponse_:1;
  BOOL hasLoginRequest_:1;
  BOOL hasLoginResponse_:1;
  BOOL hasLogoutRequest_:1;
  BOOL hasLogoutResponse_:1;
  BOOL hasForgetPwdRequest_:1;
  BOOL hasForgetPwdResponse_:1;
  BOOL hasWhoAmIrequest_:1;
  BOOL hasWhoAmIresponse_:1;
  BOOL hasTextChatMessageRequest_:1;
  BOOL hasTextChatMessageResponse_:1;
  BOOL hasPictureChatMessageRequest_:1;
  BOOL hasPictureChatMessageResponse_:1;
  BOOL hasVoiceChatMessageRequest_:1;
  BOOL hasVoiceChatMessageResponse_:1;
  BOOL hasVideoChatMessageRequest_:1;
  BOOL hasVideoChatMessageResponse_:1;
  BOOL hasTextFromServerRequest_:1;
  BOOL hasTextFromServerResponse_:1;
  BOOL hasPictureFromServerRequest_:1;
  BOOL hasPictureFromServerResponse_:1;
  BOOL hasType_:1;
  Message_SubMessageRequest* subRequest;
  Message_SubMessageResponse* subResponse;
  Message_LoginMessageRequest* loginRequest;
  Message_LoginMessageResponse* loginResponse;
  Message_LogoutMessageRequest* logoutRequest;
  Message_LogoutMessageResponse* logoutResponse;
  Message_ForgetPasswordMessageRequest* forgetPwdRequest;
  Message_ForgetPasswordMessageResponse* forgetPwdResponse;
  Message_WhoAmIRequest* whoAmIrequest;
  Message_WhoAmIResponse* whoAmIresponse;
  Message_TextChatMessageRequest* textChatMessageRequest;
  Message_TextChatMessageResponse* textChatMessageResponse;
  Message_PictureChatMessageRequest* pictureChatMessageRequest;
  Message_PictureChatMessageResponse* pictureChatMessageResponse;
  Message_VoiceChatMessageRequest* voiceChatMessageRequest;
  Message_VoiceChatMessageResponse* voiceChatMessageResponse;
  Message_VideoChatMessageRequest* videoChatMessageRequest;
  Message_VideoChatMessageResponse* videoChatMessageResponse;
  Message_TextFromServerRequest* textFromServerRequest;
  Message_TextFromServerResponse* textFromServerResponse;
  Message_PictureFromServerRequest* pictureFromServerRequest;
  Message_PictureFromServerResponse* pictureFromServerResponse;
  Message_MessageType type;
}
- (BOOL) hasType;
- (BOOL) hasSubRequest;
- (BOOL) hasSubResponse;
- (BOOL) hasLoginRequest;
- (BOOL) hasLoginResponse;
- (BOOL) hasLogoutRequest;
- (BOOL) hasLogoutResponse;
- (BOOL) hasForgetPwdRequest;
- (BOOL) hasForgetPwdResponse;
- (BOOL) hasWhoAmIrequest;
- (BOOL) hasWhoAmIresponse;
- (BOOL) hasTextChatMessageRequest;
- (BOOL) hasTextChatMessageResponse;
- (BOOL) hasPictureChatMessageRequest;
- (BOOL) hasPictureChatMessageResponse;
- (BOOL) hasVoiceChatMessageRequest;
- (BOOL) hasVoiceChatMessageResponse;
- (BOOL) hasVideoChatMessageRequest;
- (BOOL) hasVideoChatMessageResponse;
- (BOOL) hasTextFromServerRequest;
- (BOOL) hasTextFromServerResponse;
- (BOOL) hasPictureFromServerRequest;
- (BOOL) hasPictureFromServerResponse;
@property (readonly) Message_MessageType type;
@property (readonly, retain) Message_SubMessageRequest* subRequest;
@property (readonly, retain) Message_SubMessageResponse* subResponse;
@property (readonly, retain) Message_LoginMessageRequest* loginRequest;
@property (readonly, retain) Message_LoginMessageResponse* loginResponse;
@property (readonly, retain) Message_LogoutMessageRequest* logoutRequest;
@property (readonly, retain) Message_LogoutMessageResponse* logoutResponse;
@property (readonly, retain) Message_ForgetPasswordMessageRequest* forgetPwdRequest;
@property (readonly, retain) Message_ForgetPasswordMessageResponse* forgetPwdResponse;
@property (readonly, retain) Message_WhoAmIRequest* whoAmIrequest;
@property (readonly, retain) Message_WhoAmIResponse* whoAmIresponse;
@property (readonly, retain) Message_TextChatMessageRequest* textChatMessageRequest;
@property (readonly, retain) Message_TextChatMessageResponse* textChatMessageResponse;
@property (readonly, retain) Message_PictureChatMessageRequest* pictureChatMessageRequest;
@property (readonly, retain) Message_PictureChatMessageResponse* pictureChatMessageResponse;
@property (readonly, retain) Message_VoiceChatMessageRequest* voiceChatMessageRequest;
@property (readonly, retain) Message_VoiceChatMessageResponse* voiceChatMessageResponse;
@property (readonly, retain) Message_VideoChatMessageRequest* videoChatMessageRequest;
@property (readonly, retain) Message_VideoChatMessageResponse* videoChatMessageResponse;
@property (readonly, retain) Message_TextFromServerRequest* textFromServerRequest;
@property (readonly, retain) Message_TextFromServerResponse* textFromServerResponse;
@property (readonly, retain) Message_PictureFromServerRequest* pictureFromServerRequest;
@property (readonly, retain) Message_PictureFromServerResponse* pictureFromServerResponse;

+ (Message*) defaultInstance;
- (Message*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (Message_Builder*) builder;
+ (Message_Builder*) builder;
+ (Message_Builder*) builderWithPrototype:(Message*) prototype;

+ (Message*) parseFromData:(NSData*) data;
+ (Message*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Message*) parseFromInputStream:(NSInputStream*) input;
+ (Message*) parseDelimitedFromInputStream:(NSInputStream*) input;
+ (Message*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Message*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (Message*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface Message_SubMessageRequest : PBGeneratedMessage {
@private
  BOOL hasSex_:1;
  BOOL hasPhoneNumber_:1;
  BOOL hasEmail_:1;
  BOOL hasPassword_:1;
  int32_t sex;
  NSString* phoneNumber;
  NSString* email;
  NSString* password;
}
- (BOOL) hasPhoneNumber;
- (BOOL) hasEmail;
- (BOOL) hasPassword;
- (BOOL) hasSex;
@property (readonly, retain) NSString* phoneNumber;
@property (readonly, retain) NSString* email;
@property (readonly, retain) NSString* password;
@property (readonly) int32_t sex;

+ (Message_SubMessageRequest*) defaultInstance;
- (Message_SubMessageRequest*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (Message_SubMessageRequest_Builder*) builder;
+ (Message_SubMessageRequest_Builder*) builder;
+ (Message_SubMessageRequest_Builder*) builderWithPrototype:(Message_SubMessageRequest*) prototype;

+ (Message_SubMessageRequest*) parseFromData:(NSData*) data;
+ (Message_SubMessageRequest*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Message_SubMessageRequest*) parseFromInputStream:(NSInputStream*) input;
+ (Message_SubMessageRequest*) parseDelimitedFromInputStream:(NSInputStream*) input;
+ (Message_SubMessageRequest*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Message_SubMessageRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (Message_SubMessageRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface Message_SubMessageRequest_Builder : PBGeneratedMessage_Builder {
@private
  Message_SubMessageRequest* result;
}

- (Message_SubMessageRequest*) defaultInstance;

- (Message_SubMessageRequest_Builder*) clear;
- (Message_SubMessageRequest_Builder*) clone;

- (Message_SubMessageRequest*) build;
- (Message_SubMessageRequest*) buildPartial;

- (Message_SubMessageRequest_Builder*) mergeFrom:(Message_SubMessageRequest*) other;
- (Message_SubMessageRequest_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (Message_SubMessageRequest_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasPhoneNumber;
- (NSString*) phoneNumber;
- (Message_SubMessageRequest_Builder*) setPhoneNumber:(NSString*) value;
- (Message_SubMessageRequest_Builder*) clearPhoneNumber;

- (BOOL) hasEmail;
- (NSString*) email;
- (Message_SubMessageRequest_Builder*) setEmail:(NSString*) value;
- (Message_SubMessageRequest_Builder*) clearEmail;

- (BOOL) hasPassword;
- (NSString*) password;
- (Message_SubMessageRequest_Builder*) setPassword:(NSString*) value;
- (Message_SubMessageRequest_Builder*) clearPassword;

- (BOOL) hasSex;
- (int32_t) sex;
- (Message_SubMessageRequest_Builder*) setSex:(int32_t) value;
- (Message_SubMessageRequest_Builder*) clearSex;
@end

@interface Message_SubMessageResponse : PBGeneratedMessage {
@private
  BOOL hasStatus_:1;
  BOOL hasSex_:1;
  BOOL hasAvatarId_:1;
  BOOL hasUserId_:1;
  BOOL hasUserName_:1;
  BOOL hasPassword_:1;
  BOOL hasNickName_:1;
  BOOL hasBirthday_:1;
  BOOL hasAvatarUrl_:1;
  BOOL hasAppId_:1;
  int32_t status;
  int32_t sex;
  int32_t avatarId;
  NSString* userId;
  NSString* userName;
  NSString* password;
  NSString* nickName;
  NSString* birthday;
  NSString* avatarUrl;
  NSString* appId;
}
- (BOOL) hasStatus;
- (BOOL) hasUserId;
- (BOOL) hasUserName;
- (BOOL) hasPassword;
- (BOOL) hasNickName;
- (BOOL) hasSex;
- (BOOL) hasBirthday;
- (BOOL) hasAvatarUrl;
- (BOOL) hasAvatarId;
- (BOOL) hasAppId;
@property (readonly) int32_t status;
@property (readonly, retain) NSString* userId;
@property (readonly, retain) NSString* userName;
@property (readonly, retain) NSString* password;
@property (readonly, retain) NSString* nickName;
@property (readonly) int32_t sex;
@property (readonly, retain) NSString* birthday;
@property (readonly, retain) NSString* avatarUrl;
@property (readonly) int32_t avatarId;
@property (readonly, retain) NSString* appId;

+ (Message_SubMessageResponse*) defaultInstance;
- (Message_SubMessageResponse*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (Message_SubMessageResponse_Builder*) builder;
+ (Message_SubMessageResponse_Builder*) builder;
+ (Message_SubMessageResponse_Builder*) builderWithPrototype:(Message_SubMessageResponse*) prototype;

+ (Message_SubMessageResponse*) parseFromData:(NSData*) data;
+ (Message_SubMessageResponse*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Message_SubMessageResponse*) parseFromInputStream:(NSInputStream*) input;
+ (Message_SubMessageResponse*) parseDelimitedFromInputStream:(NSInputStream*) input;
+ (Message_SubMessageResponse*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Message_SubMessageResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (Message_SubMessageResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface Message_SubMessageResponse_Builder : PBGeneratedMessage_Builder {
@private
  Message_SubMessageResponse* result;
}

- (Message_SubMessageResponse*) defaultInstance;

- (Message_SubMessageResponse_Builder*) clear;
- (Message_SubMessageResponse_Builder*) clone;

- (Message_SubMessageResponse*) build;
- (Message_SubMessageResponse*) buildPartial;

- (Message_SubMessageResponse_Builder*) mergeFrom:(Message_SubMessageResponse*) other;
- (Message_SubMessageResponse_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (Message_SubMessageResponse_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasStatus;
- (int32_t) status;
- (Message_SubMessageResponse_Builder*) setStatus:(int32_t) value;
- (Message_SubMessageResponse_Builder*) clearStatus;

- (BOOL) hasUserId;
- (NSString*) userId;
- (Message_SubMessageResponse_Builder*) setUserId:(NSString*) value;
- (Message_SubMessageResponse_Builder*) clearUserId;

- (BOOL) hasUserName;
- (NSString*) userName;
- (Message_SubMessageResponse_Builder*) setUserName:(NSString*) value;
- (Message_SubMessageResponse_Builder*) clearUserName;

- (BOOL) hasPassword;
- (NSString*) password;
- (Message_SubMessageResponse_Builder*) setPassword:(NSString*) value;
- (Message_SubMessageResponse_Builder*) clearPassword;

- (BOOL) hasNickName;
- (NSString*) nickName;
- (Message_SubMessageResponse_Builder*) setNickName:(NSString*) value;
- (Message_SubMessageResponse_Builder*) clearNickName;

- (BOOL) hasSex;
- (int32_t) sex;
- (Message_SubMessageResponse_Builder*) setSex:(int32_t) value;
- (Message_SubMessageResponse_Builder*) clearSex;

- (BOOL) hasBirthday;
- (NSString*) birthday;
- (Message_SubMessageResponse_Builder*) setBirthday:(NSString*) value;
- (Message_SubMessageResponse_Builder*) clearBirthday;

- (BOOL) hasAvatarUrl;
- (NSString*) avatarUrl;
- (Message_SubMessageResponse_Builder*) setAvatarUrl:(NSString*) value;
- (Message_SubMessageResponse_Builder*) clearAvatarUrl;

- (BOOL) hasAvatarId;
- (int32_t) avatarId;
- (Message_SubMessageResponse_Builder*) setAvatarId:(int32_t) value;
- (Message_SubMessageResponse_Builder*) clearAvatarId;

- (BOOL) hasAppId;
- (NSString*) appId;
- (Message_SubMessageResponse_Builder*) setAppId:(NSString*) value;
- (Message_SubMessageResponse_Builder*) clearAppId;
@end

@interface Message_LoginMessageRequest : PBGeneratedMessage {
@private
  BOOL hasPhoneNumber_:1;
  BOOL hasEmail_:1;
  BOOL hasPassword_:1;
  NSString* phoneNumber;
  NSString* email;
  NSString* password;
}
- (BOOL) hasPhoneNumber;
- (BOOL) hasEmail;
- (BOOL) hasPassword;
@property (readonly, retain) NSString* phoneNumber;
@property (readonly, retain) NSString* email;
@property (readonly, retain) NSString* password;

+ (Message_LoginMessageRequest*) defaultInstance;
- (Message_LoginMessageRequest*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (Message_LoginMessageRequest_Builder*) builder;
+ (Message_LoginMessageRequest_Builder*) builder;
+ (Message_LoginMessageRequest_Builder*) builderWithPrototype:(Message_LoginMessageRequest*) prototype;

+ (Message_LoginMessageRequest*) parseFromData:(NSData*) data;
+ (Message_LoginMessageRequest*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Message_LoginMessageRequest*) parseFromInputStream:(NSInputStream*) input;
+ (Message_LoginMessageRequest*) parseDelimitedFromInputStream:(NSInputStream*) input;
+ (Message_LoginMessageRequest*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Message_LoginMessageRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (Message_LoginMessageRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface Message_LoginMessageRequest_Builder : PBGeneratedMessage_Builder {
@private
  Message_LoginMessageRequest* result;
}

- (Message_LoginMessageRequest*) defaultInstance;

- (Message_LoginMessageRequest_Builder*) clear;
- (Message_LoginMessageRequest_Builder*) clone;

- (Message_LoginMessageRequest*) build;
- (Message_LoginMessageRequest*) buildPartial;

- (Message_LoginMessageRequest_Builder*) mergeFrom:(Message_LoginMessageRequest*) other;
- (Message_LoginMessageRequest_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (Message_LoginMessageRequest_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasPhoneNumber;
- (NSString*) phoneNumber;
- (Message_LoginMessageRequest_Builder*) setPhoneNumber:(NSString*) value;
- (Message_LoginMessageRequest_Builder*) clearPhoneNumber;

- (BOOL) hasEmail;
- (NSString*) email;
- (Message_LoginMessageRequest_Builder*) setEmail:(NSString*) value;
- (Message_LoginMessageRequest_Builder*) clearEmail;

- (BOOL) hasPassword;
- (NSString*) password;
- (Message_LoginMessageRequest_Builder*) setPassword:(NSString*) value;
- (Message_LoginMessageRequest_Builder*) clearPassword;
@end

@interface Message_LoginMessageResponse : PBGeneratedMessage {
@private
  BOOL hasStatus_:1;
  BOOL hasSex_:1;
  BOOL hasAvatarId_:1;
  BOOL hasUserId_:1;
  BOOL hasUserName_:1;
  BOOL hasPassword_:1;
  BOOL hasNickName_:1;
  BOOL hasBirthday_:1;
  BOOL hasAvatarUrl_:1;
  BOOL hasAppId_:1;
  int32_t status;
  int32_t sex;
  int32_t avatarId;
  NSString* userId;
  NSString* userName;
  NSString* password;
  NSString* nickName;
  NSString* birthday;
  NSString* avatarUrl;
  NSString* appId;
}
- (BOOL) hasStatus;
- (BOOL) hasUserId;
- (BOOL) hasUserName;
- (BOOL) hasPassword;
- (BOOL) hasNickName;
- (BOOL) hasSex;
- (BOOL) hasBirthday;
- (BOOL) hasAvatarUrl;
- (BOOL) hasAvatarId;
- (BOOL) hasAppId;
@property (readonly) int32_t status;
@property (readonly, retain) NSString* userId;
@property (readonly, retain) NSString* userName;
@property (readonly, retain) NSString* password;
@property (readonly, retain) NSString* nickName;
@property (readonly) int32_t sex;
@property (readonly, retain) NSString* birthday;
@property (readonly, retain) NSString* avatarUrl;
@property (readonly) int32_t avatarId;
@property (readonly, retain) NSString* appId;

+ (Message_LoginMessageResponse*) defaultInstance;
- (Message_LoginMessageResponse*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (Message_LoginMessageResponse_Builder*) builder;
+ (Message_LoginMessageResponse_Builder*) builder;
+ (Message_LoginMessageResponse_Builder*) builderWithPrototype:(Message_LoginMessageResponse*) prototype;

+ (Message_LoginMessageResponse*) parseFromData:(NSData*) data;
+ (Message_LoginMessageResponse*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Message_LoginMessageResponse*) parseFromInputStream:(NSInputStream*) input;
+ (Message_LoginMessageResponse*) parseDelimitedFromInputStream:(NSInputStream*) input;
+ (Message_LoginMessageResponse*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Message_LoginMessageResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (Message_LoginMessageResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface Message_LoginMessageResponse_Builder : PBGeneratedMessage_Builder {
@private
  Message_LoginMessageResponse* result;
}

- (Message_LoginMessageResponse*) defaultInstance;

- (Message_LoginMessageResponse_Builder*) clear;
- (Message_LoginMessageResponse_Builder*) clone;

- (Message_LoginMessageResponse*) build;
- (Message_LoginMessageResponse*) buildPartial;

- (Message_LoginMessageResponse_Builder*) mergeFrom:(Message_LoginMessageResponse*) other;
- (Message_LoginMessageResponse_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (Message_LoginMessageResponse_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasStatus;
- (int32_t) status;
- (Message_LoginMessageResponse_Builder*) setStatus:(int32_t) value;
- (Message_LoginMessageResponse_Builder*) clearStatus;

- (BOOL) hasUserId;
- (NSString*) userId;
- (Message_LoginMessageResponse_Builder*) setUserId:(NSString*) value;
- (Message_LoginMessageResponse_Builder*) clearUserId;

- (BOOL) hasUserName;
- (NSString*) userName;
- (Message_LoginMessageResponse_Builder*) setUserName:(NSString*) value;
- (Message_LoginMessageResponse_Builder*) clearUserName;

- (BOOL) hasPassword;
- (NSString*) password;
- (Message_LoginMessageResponse_Builder*) setPassword:(NSString*) value;
- (Message_LoginMessageResponse_Builder*) clearPassword;

- (BOOL) hasNickName;
- (NSString*) nickName;
- (Message_LoginMessageResponse_Builder*) setNickName:(NSString*) value;
- (Message_LoginMessageResponse_Builder*) clearNickName;

- (BOOL) hasSex;
- (int32_t) sex;
- (Message_LoginMessageResponse_Builder*) setSex:(int32_t) value;
- (Message_LoginMessageResponse_Builder*) clearSex;

- (BOOL) hasBirthday;
- (NSString*) birthday;
- (Message_LoginMessageResponse_Builder*) setBirthday:(NSString*) value;
- (Message_LoginMessageResponse_Builder*) clearBirthday;

- (BOOL) hasAvatarUrl;
- (NSString*) avatarUrl;
- (Message_LoginMessageResponse_Builder*) setAvatarUrl:(NSString*) value;
- (Message_LoginMessageResponse_Builder*) clearAvatarUrl;

- (BOOL) hasAvatarId;
- (int32_t) avatarId;
- (Message_LoginMessageResponse_Builder*) setAvatarId:(int32_t) value;
- (Message_LoginMessageResponse_Builder*) clearAvatarId;

- (BOOL) hasAppId;
- (NSString*) appId;
- (Message_LoginMessageResponse_Builder*) setAppId:(NSString*) value;
- (Message_LoginMessageResponse_Builder*) clearAppId;
@end

@interface Message_LogoutMessageRequest : PBGeneratedMessage {
@private
  BOOL hasPhoneNumber_:1;
  BOOL hasEmail_:1;
  NSString* phoneNumber;
  NSString* email;
}
- (BOOL) hasPhoneNumber;
- (BOOL) hasEmail;
@property (readonly, retain) NSString* phoneNumber;
@property (readonly, retain) NSString* email;

+ (Message_LogoutMessageRequest*) defaultInstance;
- (Message_LogoutMessageRequest*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (Message_LogoutMessageRequest_Builder*) builder;
+ (Message_LogoutMessageRequest_Builder*) builder;
+ (Message_LogoutMessageRequest_Builder*) builderWithPrototype:(Message_LogoutMessageRequest*) prototype;

+ (Message_LogoutMessageRequest*) parseFromData:(NSData*) data;
+ (Message_LogoutMessageRequest*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Message_LogoutMessageRequest*) parseFromInputStream:(NSInputStream*) input;
+ (Message_LogoutMessageRequest*) parseDelimitedFromInputStream:(NSInputStream*) input;
+ (Message_LogoutMessageRequest*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Message_LogoutMessageRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (Message_LogoutMessageRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface Message_LogoutMessageRequest_Builder : PBGeneratedMessage_Builder {
@private
  Message_LogoutMessageRequest* result;
}

- (Message_LogoutMessageRequest*) defaultInstance;

- (Message_LogoutMessageRequest_Builder*) clear;
- (Message_LogoutMessageRequest_Builder*) clone;

- (Message_LogoutMessageRequest*) build;
- (Message_LogoutMessageRequest*) buildPartial;

- (Message_LogoutMessageRequest_Builder*) mergeFrom:(Message_LogoutMessageRequest*) other;
- (Message_LogoutMessageRequest_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (Message_LogoutMessageRequest_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasPhoneNumber;
- (NSString*) phoneNumber;
- (Message_LogoutMessageRequest_Builder*) setPhoneNumber:(NSString*) value;
- (Message_LogoutMessageRequest_Builder*) clearPhoneNumber;

- (BOOL) hasEmail;
- (NSString*) email;
- (Message_LogoutMessageRequest_Builder*) setEmail:(NSString*) value;
- (Message_LogoutMessageRequest_Builder*) clearEmail;
@end

@interface Message_LogoutMessageResponse : PBGeneratedMessage {
@private
  BOOL hasStatus_:1;
  int32_t status;
}
- (BOOL) hasStatus;
@property (readonly) int32_t status;

+ (Message_LogoutMessageResponse*) defaultInstance;
- (Message_LogoutMessageResponse*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (Message_LogoutMessageResponse_Builder*) builder;
+ (Message_LogoutMessageResponse_Builder*) builder;
+ (Message_LogoutMessageResponse_Builder*) builderWithPrototype:(Message_LogoutMessageResponse*) prototype;

+ (Message_LogoutMessageResponse*) parseFromData:(NSData*) data;
+ (Message_LogoutMessageResponse*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Message_LogoutMessageResponse*) parseFromInputStream:(NSInputStream*) input;
+ (Message_LogoutMessageResponse*) parseDelimitedFromInputStream:(NSInputStream*) input;
+ (Message_LogoutMessageResponse*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Message_LogoutMessageResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (Message_LogoutMessageResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface Message_LogoutMessageResponse_Builder : PBGeneratedMessage_Builder {
@private
  Message_LogoutMessageResponse* result;
}

- (Message_LogoutMessageResponse*) defaultInstance;

- (Message_LogoutMessageResponse_Builder*) clear;
- (Message_LogoutMessageResponse_Builder*) clone;

- (Message_LogoutMessageResponse*) build;
- (Message_LogoutMessageResponse*) buildPartial;

- (Message_LogoutMessageResponse_Builder*) mergeFrom:(Message_LogoutMessageResponse*) other;
- (Message_LogoutMessageResponse_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (Message_LogoutMessageResponse_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasStatus;
- (int32_t) status;
- (Message_LogoutMessageResponse_Builder*) setStatus:(int32_t) value;
- (Message_LogoutMessageResponse_Builder*) clearStatus;
@end

@interface Message_ForgetPasswordMessageRequest : PBGeneratedMessage {
@private
  BOOL hasPhoneNumber_:1;
  BOOL hasEmail_:1;
  NSString* phoneNumber;
  NSString* email;
}
- (BOOL) hasPhoneNumber;
- (BOOL) hasEmail;
@property (readonly, retain) NSString* phoneNumber;
@property (readonly, retain) NSString* email;

+ (Message_ForgetPasswordMessageRequest*) defaultInstance;
- (Message_ForgetPasswordMessageRequest*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (Message_ForgetPasswordMessageRequest_Builder*) builder;
+ (Message_ForgetPasswordMessageRequest_Builder*) builder;
+ (Message_ForgetPasswordMessageRequest_Builder*) builderWithPrototype:(Message_ForgetPasswordMessageRequest*) prototype;

+ (Message_ForgetPasswordMessageRequest*) parseFromData:(NSData*) data;
+ (Message_ForgetPasswordMessageRequest*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Message_ForgetPasswordMessageRequest*) parseFromInputStream:(NSInputStream*) input;
+ (Message_ForgetPasswordMessageRequest*) parseDelimitedFromInputStream:(NSInputStream*) input;
+ (Message_ForgetPasswordMessageRequest*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Message_ForgetPasswordMessageRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (Message_ForgetPasswordMessageRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface Message_ForgetPasswordMessageRequest_Builder : PBGeneratedMessage_Builder {
@private
  Message_ForgetPasswordMessageRequest* result;
}

- (Message_ForgetPasswordMessageRequest*) defaultInstance;

- (Message_ForgetPasswordMessageRequest_Builder*) clear;
- (Message_ForgetPasswordMessageRequest_Builder*) clone;

- (Message_ForgetPasswordMessageRequest*) build;
- (Message_ForgetPasswordMessageRequest*) buildPartial;

- (Message_ForgetPasswordMessageRequest_Builder*) mergeFrom:(Message_ForgetPasswordMessageRequest*) other;
- (Message_ForgetPasswordMessageRequest_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (Message_ForgetPasswordMessageRequest_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasPhoneNumber;
- (NSString*) phoneNumber;
- (Message_ForgetPasswordMessageRequest_Builder*) setPhoneNumber:(NSString*) value;
- (Message_ForgetPasswordMessageRequest_Builder*) clearPhoneNumber;

- (BOOL) hasEmail;
- (NSString*) email;
- (Message_ForgetPasswordMessageRequest_Builder*) setEmail:(NSString*) value;
- (Message_ForgetPasswordMessageRequest_Builder*) clearEmail;
@end

@interface Message_ForgetPasswordMessageResponse : PBGeneratedMessage {
@private
  BOOL hasStatus_:1;
  int32_t status;
}
- (BOOL) hasStatus;
@property (readonly) int32_t status;

+ (Message_ForgetPasswordMessageResponse*) defaultInstance;
- (Message_ForgetPasswordMessageResponse*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (Message_ForgetPasswordMessageResponse_Builder*) builder;
+ (Message_ForgetPasswordMessageResponse_Builder*) builder;
+ (Message_ForgetPasswordMessageResponse_Builder*) builderWithPrototype:(Message_ForgetPasswordMessageResponse*) prototype;

+ (Message_ForgetPasswordMessageResponse*) parseFromData:(NSData*) data;
+ (Message_ForgetPasswordMessageResponse*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Message_ForgetPasswordMessageResponse*) parseFromInputStream:(NSInputStream*) input;
+ (Message_ForgetPasswordMessageResponse*) parseDelimitedFromInputStream:(NSInputStream*) input;
+ (Message_ForgetPasswordMessageResponse*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Message_ForgetPasswordMessageResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (Message_ForgetPasswordMessageResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface Message_ForgetPasswordMessageResponse_Builder : PBGeneratedMessage_Builder {
@private
  Message_ForgetPasswordMessageResponse* result;
}

- (Message_ForgetPasswordMessageResponse*) defaultInstance;

- (Message_ForgetPasswordMessageResponse_Builder*) clear;
- (Message_ForgetPasswordMessageResponse_Builder*) clone;

- (Message_ForgetPasswordMessageResponse*) build;
- (Message_ForgetPasswordMessageResponse*) buildPartial;

- (Message_ForgetPasswordMessageResponse_Builder*) mergeFrom:(Message_ForgetPasswordMessageResponse*) other;
- (Message_ForgetPasswordMessageResponse_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (Message_ForgetPasswordMessageResponse_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasStatus;
- (int32_t) status;
- (Message_ForgetPasswordMessageResponse_Builder*) setStatus:(int32_t) value;
- (Message_ForgetPasswordMessageResponse_Builder*) clearStatus;
@end

@interface Message_WhoAmIRequest : PBGeneratedMessage {
@private
  BOOL hasDate_:1;
  BOOL hasUserId_:1;
  BOOL hasLocation_:1;
  BOOL hasMessageHash_:1;
  int64_t date;
  NSString* userId;
  NSString* location;
  NSString* messageHash;
}
- (BOOL) hasUserId;
- (BOOL) hasLocation;
- (BOOL) hasMessageHash;
- (BOOL) hasDate;
@property (readonly, retain) NSString* userId;
@property (readonly, retain) NSString* location;
@property (readonly, retain) NSString* messageHash;
@property (readonly) int64_t date;

+ (Message_WhoAmIRequest*) defaultInstance;
- (Message_WhoAmIRequest*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (Message_WhoAmIRequest_Builder*) builder;
+ (Message_WhoAmIRequest_Builder*) builder;
+ (Message_WhoAmIRequest_Builder*) builderWithPrototype:(Message_WhoAmIRequest*) prototype;

+ (Message_WhoAmIRequest*) parseFromData:(NSData*) data;
+ (Message_WhoAmIRequest*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Message_WhoAmIRequest*) parseFromInputStream:(NSInputStream*) input;
+ (Message_WhoAmIRequest*) parseDelimitedFromInputStream:(NSInputStream*) input;
+ (Message_WhoAmIRequest*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Message_WhoAmIRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (Message_WhoAmIRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface Message_WhoAmIRequest_Builder : PBGeneratedMessage_Builder {
@private
  Message_WhoAmIRequest* result;
}

- (Message_WhoAmIRequest*) defaultInstance;

- (Message_WhoAmIRequest_Builder*) clear;
- (Message_WhoAmIRequest_Builder*) clone;

- (Message_WhoAmIRequest*) build;
- (Message_WhoAmIRequest*) buildPartial;

- (Message_WhoAmIRequest_Builder*) mergeFrom:(Message_WhoAmIRequest*) other;
- (Message_WhoAmIRequest_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (Message_WhoAmIRequest_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUserId;
- (NSString*) userId;
- (Message_WhoAmIRequest_Builder*) setUserId:(NSString*) value;
- (Message_WhoAmIRequest_Builder*) clearUserId;

- (BOOL) hasLocation;
- (NSString*) location;
- (Message_WhoAmIRequest_Builder*) setLocation:(NSString*) value;
- (Message_WhoAmIRequest_Builder*) clearLocation;

- (BOOL) hasMessageHash;
- (NSString*) messageHash;
- (Message_WhoAmIRequest_Builder*) setMessageHash:(NSString*) value;
- (Message_WhoAmIRequest_Builder*) clearMessageHash;

- (BOOL) hasDate;
- (int64_t) date;
- (Message_WhoAmIRequest_Builder*) setDate:(int64_t) value;
- (Message_WhoAmIRequest_Builder*) clearDate;
@end

@interface Message_WhoAmIResponse : PBGeneratedMessage {
@private
  BOOL hasDate_:1;
  BOOL hasStatus_:1;
  BOOL hasDesc_:1;
  BOOL hasMessageHash_:1;
  int64_t date;
  int32_t status;
  NSString* desc;
  NSString* messageHash;
}
- (BOOL) hasStatus;
- (BOOL) hasDesc;
- (BOOL) hasMessageHash;
- (BOOL) hasDate;
@property (readonly) int32_t status;
@property (readonly, retain) NSString* desc;
@property (readonly, retain) NSString* messageHash;
@property (readonly) int64_t date;

+ (Message_WhoAmIResponse*) defaultInstance;
- (Message_WhoAmIResponse*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (Message_WhoAmIResponse_Builder*) builder;
+ (Message_WhoAmIResponse_Builder*) builder;
+ (Message_WhoAmIResponse_Builder*) builderWithPrototype:(Message_WhoAmIResponse*) prototype;

+ (Message_WhoAmIResponse*) parseFromData:(NSData*) data;
+ (Message_WhoAmIResponse*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Message_WhoAmIResponse*) parseFromInputStream:(NSInputStream*) input;
+ (Message_WhoAmIResponse*) parseDelimitedFromInputStream:(NSInputStream*) input;
+ (Message_WhoAmIResponse*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Message_WhoAmIResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (Message_WhoAmIResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface Message_WhoAmIResponse_Builder : PBGeneratedMessage_Builder {
@private
  Message_WhoAmIResponse* result;
}

- (Message_WhoAmIResponse*) defaultInstance;

- (Message_WhoAmIResponse_Builder*) clear;
- (Message_WhoAmIResponse_Builder*) clone;

- (Message_WhoAmIResponse*) build;
- (Message_WhoAmIResponse*) buildPartial;

- (Message_WhoAmIResponse_Builder*) mergeFrom:(Message_WhoAmIResponse*) other;
- (Message_WhoAmIResponse_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (Message_WhoAmIResponse_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasStatus;
- (int32_t) status;
- (Message_WhoAmIResponse_Builder*) setStatus:(int32_t) value;
- (Message_WhoAmIResponse_Builder*) clearStatus;

- (BOOL) hasDesc;
- (NSString*) desc;
- (Message_WhoAmIResponse_Builder*) setDesc:(NSString*) value;
- (Message_WhoAmIResponse_Builder*) clearDesc;

- (BOOL) hasMessageHash;
- (NSString*) messageHash;
- (Message_WhoAmIResponse_Builder*) setMessageHash:(NSString*) value;
- (Message_WhoAmIResponse_Builder*) clearMessageHash;

- (BOOL) hasDate;
- (int64_t) date;
- (Message_WhoAmIResponse_Builder*) setDate:(int64_t) value;
- (Message_WhoAmIResponse_Builder*) clearDate;
@end

@interface Message_TextChatMessageRequest : PBGeneratedMessage {
@private
  BOOL hasDate_:1;
  BOOL hasUserId_:1;
  BOOL hasText_:1;
  BOOL hasToUserId_:1;
  BOOL hasMessageHash_:1;
  int64_t date;
  NSString* userId;
  NSString* text;
  NSString* toUserId;
  NSString* messageHash;
}
- (BOOL) hasUserId;
- (BOOL) hasText;
- (BOOL) hasToUserId;
- (BOOL) hasMessageHash;
- (BOOL) hasDate;
@property (readonly, retain) NSString* userId;
@property (readonly, retain) NSString* text;
@property (readonly, retain) NSString* toUserId;
@property (readonly, retain) NSString* messageHash;
@property (readonly) int64_t date;

+ (Message_TextChatMessageRequest*) defaultInstance;
- (Message_TextChatMessageRequest*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (Message_TextChatMessageRequest_Builder*) builder;
+ (Message_TextChatMessageRequest_Builder*) builder;
+ (Message_TextChatMessageRequest_Builder*) builderWithPrototype:(Message_TextChatMessageRequest*) prototype;

+ (Message_TextChatMessageRequest*) parseFromData:(NSData*) data;
+ (Message_TextChatMessageRequest*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Message_TextChatMessageRequest*) parseFromInputStream:(NSInputStream*) input;
+ (Message_TextChatMessageRequest*) parseDelimitedFromInputStream:(NSInputStream*) input;
+ (Message_TextChatMessageRequest*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Message_TextChatMessageRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (Message_TextChatMessageRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface Message_TextChatMessageRequest_Builder : PBGeneratedMessage_Builder {
@private
  Message_TextChatMessageRequest* result;
}

- (Message_TextChatMessageRequest*) defaultInstance;

- (Message_TextChatMessageRequest_Builder*) clear;
- (Message_TextChatMessageRequest_Builder*) clone;

- (Message_TextChatMessageRequest*) build;
- (Message_TextChatMessageRequest*) buildPartial;

- (Message_TextChatMessageRequest_Builder*) mergeFrom:(Message_TextChatMessageRequest*) other;
- (Message_TextChatMessageRequest_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (Message_TextChatMessageRequest_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUserId;
- (NSString*) userId;
- (Message_TextChatMessageRequest_Builder*) setUserId:(NSString*) value;
- (Message_TextChatMessageRequest_Builder*) clearUserId;

- (BOOL) hasText;
- (NSString*) text;
- (Message_TextChatMessageRequest_Builder*) setText:(NSString*) value;
- (Message_TextChatMessageRequest_Builder*) clearText;

- (BOOL) hasToUserId;
- (NSString*) toUserId;
- (Message_TextChatMessageRequest_Builder*) setToUserId:(NSString*) value;
- (Message_TextChatMessageRequest_Builder*) clearToUserId;

- (BOOL) hasMessageHash;
- (NSString*) messageHash;
- (Message_TextChatMessageRequest_Builder*) setMessageHash:(NSString*) value;
- (Message_TextChatMessageRequest_Builder*) clearMessageHash;

- (BOOL) hasDate;
- (int64_t) date;
- (Message_TextChatMessageRequest_Builder*) setDate:(int64_t) value;
- (Message_TextChatMessageRequest_Builder*) clearDate;
@end

@interface Message_TextChatMessageResponse : PBGeneratedMessage {
@private
  BOOL hasDate_:1;
  BOOL hasStatus_:1;
  BOOL hasUserId_:1;
  BOOL hasDesc_:1;
  BOOL hasToUserId_:1;
  BOOL hasMessageHash_:1;
  int64_t date;
  int32_t status;
  NSString* userId;
  NSString* desc;
  NSString* toUserId;
  NSString* messageHash;
}
- (BOOL) hasUserId;
- (BOOL) hasStatus;
- (BOOL) hasDesc;
- (BOOL) hasToUserId;
- (BOOL) hasMessageHash;
- (BOOL) hasDate;
@property (readonly, retain) NSString* userId;
@property (readonly) int32_t status;
@property (readonly, retain) NSString* desc;
@property (readonly, retain) NSString* toUserId;
@property (readonly, retain) NSString* messageHash;
@property (readonly) int64_t date;

+ (Message_TextChatMessageResponse*) defaultInstance;
- (Message_TextChatMessageResponse*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (Message_TextChatMessageResponse_Builder*) builder;
+ (Message_TextChatMessageResponse_Builder*) builder;
+ (Message_TextChatMessageResponse_Builder*) builderWithPrototype:(Message_TextChatMessageResponse*) prototype;

+ (Message_TextChatMessageResponse*) parseFromData:(NSData*) data;
+ (Message_TextChatMessageResponse*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Message_TextChatMessageResponse*) parseFromInputStream:(NSInputStream*) input;
+ (Message_TextChatMessageResponse*) parseDelimitedFromInputStream:(NSInputStream*) input;
+ (Message_TextChatMessageResponse*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Message_TextChatMessageResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (Message_TextChatMessageResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface Message_TextChatMessageResponse_Builder : PBGeneratedMessage_Builder {
@private
  Message_TextChatMessageResponse* result;
}

- (Message_TextChatMessageResponse*) defaultInstance;

- (Message_TextChatMessageResponse_Builder*) clear;
- (Message_TextChatMessageResponse_Builder*) clone;

- (Message_TextChatMessageResponse*) build;
- (Message_TextChatMessageResponse*) buildPartial;

- (Message_TextChatMessageResponse_Builder*) mergeFrom:(Message_TextChatMessageResponse*) other;
- (Message_TextChatMessageResponse_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (Message_TextChatMessageResponse_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUserId;
- (NSString*) userId;
- (Message_TextChatMessageResponse_Builder*) setUserId:(NSString*) value;
- (Message_TextChatMessageResponse_Builder*) clearUserId;

- (BOOL) hasStatus;
- (int32_t) status;
- (Message_TextChatMessageResponse_Builder*) setStatus:(int32_t) value;
- (Message_TextChatMessageResponse_Builder*) clearStatus;

- (BOOL) hasDesc;
- (NSString*) desc;
- (Message_TextChatMessageResponse_Builder*) setDesc:(NSString*) value;
- (Message_TextChatMessageResponse_Builder*) clearDesc;

- (BOOL) hasToUserId;
- (NSString*) toUserId;
- (Message_TextChatMessageResponse_Builder*) setToUserId:(NSString*) value;
- (Message_TextChatMessageResponse_Builder*) clearToUserId;

- (BOOL) hasMessageHash;
- (NSString*) messageHash;
- (Message_TextChatMessageResponse_Builder*) setMessageHash:(NSString*) value;
- (Message_TextChatMessageResponse_Builder*) clearMessageHash;

- (BOOL) hasDate;
- (int64_t) date;
- (Message_TextChatMessageResponse_Builder*) setDate:(int64_t) value;
- (Message_TextChatMessageResponse_Builder*) clearDate;
@end

@interface Message_PictureChatMessageRequest : PBGeneratedMessage {
@private
  BOOL hasDate_:1;
  BOOL hasUserId_:1;
  BOOL hasPictureUuid_:1;
  BOOL hasDesc_:1;
  BOOL hasToUserId_:1;
  BOOL hasMessageHash_:1;
  int64_t date;
  NSString* userId;
  NSString* pictureUuid;
  NSString* desc;
  NSString* toUserId;
  NSString* messageHash;
}
- (BOOL) hasUserId;
- (BOOL) hasPictureUuid;
- (BOOL) hasDesc;
- (BOOL) hasToUserId;
- (BOOL) hasMessageHash;
- (BOOL) hasDate;
@property (readonly, retain) NSString* userId;
@property (readonly, retain) NSString* pictureUuid;
@property (readonly, retain) NSString* desc;
@property (readonly, retain) NSString* toUserId;
@property (readonly, retain) NSString* messageHash;
@property (readonly) int64_t date;

+ (Message_PictureChatMessageRequest*) defaultInstance;
- (Message_PictureChatMessageRequest*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (Message_PictureChatMessageRequest_Builder*) builder;
+ (Message_PictureChatMessageRequest_Builder*) builder;
+ (Message_PictureChatMessageRequest_Builder*) builderWithPrototype:(Message_PictureChatMessageRequest*) prototype;

+ (Message_PictureChatMessageRequest*) parseFromData:(NSData*) data;
+ (Message_PictureChatMessageRequest*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Message_PictureChatMessageRequest*) parseFromInputStream:(NSInputStream*) input;
+ (Message_PictureChatMessageRequest*) parseDelimitedFromInputStream:(NSInputStream*) input;
+ (Message_PictureChatMessageRequest*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Message_PictureChatMessageRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (Message_PictureChatMessageRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface Message_PictureChatMessageRequest_Builder : PBGeneratedMessage_Builder {
@private
  Message_PictureChatMessageRequest* result;
}

- (Message_PictureChatMessageRequest*) defaultInstance;

- (Message_PictureChatMessageRequest_Builder*) clear;
- (Message_PictureChatMessageRequest_Builder*) clone;

- (Message_PictureChatMessageRequest*) build;
- (Message_PictureChatMessageRequest*) buildPartial;

- (Message_PictureChatMessageRequest_Builder*) mergeFrom:(Message_PictureChatMessageRequest*) other;
- (Message_PictureChatMessageRequest_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (Message_PictureChatMessageRequest_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUserId;
- (NSString*) userId;
- (Message_PictureChatMessageRequest_Builder*) setUserId:(NSString*) value;
- (Message_PictureChatMessageRequest_Builder*) clearUserId;

- (BOOL) hasPictureUuid;
- (NSString*) pictureUuid;
- (Message_PictureChatMessageRequest_Builder*) setPictureUuid:(NSString*) value;
- (Message_PictureChatMessageRequest_Builder*) clearPictureUuid;

- (BOOL) hasDesc;
- (NSString*) desc;
- (Message_PictureChatMessageRequest_Builder*) setDesc:(NSString*) value;
- (Message_PictureChatMessageRequest_Builder*) clearDesc;

- (BOOL) hasToUserId;
- (NSString*) toUserId;
- (Message_PictureChatMessageRequest_Builder*) setToUserId:(NSString*) value;
- (Message_PictureChatMessageRequest_Builder*) clearToUserId;

- (BOOL) hasMessageHash;
- (NSString*) messageHash;
- (Message_PictureChatMessageRequest_Builder*) setMessageHash:(NSString*) value;
- (Message_PictureChatMessageRequest_Builder*) clearMessageHash;

- (BOOL) hasDate;
- (int64_t) date;
- (Message_PictureChatMessageRequest_Builder*) setDate:(int64_t) value;
- (Message_PictureChatMessageRequest_Builder*) clearDate;
@end

@interface Message_PictureChatMessageResponse : PBGeneratedMessage {
@private
  BOOL hasDate_:1;
  BOOL hasStatus_:1;
  BOOL hasUserId_:1;
  BOOL hasDesc_:1;
  BOOL hasToUserId_:1;
  BOOL hasMessageHash_:1;
  int64_t date;
  int32_t status;
  NSString* userId;
  NSString* desc;
  NSString* toUserId;
  NSString* messageHash;
}
- (BOOL) hasUserId;
- (BOOL) hasStatus;
- (BOOL) hasDesc;
- (BOOL) hasToUserId;
- (BOOL) hasMessageHash;
- (BOOL) hasDate;
@property (readonly, retain) NSString* userId;
@property (readonly) int32_t status;
@property (readonly, retain) NSString* desc;
@property (readonly, retain) NSString* toUserId;
@property (readonly, retain) NSString* messageHash;
@property (readonly) int64_t date;

+ (Message_PictureChatMessageResponse*) defaultInstance;
- (Message_PictureChatMessageResponse*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (Message_PictureChatMessageResponse_Builder*) builder;
+ (Message_PictureChatMessageResponse_Builder*) builder;
+ (Message_PictureChatMessageResponse_Builder*) builderWithPrototype:(Message_PictureChatMessageResponse*) prototype;

+ (Message_PictureChatMessageResponse*) parseFromData:(NSData*) data;
+ (Message_PictureChatMessageResponse*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Message_PictureChatMessageResponse*) parseFromInputStream:(NSInputStream*) input;
+ (Message_PictureChatMessageResponse*) parseDelimitedFromInputStream:(NSInputStream*) input;
+ (Message_PictureChatMessageResponse*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Message_PictureChatMessageResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (Message_PictureChatMessageResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface Message_PictureChatMessageResponse_Builder : PBGeneratedMessage_Builder {
@private
  Message_PictureChatMessageResponse* result;
}

- (Message_PictureChatMessageResponse*) defaultInstance;

- (Message_PictureChatMessageResponse_Builder*) clear;
- (Message_PictureChatMessageResponse_Builder*) clone;

- (Message_PictureChatMessageResponse*) build;
- (Message_PictureChatMessageResponse*) buildPartial;

- (Message_PictureChatMessageResponse_Builder*) mergeFrom:(Message_PictureChatMessageResponse*) other;
- (Message_PictureChatMessageResponse_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (Message_PictureChatMessageResponse_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUserId;
- (NSString*) userId;
- (Message_PictureChatMessageResponse_Builder*) setUserId:(NSString*) value;
- (Message_PictureChatMessageResponse_Builder*) clearUserId;

- (BOOL) hasStatus;
- (int32_t) status;
- (Message_PictureChatMessageResponse_Builder*) setStatus:(int32_t) value;
- (Message_PictureChatMessageResponse_Builder*) clearStatus;

- (BOOL) hasDesc;
- (NSString*) desc;
- (Message_PictureChatMessageResponse_Builder*) setDesc:(NSString*) value;
- (Message_PictureChatMessageResponse_Builder*) clearDesc;

- (BOOL) hasToUserId;
- (NSString*) toUserId;
- (Message_PictureChatMessageResponse_Builder*) setToUserId:(NSString*) value;
- (Message_PictureChatMessageResponse_Builder*) clearToUserId;

- (BOOL) hasMessageHash;
- (NSString*) messageHash;
- (Message_PictureChatMessageResponse_Builder*) setMessageHash:(NSString*) value;
- (Message_PictureChatMessageResponse_Builder*) clearMessageHash;

- (BOOL) hasDate;
- (int64_t) date;
- (Message_PictureChatMessageResponse_Builder*) setDate:(int64_t) value;
- (Message_PictureChatMessageResponse_Builder*) clearDate;
@end

@interface Message_VoiceChatMessageRequest : PBGeneratedMessage {
@private
  BOOL hasDate_:1;
  BOOL hasUserId_:1;
  BOOL hasVoiceUuid_:1;
  BOOL hasDesc_:1;
  BOOL hasToUserId_:1;
  BOOL hasMessageHash_:1;
  int64_t date;
  NSString* userId;
  NSString* voiceUuid;
  NSString* desc;
  NSString* toUserId;
  NSString* messageHash;
}
- (BOOL) hasUserId;
- (BOOL) hasVoiceUuid;
- (BOOL) hasDesc;
- (BOOL) hasToUserId;
- (BOOL) hasMessageHash;
- (BOOL) hasDate;
@property (readonly, retain) NSString* userId;
@property (readonly, retain) NSString* voiceUuid;
@property (readonly, retain) NSString* desc;
@property (readonly, retain) NSString* toUserId;
@property (readonly, retain) NSString* messageHash;
@property (readonly) int64_t date;

+ (Message_VoiceChatMessageRequest*) defaultInstance;
- (Message_VoiceChatMessageRequest*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (Message_VoiceChatMessageRequest_Builder*) builder;
+ (Message_VoiceChatMessageRequest_Builder*) builder;
+ (Message_VoiceChatMessageRequest_Builder*) builderWithPrototype:(Message_VoiceChatMessageRequest*) prototype;

+ (Message_VoiceChatMessageRequest*) parseFromData:(NSData*) data;
+ (Message_VoiceChatMessageRequest*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Message_VoiceChatMessageRequest*) parseFromInputStream:(NSInputStream*) input;
+ (Message_VoiceChatMessageRequest*) parseDelimitedFromInputStream:(NSInputStream*) input;
+ (Message_VoiceChatMessageRequest*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Message_VoiceChatMessageRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (Message_VoiceChatMessageRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface Message_VoiceChatMessageRequest_Builder : PBGeneratedMessage_Builder {
@private
  Message_VoiceChatMessageRequest* result;
}

- (Message_VoiceChatMessageRequest*) defaultInstance;

- (Message_VoiceChatMessageRequest_Builder*) clear;
- (Message_VoiceChatMessageRequest_Builder*) clone;

- (Message_VoiceChatMessageRequest*) build;
- (Message_VoiceChatMessageRequest*) buildPartial;

- (Message_VoiceChatMessageRequest_Builder*) mergeFrom:(Message_VoiceChatMessageRequest*) other;
- (Message_VoiceChatMessageRequest_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (Message_VoiceChatMessageRequest_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUserId;
- (NSString*) userId;
- (Message_VoiceChatMessageRequest_Builder*) setUserId:(NSString*) value;
- (Message_VoiceChatMessageRequest_Builder*) clearUserId;

- (BOOL) hasVoiceUuid;
- (NSString*) voiceUuid;
- (Message_VoiceChatMessageRequest_Builder*) setVoiceUuid:(NSString*) value;
- (Message_VoiceChatMessageRequest_Builder*) clearVoiceUuid;

- (BOOL) hasDesc;
- (NSString*) desc;
- (Message_VoiceChatMessageRequest_Builder*) setDesc:(NSString*) value;
- (Message_VoiceChatMessageRequest_Builder*) clearDesc;

- (BOOL) hasToUserId;
- (NSString*) toUserId;
- (Message_VoiceChatMessageRequest_Builder*) setToUserId:(NSString*) value;
- (Message_VoiceChatMessageRequest_Builder*) clearToUserId;

- (BOOL) hasMessageHash;
- (NSString*) messageHash;
- (Message_VoiceChatMessageRequest_Builder*) setMessageHash:(NSString*) value;
- (Message_VoiceChatMessageRequest_Builder*) clearMessageHash;

- (BOOL) hasDate;
- (int64_t) date;
- (Message_VoiceChatMessageRequest_Builder*) setDate:(int64_t) value;
- (Message_VoiceChatMessageRequest_Builder*) clearDate;
@end

@interface Message_VoiceChatMessageResponse : PBGeneratedMessage {
@private
  BOOL hasDate_:1;
  BOOL hasStatus_:1;
  BOOL hasUserId_:1;
  BOOL hasDesc_:1;
  BOOL hasToUserId_:1;
  BOOL hasMessageHash_:1;
  int64_t date;
  int32_t status;
  NSString* userId;
  NSString* desc;
  NSString* toUserId;
  NSString* messageHash;
}
- (BOOL) hasUserId;
- (BOOL) hasStatus;
- (BOOL) hasDesc;
- (BOOL) hasToUserId;
- (BOOL) hasMessageHash;
- (BOOL) hasDate;
@property (readonly, retain) NSString* userId;
@property (readonly) int32_t status;
@property (readonly, retain) NSString* desc;
@property (readonly, retain) NSString* toUserId;
@property (readonly, retain) NSString* messageHash;
@property (readonly) int64_t date;

+ (Message_VoiceChatMessageResponse*) defaultInstance;
- (Message_VoiceChatMessageResponse*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (Message_VoiceChatMessageResponse_Builder*) builder;
+ (Message_VoiceChatMessageResponse_Builder*) builder;
+ (Message_VoiceChatMessageResponse_Builder*) builderWithPrototype:(Message_VoiceChatMessageResponse*) prototype;

+ (Message_VoiceChatMessageResponse*) parseFromData:(NSData*) data;
+ (Message_VoiceChatMessageResponse*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Message_VoiceChatMessageResponse*) parseFromInputStream:(NSInputStream*) input;
+ (Message_VoiceChatMessageResponse*) parseDelimitedFromInputStream:(NSInputStream*) input;
+ (Message_VoiceChatMessageResponse*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Message_VoiceChatMessageResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (Message_VoiceChatMessageResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface Message_VoiceChatMessageResponse_Builder : PBGeneratedMessage_Builder {
@private
  Message_VoiceChatMessageResponse* result;
}

- (Message_VoiceChatMessageResponse*) defaultInstance;

- (Message_VoiceChatMessageResponse_Builder*) clear;
- (Message_VoiceChatMessageResponse_Builder*) clone;

- (Message_VoiceChatMessageResponse*) build;
- (Message_VoiceChatMessageResponse*) buildPartial;

- (Message_VoiceChatMessageResponse_Builder*) mergeFrom:(Message_VoiceChatMessageResponse*) other;
- (Message_VoiceChatMessageResponse_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (Message_VoiceChatMessageResponse_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUserId;
- (NSString*) userId;
- (Message_VoiceChatMessageResponse_Builder*) setUserId:(NSString*) value;
- (Message_VoiceChatMessageResponse_Builder*) clearUserId;

- (BOOL) hasStatus;
- (int32_t) status;
- (Message_VoiceChatMessageResponse_Builder*) setStatus:(int32_t) value;
- (Message_VoiceChatMessageResponse_Builder*) clearStatus;

- (BOOL) hasDesc;
- (NSString*) desc;
- (Message_VoiceChatMessageResponse_Builder*) setDesc:(NSString*) value;
- (Message_VoiceChatMessageResponse_Builder*) clearDesc;

- (BOOL) hasToUserId;
- (NSString*) toUserId;
- (Message_VoiceChatMessageResponse_Builder*) setToUserId:(NSString*) value;
- (Message_VoiceChatMessageResponse_Builder*) clearToUserId;

- (BOOL) hasMessageHash;
- (NSString*) messageHash;
- (Message_VoiceChatMessageResponse_Builder*) setMessageHash:(NSString*) value;
- (Message_VoiceChatMessageResponse_Builder*) clearMessageHash;

- (BOOL) hasDate;
- (int64_t) date;
- (Message_VoiceChatMessageResponse_Builder*) setDate:(int64_t) value;
- (Message_VoiceChatMessageResponse_Builder*) clearDate;
@end

@interface Message_VideoChatMessageRequest : PBGeneratedMessage {
@private
  BOOL hasDate_:1;
  BOOL hasUserId_:1;
  BOOL hasVideoUuid_:1;
  BOOL hasDesc_:1;
  BOOL hasToUserId_:1;
  BOOL hasMessageHash_:1;
  int64_t date;
  NSString* userId;
  NSString* videoUuid;
  NSString* desc;
  NSString* toUserId;
  NSString* messageHash;
}
- (BOOL) hasUserId;
- (BOOL) hasVideoUuid;
- (BOOL) hasDesc;
- (BOOL) hasToUserId;
- (BOOL) hasMessageHash;
- (BOOL) hasDate;
@property (readonly, retain) NSString* userId;
@property (readonly, retain) NSString* videoUuid;
@property (readonly, retain) NSString* desc;
@property (readonly, retain) NSString* toUserId;
@property (readonly, retain) NSString* messageHash;
@property (readonly) int64_t date;

+ (Message_VideoChatMessageRequest*) defaultInstance;
- (Message_VideoChatMessageRequest*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (Message_VideoChatMessageRequest_Builder*) builder;
+ (Message_VideoChatMessageRequest_Builder*) builder;
+ (Message_VideoChatMessageRequest_Builder*) builderWithPrototype:(Message_VideoChatMessageRequest*) prototype;

+ (Message_VideoChatMessageRequest*) parseFromData:(NSData*) data;
+ (Message_VideoChatMessageRequest*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Message_VideoChatMessageRequest*) parseFromInputStream:(NSInputStream*) input;
+ (Message_VideoChatMessageRequest*) parseDelimitedFromInputStream:(NSInputStream*) input;
+ (Message_VideoChatMessageRequest*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Message_VideoChatMessageRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (Message_VideoChatMessageRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface Message_VideoChatMessageRequest_Builder : PBGeneratedMessage_Builder {
@private
  Message_VideoChatMessageRequest* result;
}

- (Message_VideoChatMessageRequest*) defaultInstance;

- (Message_VideoChatMessageRequest_Builder*) clear;
- (Message_VideoChatMessageRequest_Builder*) clone;

- (Message_VideoChatMessageRequest*) build;
- (Message_VideoChatMessageRequest*) buildPartial;

- (Message_VideoChatMessageRequest_Builder*) mergeFrom:(Message_VideoChatMessageRequest*) other;
- (Message_VideoChatMessageRequest_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (Message_VideoChatMessageRequest_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUserId;
- (NSString*) userId;
- (Message_VideoChatMessageRequest_Builder*) setUserId:(NSString*) value;
- (Message_VideoChatMessageRequest_Builder*) clearUserId;

- (BOOL) hasVideoUuid;
- (NSString*) videoUuid;
- (Message_VideoChatMessageRequest_Builder*) setVideoUuid:(NSString*) value;
- (Message_VideoChatMessageRequest_Builder*) clearVideoUuid;

- (BOOL) hasDesc;
- (NSString*) desc;
- (Message_VideoChatMessageRequest_Builder*) setDesc:(NSString*) value;
- (Message_VideoChatMessageRequest_Builder*) clearDesc;

- (BOOL) hasToUserId;
- (NSString*) toUserId;
- (Message_VideoChatMessageRequest_Builder*) setToUserId:(NSString*) value;
- (Message_VideoChatMessageRequest_Builder*) clearToUserId;

- (BOOL) hasMessageHash;
- (NSString*) messageHash;
- (Message_VideoChatMessageRequest_Builder*) setMessageHash:(NSString*) value;
- (Message_VideoChatMessageRequest_Builder*) clearMessageHash;

- (BOOL) hasDate;
- (int64_t) date;
- (Message_VideoChatMessageRequest_Builder*) setDate:(int64_t) value;
- (Message_VideoChatMessageRequest_Builder*) clearDate;
@end

@interface Message_VideoChatMessageResponse : PBGeneratedMessage {
@private
  BOOL hasDate_:1;
  BOOL hasStatus_:1;
  BOOL hasUserId_:1;
  BOOL hasDesc_:1;
  BOOL hasToUserId_:1;
  BOOL hasMessageHash_:1;
  int64_t date;
  int32_t status;
  NSString* userId;
  NSString* desc;
  NSString* toUserId;
  NSString* messageHash;
}
- (BOOL) hasUserId;
- (BOOL) hasStatus;
- (BOOL) hasDesc;
- (BOOL) hasToUserId;
- (BOOL) hasMessageHash;
- (BOOL) hasDate;
@property (readonly, retain) NSString* userId;
@property (readonly) int32_t status;
@property (readonly, retain) NSString* desc;
@property (readonly, retain) NSString* toUserId;
@property (readonly, retain) NSString* messageHash;
@property (readonly) int64_t date;

+ (Message_VideoChatMessageResponse*) defaultInstance;
- (Message_VideoChatMessageResponse*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (Message_VideoChatMessageResponse_Builder*) builder;
+ (Message_VideoChatMessageResponse_Builder*) builder;
+ (Message_VideoChatMessageResponse_Builder*) builderWithPrototype:(Message_VideoChatMessageResponse*) prototype;

+ (Message_VideoChatMessageResponse*) parseFromData:(NSData*) data;
+ (Message_VideoChatMessageResponse*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Message_VideoChatMessageResponse*) parseFromInputStream:(NSInputStream*) input;
+ (Message_VideoChatMessageResponse*) parseDelimitedFromInputStream:(NSInputStream*) input;
+ (Message_VideoChatMessageResponse*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Message_VideoChatMessageResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (Message_VideoChatMessageResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface Message_VideoChatMessageResponse_Builder : PBGeneratedMessage_Builder {
@private
  Message_VideoChatMessageResponse* result;
}

- (Message_VideoChatMessageResponse*) defaultInstance;

- (Message_VideoChatMessageResponse_Builder*) clear;
- (Message_VideoChatMessageResponse_Builder*) clone;

- (Message_VideoChatMessageResponse*) build;
- (Message_VideoChatMessageResponse*) buildPartial;

- (Message_VideoChatMessageResponse_Builder*) mergeFrom:(Message_VideoChatMessageResponse*) other;
- (Message_VideoChatMessageResponse_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (Message_VideoChatMessageResponse_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUserId;
- (NSString*) userId;
- (Message_VideoChatMessageResponse_Builder*) setUserId:(NSString*) value;
- (Message_VideoChatMessageResponse_Builder*) clearUserId;

- (BOOL) hasStatus;
- (int32_t) status;
- (Message_VideoChatMessageResponse_Builder*) setStatus:(int32_t) value;
- (Message_VideoChatMessageResponse_Builder*) clearStatus;

- (BOOL) hasDesc;
- (NSString*) desc;
- (Message_VideoChatMessageResponse_Builder*) setDesc:(NSString*) value;
- (Message_VideoChatMessageResponse_Builder*) clearDesc;

- (BOOL) hasToUserId;
- (NSString*) toUserId;
- (Message_VideoChatMessageResponse_Builder*) setToUserId:(NSString*) value;
- (Message_VideoChatMessageResponse_Builder*) clearToUserId;

- (BOOL) hasMessageHash;
- (NSString*) messageHash;
- (Message_VideoChatMessageResponse_Builder*) setMessageHash:(NSString*) value;
- (Message_VideoChatMessageResponse_Builder*) clearMessageHash;

- (BOOL) hasDate;
- (int64_t) date;
- (Message_VideoChatMessageResponse_Builder*) setDate:(int64_t) value;
- (Message_VideoChatMessageResponse_Builder*) clearDate;
@end

@interface Message_TextFromServerRequest : PBGeneratedMessage {
@private
  BOOL hasDate_:1;
  BOOL hasMessageHash_:1;
  BOOL hasFromUserId_:1;
  BOOL hasToUserId_:1;
  BOOL hasText_:1;
  int64_t date;
  NSString* messageHash;
  NSString* fromUserId;
  NSString* toUserId;
  NSString* text;
}
- (BOOL) hasMessageHash;
- (BOOL) hasFromUserId;
- (BOOL) hasToUserId;
- (BOOL) hasText;
- (BOOL) hasDate;
@property (readonly, retain) NSString* messageHash;
@property (readonly, retain) NSString* fromUserId;
@property (readonly, retain) NSString* toUserId;
@property (readonly, retain) NSString* text;
@property (readonly) int64_t date;

+ (Message_TextFromServerRequest*) defaultInstance;
- (Message_TextFromServerRequest*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (Message_TextFromServerRequest_Builder*) builder;
+ (Message_TextFromServerRequest_Builder*) builder;
+ (Message_TextFromServerRequest_Builder*) builderWithPrototype:(Message_TextFromServerRequest*) prototype;

+ (Message_TextFromServerRequest*) parseFromData:(NSData*) data;
+ (Message_TextFromServerRequest*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Message_TextFromServerRequest*) parseFromInputStream:(NSInputStream*) input;
+ (Message_TextFromServerRequest*) parseDelimitedFromInputStream:(NSInputStream*) input;
+ (Message_TextFromServerRequest*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Message_TextFromServerRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (Message_TextFromServerRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface Message_TextFromServerRequest_Builder : PBGeneratedMessage_Builder {
@private
  Message_TextFromServerRequest* result;
}

- (Message_TextFromServerRequest*) defaultInstance;

- (Message_TextFromServerRequest_Builder*) clear;
- (Message_TextFromServerRequest_Builder*) clone;

- (Message_TextFromServerRequest*) build;
- (Message_TextFromServerRequest*) buildPartial;

- (Message_TextFromServerRequest_Builder*) mergeFrom:(Message_TextFromServerRequest*) other;
- (Message_TextFromServerRequest_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (Message_TextFromServerRequest_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasMessageHash;
- (NSString*) messageHash;
- (Message_TextFromServerRequest_Builder*) setMessageHash:(NSString*) value;
- (Message_TextFromServerRequest_Builder*) clearMessageHash;

- (BOOL) hasFromUserId;
- (NSString*) fromUserId;
- (Message_TextFromServerRequest_Builder*) setFromUserId:(NSString*) value;
- (Message_TextFromServerRequest_Builder*) clearFromUserId;

- (BOOL) hasToUserId;
- (NSString*) toUserId;
- (Message_TextFromServerRequest_Builder*) setToUserId:(NSString*) value;
- (Message_TextFromServerRequest_Builder*) clearToUserId;

- (BOOL) hasText;
- (NSString*) text;
- (Message_TextFromServerRequest_Builder*) setText:(NSString*) value;
- (Message_TextFromServerRequest_Builder*) clearText;

- (BOOL) hasDate;
- (int64_t) date;
- (Message_TextFromServerRequest_Builder*) setDate:(int64_t) value;
- (Message_TextFromServerRequest_Builder*) clearDate;
@end

@interface Message_TextFromServerResponse : PBGeneratedMessage {
@private
  BOOL hasDate_:1;
  BOOL hasStatus_:1;
  BOOL hasMessageHash_:1;
  BOOL hasDesc_:1;
  int64_t date;
  int32_t status;
  NSString* messageHash;
  NSString* desc;
}
- (BOOL) hasStatus;
- (BOOL) hasMessageHash;
- (BOOL) hasDesc;
- (BOOL) hasDate;
@property (readonly) int32_t status;
@property (readonly, retain) NSString* messageHash;
@property (readonly, retain) NSString* desc;
@property (readonly) int64_t date;

+ (Message_TextFromServerResponse*) defaultInstance;
- (Message_TextFromServerResponse*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (Message_TextFromServerResponse_Builder*) builder;
+ (Message_TextFromServerResponse_Builder*) builder;
+ (Message_TextFromServerResponse_Builder*) builderWithPrototype:(Message_TextFromServerResponse*) prototype;

+ (Message_TextFromServerResponse*) parseFromData:(NSData*) data;
+ (Message_TextFromServerResponse*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Message_TextFromServerResponse*) parseFromInputStream:(NSInputStream*) input;
+ (Message_TextFromServerResponse*) parseDelimitedFromInputStream:(NSInputStream*) input;
+ (Message_TextFromServerResponse*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Message_TextFromServerResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (Message_TextFromServerResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface Message_TextFromServerResponse_Builder : PBGeneratedMessage_Builder {
@private
  Message_TextFromServerResponse* result;
}

- (Message_TextFromServerResponse*) defaultInstance;

- (Message_TextFromServerResponse_Builder*) clear;
- (Message_TextFromServerResponse_Builder*) clone;

- (Message_TextFromServerResponse*) build;
- (Message_TextFromServerResponse*) buildPartial;

- (Message_TextFromServerResponse_Builder*) mergeFrom:(Message_TextFromServerResponse*) other;
- (Message_TextFromServerResponse_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (Message_TextFromServerResponse_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasStatus;
- (int32_t) status;
- (Message_TextFromServerResponse_Builder*) setStatus:(int32_t) value;
- (Message_TextFromServerResponse_Builder*) clearStatus;

- (BOOL) hasMessageHash;
- (NSString*) messageHash;
- (Message_TextFromServerResponse_Builder*) setMessageHash:(NSString*) value;
- (Message_TextFromServerResponse_Builder*) clearMessageHash;

- (BOOL) hasDesc;
- (NSString*) desc;
- (Message_TextFromServerResponse_Builder*) setDesc:(NSString*) value;
- (Message_TextFromServerResponse_Builder*) clearDesc;

- (BOOL) hasDate;
- (int64_t) date;
- (Message_TextFromServerResponse_Builder*) setDate:(int64_t) value;
- (Message_TextFromServerResponse_Builder*) clearDate;
@end

@interface Message_PictureFromServerRequest : PBGeneratedMessage {
@private
  BOOL hasDate_:1;
  BOOL hasMessageHash_:1;
  BOOL hasFromUserId_:1;
  BOOL hasToUserId_:1;
  BOOL hasPictureUuid_:1;
  int64_t date;
  NSString* messageHash;
  NSString* fromUserId;
  NSString* toUserId;
  NSString* pictureUuid;
}
- (BOOL) hasMessageHash;
- (BOOL) hasFromUserId;
- (BOOL) hasToUserId;
- (BOOL) hasPictureUuid;
- (BOOL) hasDate;
@property (readonly, retain) NSString* messageHash;
@property (readonly, retain) NSString* fromUserId;
@property (readonly, retain) NSString* toUserId;
@property (readonly, retain) NSString* pictureUuid;
@property (readonly) int64_t date;

+ (Message_PictureFromServerRequest*) defaultInstance;
- (Message_PictureFromServerRequest*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (Message_PictureFromServerRequest_Builder*) builder;
+ (Message_PictureFromServerRequest_Builder*) builder;
+ (Message_PictureFromServerRequest_Builder*) builderWithPrototype:(Message_PictureFromServerRequest*) prototype;

+ (Message_PictureFromServerRequest*) parseFromData:(NSData*) data;
+ (Message_PictureFromServerRequest*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Message_PictureFromServerRequest*) parseFromInputStream:(NSInputStream*) input;
+ (Message_PictureFromServerRequest*) parseDelimitedFromInputStream:(NSInputStream*) input;
+ (Message_PictureFromServerRequest*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Message_PictureFromServerRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (Message_PictureFromServerRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface Message_PictureFromServerRequest_Builder : PBGeneratedMessage_Builder {
@private
  Message_PictureFromServerRequest* result;
}

- (Message_PictureFromServerRequest*) defaultInstance;

- (Message_PictureFromServerRequest_Builder*) clear;
- (Message_PictureFromServerRequest_Builder*) clone;

- (Message_PictureFromServerRequest*) build;
- (Message_PictureFromServerRequest*) buildPartial;

- (Message_PictureFromServerRequest_Builder*) mergeFrom:(Message_PictureFromServerRequest*) other;
- (Message_PictureFromServerRequest_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (Message_PictureFromServerRequest_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasMessageHash;
- (NSString*) messageHash;
- (Message_PictureFromServerRequest_Builder*) setMessageHash:(NSString*) value;
- (Message_PictureFromServerRequest_Builder*) clearMessageHash;

- (BOOL) hasFromUserId;
- (NSString*) fromUserId;
- (Message_PictureFromServerRequest_Builder*) setFromUserId:(NSString*) value;
- (Message_PictureFromServerRequest_Builder*) clearFromUserId;

- (BOOL) hasToUserId;
- (NSString*) toUserId;
- (Message_PictureFromServerRequest_Builder*) setToUserId:(NSString*) value;
- (Message_PictureFromServerRequest_Builder*) clearToUserId;

- (BOOL) hasPictureUuid;
- (NSString*) pictureUuid;
- (Message_PictureFromServerRequest_Builder*) setPictureUuid:(NSString*) value;
- (Message_PictureFromServerRequest_Builder*) clearPictureUuid;

- (BOOL) hasDate;
- (int64_t) date;
- (Message_PictureFromServerRequest_Builder*) setDate:(int64_t) value;
- (Message_PictureFromServerRequest_Builder*) clearDate;
@end

@interface Message_PictureFromServerResponse : PBGeneratedMessage {
@private
  BOOL hasDate_:1;
  BOOL hasStatus_:1;
  BOOL hasMessageHash_:1;
  BOOL hasDesc_:1;
  int64_t date;
  int32_t status;
  NSString* messageHash;
  NSString* desc;
}
- (BOOL) hasStatus;
- (BOOL) hasMessageHash;
- (BOOL) hasDesc;
- (BOOL) hasDate;
@property (readonly) int32_t status;
@property (readonly, retain) NSString* messageHash;
@property (readonly, retain) NSString* desc;
@property (readonly) int64_t date;

+ (Message_PictureFromServerResponse*) defaultInstance;
- (Message_PictureFromServerResponse*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (Message_PictureFromServerResponse_Builder*) builder;
+ (Message_PictureFromServerResponse_Builder*) builder;
+ (Message_PictureFromServerResponse_Builder*) builderWithPrototype:(Message_PictureFromServerResponse*) prototype;

+ (Message_PictureFromServerResponse*) parseFromData:(NSData*) data;
+ (Message_PictureFromServerResponse*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Message_PictureFromServerResponse*) parseFromInputStream:(NSInputStream*) input;
+ (Message_PictureFromServerResponse*) parseDelimitedFromInputStream:(NSInputStream*) input;
+ (Message_PictureFromServerResponse*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Message_PictureFromServerResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (Message_PictureFromServerResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface Message_PictureFromServerResponse_Builder : PBGeneratedMessage_Builder {
@private
  Message_PictureFromServerResponse* result;
}

- (Message_PictureFromServerResponse*) defaultInstance;

- (Message_PictureFromServerResponse_Builder*) clear;
- (Message_PictureFromServerResponse_Builder*) clone;

- (Message_PictureFromServerResponse*) build;
- (Message_PictureFromServerResponse*) buildPartial;

- (Message_PictureFromServerResponse_Builder*) mergeFrom:(Message_PictureFromServerResponse*) other;
- (Message_PictureFromServerResponse_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (Message_PictureFromServerResponse_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasStatus;
- (int32_t) status;
- (Message_PictureFromServerResponse_Builder*) setStatus:(int32_t) value;
- (Message_PictureFromServerResponse_Builder*) clearStatus;

- (BOOL) hasMessageHash;
- (NSString*) messageHash;
- (Message_PictureFromServerResponse_Builder*) setMessageHash:(NSString*) value;
- (Message_PictureFromServerResponse_Builder*) clearMessageHash;

- (BOOL) hasDesc;
- (NSString*) desc;
- (Message_PictureFromServerResponse_Builder*) setDesc:(NSString*) value;
- (Message_PictureFromServerResponse_Builder*) clearDesc;

- (BOOL) hasDate;
- (int64_t) date;
- (Message_PictureFromServerResponse_Builder*) setDate:(int64_t) value;
- (Message_PictureFromServerResponse_Builder*) clearDate;
@end

@interface Message_Builder : PBGeneratedMessage_Builder {
@private
  Message* result;
}

- (Message*) defaultInstance;

- (Message_Builder*) clear;
- (Message_Builder*) clone;

- (Message*) build;
- (Message*) buildPartial;

- (Message_Builder*) mergeFrom:(Message*) other;
- (Message_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (Message_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasType;
- (Message_MessageType) type;
- (Message_Builder*) setType:(Message_MessageType) value;
- (Message_Builder*) clearType;

- (BOOL) hasSubRequest;
- (Message_SubMessageRequest*) subRequest;
- (Message_Builder*) setSubRequest:(Message_SubMessageRequest*) value;
- (Message_Builder*) setSubRequestBuilder:(Message_SubMessageRequest_Builder*) builderForValue;
- (Message_Builder*) mergeSubRequest:(Message_SubMessageRequest*) value;
- (Message_Builder*) clearSubRequest;

- (BOOL) hasSubResponse;
- (Message_SubMessageResponse*) subResponse;
- (Message_Builder*) setSubResponse:(Message_SubMessageResponse*) value;
- (Message_Builder*) setSubResponseBuilder:(Message_SubMessageResponse_Builder*) builderForValue;
- (Message_Builder*) mergeSubResponse:(Message_SubMessageResponse*) value;
- (Message_Builder*) clearSubResponse;

- (BOOL) hasLoginRequest;
- (Message_LoginMessageRequest*) loginRequest;
- (Message_Builder*) setLoginRequest:(Message_LoginMessageRequest*) value;
- (Message_Builder*) setLoginRequestBuilder:(Message_LoginMessageRequest_Builder*) builderForValue;
- (Message_Builder*) mergeLoginRequest:(Message_LoginMessageRequest*) value;
- (Message_Builder*) clearLoginRequest;

- (BOOL) hasLoginResponse;
- (Message_LoginMessageResponse*) loginResponse;
- (Message_Builder*) setLoginResponse:(Message_LoginMessageResponse*) value;
- (Message_Builder*) setLoginResponseBuilder:(Message_LoginMessageResponse_Builder*) builderForValue;
- (Message_Builder*) mergeLoginResponse:(Message_LoginMessageResponse*) value;
- (Message_Builder*) clearLoginResponse;

- (BOOL) hasLogoutRequest;
- (Message_LogoutMessageRequest*) logoutRequest;
- (Message_Builder*) setLogoutRequest:(Message_LogoutMessageRequest*) value;
- (Message_Builder*) setLogoutRequestBuilder:(Message_LogoutMessageRequest_Builder*) builderForValue;
- (Message_Builder*) mergeLogoutRequest:(Message_LogoutMessageRequest*) value;
- (Message_Builder*) clearLogoutRequest;

- (BOOL) hasLogoutResponse;
- (Message_LogoutMessageResponse*) logoutResponse;
- (Message_Builder*) setLogoutResponse:(Message_LogoutMessageResponse*) value;
- (Message_Builder*) setLogoutResponseBuilder:(Message_LogoutMessageResponse_Builder*) builderForValue;
- (Message_Builder*) mergeLogoutResponse:(Message_LogoutMessageResponse*) value;
- (Message_Builder*) clearLogoutResponse;

- (BOOL) hasForgetPwdRequest;
- (Message_ForgetPasswordMessageRequest*) forgetPwdRequest;
- (Message_Builder*) setForgetPwdRequest:(Message_ForgetPasswordMessageRequest*) value;
- (Message_Builder*) setForgetPwdRequestBuilder:(Message_ForgetPasswordMessageRequest_Builder*) builderForValue;
- (Message_Builder*) mergeForgetPwdRequest:(Message_ForgetPasswordMessageRequest*) value;
- (Message_Builder*) clearForgetPwdRequest;

- (BOOL) hasForgetPwdResponse;
- (Message_ForgetPasswordMessageResponse*) forgetPwdResponse;
- (Message_Builder*) setForgetPwdResponse:(Message_ForgetPasswordMessageResponse*) value;
- (Message_Builder*) setForgetPwdResponseBuilder:(Message_ForgetPasswordMessageResponse_Builder*) builderForValue;
- (Message_Builder*) mergeForgetPwdResponse:(Message_ForgetPasswordMessageResponse*) value;
- (Message_Builder*) clearForgetPwdResponse;

- (BOOL) hasWhoAmIrequest;
- (Message_WhoAmIRequest*) whoAmIrequest;
- (Message_Builder*) setWhoAmIrequest:(Message_WhoAmIRequest*) value;
- (Message_Builder*) setWhoAmIrequestBuilder:(Message_WhoAmIRequest_Builder*) builderForValue;
- (Message_Builder*) mergeWhoAmIrequest:(Message_WhoAmIRequest*) value;
- (Message_Builder*) clearWhoAmIrequest;

- (BOOL) hasWhoAmIresponse;
- (Message_WhoAmIResponse*) whoAmIresponse;
- (Message_Builder*) setWhoAmIresponse:(Message_WhoAmIResponse*) value;
- (Message_Builder*) setWhoAmIresponseBuilder:(Message_WhoAmIResponse_Builder*) builderForValue;
- (Message_Builder*) mergeWhoAmIresponse:(Message_WhoAmIResponse*) value;
- (Message_Builder*) clearWhoAmIresponse;

- (BOOL) hasTextChatMessageRequest;
- (Message_TextChatMessageRequest*) textChatMessageRequest;
- (Message_Builder*) setTextChatMessageRequest:(Message_TextChatMessageRequest*) value;
- (Message_Builder*) setTextChatMessageRequestBuilder:(Message_TextChatMessageRequest_Builder*) builderForValue;
- (Message_Builder*) mergeTextChatMessageRequest:(Message_TextChatMessageRequest*) value;
- (Message_Builder*) clearTextChatMessageRequest;

- (BOOL) hasTextChatMessageResponse;
- (Message_TextChatMessageResponse*) textChatMessageResponse;
- (Message_Builder*) setTextChatMessageResponse:(Message_TextChatMessageResponse*) value;
- (Message_Builder*) setTextChatMessageResponseBuilder:(Message_TextChatMessageResponse_Builder*) builderForValue;
- (Message_Builder*) mergeTextChatMessageResponse:(Message_TextChatMessageResponse*) value;
- (Message_Builder*) clearTextChatMessageResponse;

- (BOOL) hasPictureChatMessageRequest;
- (Message_PictureChatMessageRequest*) pictureChatMessageRequest;
- (Message_Builder*) setPictureChatMessageRequest:(Message_PictureChatMessageRequest*) value;
- (Message_Builder*) setPictureChatMessageRequestBuilder:(Message_PictureChatMessageRequest_Builder*) builderForValue;
- (Message_Builder*) mergePictureChatMessageRequest:(Message_PictureChatMessageRequest*) value;
- (Message_Builder*) clearPictureChatMessageRequest;

- (BOOL) hasPictureChatMessageResponse;
- (Message_PictureChatMessageResponse*) pictureChatMessageResponse;
- (Message_Builder*) setPictureChatMessageResponse:(Message_PictureChatMessageResponse*) value;
- (Message_Builder*) setPictureChatMessageResponseBuilder:(Message_PictureChatMessageResponse_Builder*) builderForValue;
- (Message_Builder*) mergePictureChatMessageResponse:(Message_PictureChatMessageResponse*) value;
- (Message_Builder*) clearPictureChatMessageResponse;

- (BOOL) hasVoiceChatMessageRequest;
- (Message_VoiceChatMessageRequest*) voiceChatMessageRequest;
- (Message_Builder*) setVoiceChatMessageRequest:(Message_VoiceChatMessageRequest*) value;
- (Message_Builder*) setVoiceChatMessageRequestBuilder:(Message_VoiceChatMessageRequest_Builder*) builderForValue;
- (Message_Builder*) mergeVoiceChatMessageRequest:(Message_VoiceChatMessageRequest*) value;
- (Message_Builder*) clearVoiceChatMessageRequest;

- (BOOL) hasVoiceChatMessageResponse;
- (Message_VoiceChatMessageResponse*) voiceChatMessageResponse;
- (Message_Builder*) setVoiceChatMessageResponse:(Message_VoiceChatMessageResponse*) value;
- (Message_Builder*) setVoiceChatMessageResponseBuilder:(Message_VoiceChatMessageResponse_Builder*) builderForValue;
- (Message_Builder*) mergeVoiceChatMessageResponse:(Message_VoiceChatMessageResponse*) value;
- (Message_Builder*) clearVoiceChatMessageResponse;

- (BOOL) hasVideoChatMessageRequest;
- (Message_VideoChatMessageRequest*) videoChatMessageRequest;
- (Message_Builder*) setVideoChatMessageRequest:(Message_VideoChatMessageRequest*) value;
- (Message_Builder*) setVideoChatMessageRequestBuilder:(Message_VideoChatMessageRequest_Builder*) builderForValue;
- (Message_Builder*) mergeVideoChatMessageRequest:(Message_VideoChatMessageRequest*) value;
- (Message_Builder*) clearVideoChatMessageRequest;

- (BOOL) hasVideoChatMessageResponse;
- (Message_VideoChatMessageResponse*) videoChatMessageResponse;
- (Message_Builder*) setVideoChatMessageResponse:(Message_VideoChatMessageResponse*) value;
- (Message_Builder*) setVideoChatMessageResponseBuilder:(Message_VideoChatMessageResponse_Builder*) builderForValue;
- (Message_Builder*) mergeVideoChatMessageResponse:(Message_VideoChatMessageResponse*) value;
- (Message_Builder*) clearVideoChatMessageResponse;

- (BOOL) hasTextFromServerRequest;
- (Message_TextFromServerRequest*) textFromServerRequest;
- (Message_Builder*) setTextFromServerRequest:(Message_TextFromServerRequest*) value;
- (Message_Builder*) setTextFromServerRequestBuilder:(Message_TextFromServerRequest_Builder*) builderForValue;
- (Message_Builder*) mergeTextFromServerRequest:(Message_TextFromServerRequest*) value;
- (Message_Builder*) clearTextFromServerRequest;

- (BOOL) hasTextFromServerResponse;
- (Message_TextFromServerResponse*) textFromServerResponse;
- (Message_Builder*) setTextFromServerResponse:(Message_TextFromServerResponse*) value;
- (Message_Builder*) setTextFromServerResponseBuilder:(Message_TextFromServerResponse_Builder*) builderForValue;
- (Message_Builder*) mergeTextFromServerResponse:(Message_TextFromServerResponse*) value;
- (Message_Builder*) clearTextFromServerResponse;

- (BOOL) hasPictureFromServerRequest;
- (Message_PictureFromServerRequest*) pictureFromServerRequest;
- (Message_Builder*) setPictureFromServerRequest:(Message_PictureFromServerRequest*) value;
- (Message_Builder*) setPictureFromServerRequestBuilder:(Message_PictureFromServerRequest_Builder*) builderForValue;
- (Message_Builder*) mergePictureFromServerRequest:(Message_PictureFromServerRequest*) value;
- (Message_Builder*) clearPictureFromServerRequest;

- (BOOL) hasPictureFromServerResponse;
- (Message_PictureFromServerResponse*) pictureFromServerResponse;
- (Message_Builder*) setPictureFromServerResponse:(Message_PictureFromServerResponse*) value;
- (Message_Builder*) setPictureFromServerResponseBuilder:(Message_PictureFromServerResponse_Builder*) builderForValue;
- (Message_Builder*) mergePictureFromServerResponse:(Message_PictureFromServerResponse*) value;
- (Message_Builder*) clearPictureFromServerResponse;
@end

