// Generated by the protocol buffer compiler.  DO NOT EDIT!
#import "UIKit/UIKit.h"
#import "ProtocolBuffers.h"

@class Message;
@class Message_Builder;
@class Message_ForgetPasswordMessageRequest;
@class Message_ForgetPasswordMessageRequest_Builder;
@class Message_ForgetPasswordMessageResponse;
@class Message_ForgetPasswordMessageResponse_Builder;
@class Message_LoginMessageRequest;
@class Message_LoginMessageRequest_Builder;
@class Message_LoginMessageResponse;
@class Message_LoginMessageResponse_Builder;
@class Message_LogoutMessageRequest;
@class Message_LogoutMessageRequest_Builder;
@class Message_LogoutMessageResponse;
@class Message_LogoutMessageResponse_Builder;
@class Message_SubMessageRequest;
@class Message_SubMessageRequest_Builder;
@class Message_SubMessageResponse;
@class Message_SubMessageResponse_Builder;
typedef enum {
  Message_MessageTypeSubscribeReq = 0,
  Message_MessageTypeSubscribeResp = 1,
  Message_MessageTypeLoginReq = 2,
  Message_MessageTypeLoginResp = 3,
  Message_MessageTypeLogoutReq = 4,
  Message_MessageTypeLogoutResp = 5,
  Message_MessageTypeForgetPwdReq = 6,
  Message_MessageTypeForgetPwdResp = 7,
} Message_MessageType;

BOOL Message_MessageTypeIsValidValue(Message_MessageType value);


@interface AppRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface Message : PBGeneratedMessage {
@private
  BOOL hasSubRequest_:1;
  BOOL hasSubResponse_:1;
  BOOL hasLoginRequest_:1;
  BOOL hasLoginResponse_:1;
  BOOL hasLogoutRequest_:1;
  BOOL hasLogoutResponse_:1;
  BOOL hasForgetPwdRequest_:1;
  BOOL hasForgetPwdResponse_:1;
  BOOL hasType_:1;
  Message_SubMessageRequest* subRequest;
  Message_SubMessageResponse* subResponse;
  Message_LoginMessageRequest* loginRequest;
  Message_LoginMessageResponse* loginResponse;
  Message_LogoutMessageRequest* logoutRequest;
  Message_LogoutMessageResponse* logoutResponse;
  Message_ForgetPasswordMessageRequest* forgetPwdRequest;
  Message_ForgetPasswordMessageResponse* forgetPwdResponse;
  Message_MessageType type;
}
- (BOOL) hasType;
- (BOOL) hasSubRequest;
- (BOOL) hasSubResponse;
- (BOOL) hasLoginRequest;
- (BOOL) hasLoginResponse;
- (BOOL) hasLogoutRequest;
- (BOOL) hasLogoutResponse;
- (BOOL) hasForgetPwdRequest;
- (BOOL) hasForgetPwdResponse;
@property (readonly) Message_MessageType type;
@property (readonly, retain) Message_SubMessageRequest* subRequest;
@property (readonly, retain) Message_SubMessageResponse* subResponse;
@property (readonly, retain) Message_LoginMessageRequest* loginRequest;
@property (readonly, retain) Message_LoginMessageResponse* loginResponse;
@property (readonly, retain) Message_LogoutMessageRequest* logoutRequest;
@property (readonly, retain) Message_LogoutMessageResponse* logoutResponse;
@property (readonly, retain) Message_ForgetPasswordMessageRequest* forgetPwdRequest;
@property (readonly, retain) Message_ForgetPasswordMessageResponse* forgetPwdResponse;

+ (Message*) defaultInstance;
- (Message*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (Message_Builder*) builder;
+ (Message_Builder*) builder;
+ (Message_Builder*) builderWithPrototype:(Message*) prototype;

+ (Message*) parseFromData:(NSData*) data;
+ (Message*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Message*) parseFromInputStream:(NSInputStream*) input;
+ (Message*) parseDelimitedFromInputStream:(NSInputStream*) input;
+ (Message*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Message*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (Message*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface Message_SubMessageRequest : PBGeneratedMessage {
@private
  BOOL hasSex_:1;
  BOOL hasPhoneNumber_:1;
  BOOL hasEmail_:1;
  BOOL hasPassword_:1;
  int32_t sex;
  NSString* phoneNumber;
  NSString* email;
  NSString* password;
}
- (BOOL) hasPhoneNumber;
- (BOOL) hasEmail;
- (BOOL) hasPassword;
- (BOOL) hasSex;
@property (readonly, retain) NSString* phoneNumber;
@property (readonly, retain) NSString* email;
@property (readonly, retain) NSString* password;
@property (readonly) int32_t sex;

+ (Message_SubMessageRequest*) defaultInstance;
- (Message_SubMessageRequest*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (Message_SubMessageRequest_Builder*) builder;
+ (Message_SubMessageRequest_Builder*) builder;
+ (Message_SubMessageRequest_Builder*) builderWithPrototype:(Message_SubMessageRequest*) prototype;

+ (Message_SubMessageRequest*) parseFromData:(NSData*) data;
+ (Message_SubMessageRequest*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Message_SubMessageRequest*) parseFromInputStream:(NSInputStream*) input;
+ (Message_SubMessageRequest*) parseDelimitedFromInputStream:(NSInputStream*) input;
+ (Message_SubMessageRequest*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Message_SubMessageRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (Message_SubMessageRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface Message_SubMessageRequest_Builder : PBGeneratedMessage_Builder {
@private
  Message_SubMessageRequest* result;
}

- (Message_SubMessageRequest*) defaultInstance;

- (Message_SubMessageRequest_Builder*) clear;
- (Message_SubMessageRequest_Builder*) clone;

- (Message_SubMessageRequest*) build;
- (Message_SubMessageRequest*) buildPartial;

- (Message_SubMessageRequest_Builder*) mergeFrom:(Message_SubMessageRequest*) other;
- (Message_SubMessageRequest_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (Message_SubMessageRequest_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasPhoneNumber;
- (NSString*) phoneNumber;
- (Message_SubMessageRequest_Builder*) setPhoneNumber:(NSString*) value;
- (Message_SubMessageRequest_Builder*) clearPhoneNumber;

- (BOOL) hasEmail;
- (NSString*) email;
- (Message_SubMessageRequest_Builder*) setEmail:(NSString*) value;
- (Message_SubMessageRequest_Builder*) clearEmail;

- (BOOL) hasPassword;
- (NSString*) password;
- (Message_SubMessageRequest_Builder*) setPassword:(NSString*) value;
- (Message_SubMessageRequest_Builder*) clearPassword;

- (BOOL) hasSex;
- (int32_t) sex;
- (Message_SubMessageRequest_Builder*) setSex:(int32_t) value;
- (Message_SubMessageRequest_Builder*) clearSex;
@end

@interface Message_SubMessageResponse : PBGeneratedMessage {
@private
  BOOL hasStatus_:1;
  BOOL hasSex_:1;
  BOOL hasAvatarId_:1;
  BOOL hasUserId_:1;
  BOOL hasUserName_:1;
  BOOL hasPassword_:1;
  BOOL hasNickName_:1;
  BOOL hasBirthday_:1;
  BOOL hasAvatarUrl_:1;
  BOOL hasAppId_:1;
  int32_t status;
  int32_t sex;
  int32_t avatarId;
  NSString* userId;
  NSString* userName;
  NSString* password;
  NSString* nickName;
  NSString* birthday;
  NSString* avatarUrl;
  NSString* appId;
}
- (BOOL) hasStatus;
- (BOOL) hasUserId;
- (BOOL) hasUserName;
- (BOOL) hasPassword;
- (BOOL) hasNickName;
- (BOOL) hasSex;
- (BOOL) hasBirthday;
- (BOOL) hasAvatarUrl;
- (BOOL) hasAvatarId;
- (BOOL) hasAppId;
@property (readonly) int32_t status;
@property (readonly, retain) NSString* userId;
@property (readonly, retain) NSString* userName;
@property (readonly, retain) NSString* password;
@property (readonly, retain) NSString* nickName;
@property (readonly) int32_t sex;
@property (readonly, retain) NSString* birthday;
@property (readonly, retain) NSString* avatarUrl;
@property (readonly) int32_t avatarId;
@property (readonly, retain) NSString* appId;

+ (Message_SubMessageResponse*) defaultInstance;
- (Message_SubMessageResponse*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (Message_SubMessageResponse_Builder*) builder;
+ (Message_SubMessageResponse_Builder*) builder;
+ (Message_SubMessageResponse_Builder*) builderWithPrototype:(Message_SubMessageResponse*) prototype;

+ (Message_SubMessageResponse*) parseFromData:(NSData*) data;
+ (Message_SubMessageResponse*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Message_SubMessageResponse*) parseFromInputStream:(NSInputStream*) input;
+ (Message_SubMessageResponse*) parseDelimitedFromInputStream:(NSInputStream*) input;
+ (Message_SubMessageResponse*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Message_SubMessageResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (Message_SubMessageResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface Message_SubMessageResponse_Builder : PBGeneratedMessage_Builder {
@private
  Message_SubMessageResponse* result;
}

- (Message_SubMessageResponse*) defaultInstance;

- (Message_SubMessageResponse_Builder*) clear;
- (Message_SubMessageResponse_Builder*) clone;

- (Message_SubMessageResponse*) build;
- (Message_SubMessageResponse*) buildPartial;

- (Message_SubMessageResponse_Builder*) mergeFrom:(Message_SubMessageResponse*) other;
- (Message_SubMessageResponse_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (Message_SubMessageResponse_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasStatus;
- (int32_t) status;
- (Message_SubMessageResponse_Builder*) setStatus:(int32_t) value;
- (Message_SubMessageResponse_Builder*) clearStatus;

- (BOOL) hasUserId;
- (NSString*) userId;
- (Message_SubMessageResponse_Builder*) setUserId:(NSString*) value;
- (Message_SubMessageResponse_Builder*) clearUserId;

- (BOOL) hasUserName;
- (NSString*) userName;
- (Message_SubMessageResponse_Builder*) setUserName:(NSString*) value;
- (Message_SubMessageResponse_Builder*) clearUserName;

- (BOOL) hasPassword;
- (NSString*) password;
- (Message_SubMessageResponse_Builder*) setPassword:(NSString*) value;
- (Message_SubMessageResponse_Builder*) clearPassword;

- (BOOL) hasNickName;
- (NSString*) nickName;
- (Message_SubMessageResponse_Builder*) setNickName:(NSString*) value;
- (Message_SubMessageResponse_Builder*) clearNickName;

- (BOOL) hasSex;
- (int32_t) sex;
- (Message_SubMessageResponse_Builder*) setSex:(int32_t) value;
- (Message_SubMessageResponse_Builder*) clearSex;

- (BOOL) hasBirthday;
- (NSString*) birthday;
- (Message_SubMessageResponse_Builder*) setBirthday:(NSString*) value;
- (Message_SubMessageResponse_Builder*) clearBirthday;

- (BOOL) hasAvatarUrl;
- (NSString*) avatarUrl;
- (Message_SubMessageResponse_Builder*) setAvatarUrl:(NSString*) value;
- (Message_SubMessageResponse_Builder*) clearAvatarUrl;

- (BOOL) hasAvatarId;
- (int32_t) avatarId;
- (Message_SubMessageResponse_Builder*) setAvatarId:(int32_t) value;
- (Message_SubMessageResponse_Builder*) clearAvatarId;

- (BOOL) hasAppId;
- (NSString*) appId;
- (Message_SubMessageResponse_Builder*) setAppId:(NSString*) value;
- (Message_SubMessageResponse_Builder*) clearAppId;
@end

@interface Message_LoginMessageRequest : PBGeneratedMessage {
@private
  BOOL hasPhoneNumber_:1;
  BOOL hasEmail_:1;
  BOOL hasPassword_:1;
  NSString* phoneNumber;
  NSString* email;
  NSString* password;
}
- (BOOL) hasPhoneNumber;
- (BOOL) hasEmail;
- (BOOL) hasPassword;
@property (readonly, retain) NSString* phoneNumber;
@property (readonly, retain) NSString* email;
@property (readonly, retain) NSString* password;

+ (Message_LoginMessageRequest*) defaultInstance;
- (Message_LoginMessageRequest*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (Message_LoginMessageRequest_Builder*) builder;
+ (Message_LoginMessageRequest_Builder*) builder;
+ (Message_LoginMessageRequest_Builder*) builderWithPrototype:(Message_LoginMessageRequest*) prototype;

+ (Message_LoginMessageRequest*) parseFromData:(NSData*) data;
+ (Message_LoginMessageRequest*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Message_LoginMessageRequest*) parseFromInputStream:(NSInputStream*) input;
+ (Message_LoginMessageRequest*) parseDelimitedFromInputStream:(NSInputStream*) input;
+ (Message_LoginMessageRequest*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Message_LoginMessageRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (Message_LoginMessageRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface Message_LoginMessageRequest_Builder : PBGeneratedMessage_Builder {
@private
  Message_LoginMessageRequest* result;
}

- (Message_LoginMessageRequest*) defaultInstance;

- (Message_LoginMessageRequest_Builder*) clear;
- (Message_LoginMessageRequest_Builder*) clone;

- (Message_LoginMessageRequest*) build;
- (Message_LoginMessageRequest*) buildPartial;

- (Message_LoginMessageRequest_Builder*) mergeFrom:(Message_LoginMessageRequest*) other;
- (Message_LoginMessageRequest_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (Message_LoginMessageRequest_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasPhoneNumber;
- (NSString*) phoneNumber;
- (Message_LoginMessageRequest_Builder*) setPhoneNumber:(NSString*) value;
- (Message_LoginMessageRequest_Builder*) clearPhoneNumber;

- (BOOL) hasEmail;
- (NSString*) email;
- (Message_LoginMessageRequest_Builder*) setEmail:(NSString*) value;
- (Message_LoginMessageRequest_Builder*) clearEmail;

- (BOOL) hasPassword;
- (NSString*) password;
- (Message_LoginMessageRequest_Builder*) setPassword:(NSString*) value;
- (Message_LoginMessageRequest_Builder*) clearPassword;
@end

@interface Message_LoginMessageResponse : PBGeneratedMessage {
@private
  BOOL hasStatus_:1;
  BOOL hasSex_:1;
  BOOL hasAvatarId_:1;
  BOOL hasUserId_:1;
  BOOL hasUserName_:1;
  BOOL hasPassword_:1;
  BOOL hasNickName_:1;
  BOOL hasBirthday_:1;
  BOOL hasAvatarUrl_:1;
  BOOL hasAppId_:1;
  int32_t status;
  int32_t sex;
  int32_t avatarId;
  NSString* userId;
  NSString* userName;
  NSString* password;
  NSString* nickName;
  NSString* birthday;
  NSString* avatarUrl;
  NSString* appId;
}
- (BOOL) hasStatus;
- (BOOL) hasUserId;
- (BOOL) hasUserName;
- (BOOL) hasPassword;
- (BOOL) hasNickName;
- (BOOL) hasSex;
- (BOOL) hasBirthday;
- (BOOL) hasAvatarUrl;
- (BOOL) hasAvatarId;
- (BOOL) hasAppId;
@property (readonly) int32_t status;
@property (readonly, retain) NSString* userId;
@property (readonly, retain) NSString* userName;
@property (readonly, retain) NSString* password;
@property (readonly, retain) NSString* nickName;
@property (readonly) int32_t sex;
@property (readonly, retain) NSString* birthday;
@property (readonly, retain) NSString* avatarUrl;
@property (readonly) int32_t avatarId;
@property (readonly, retain) NSString* appId;

+ (Message_LoginMessageResponse*) defaultInstance;
- (Message_LoginMessageResponse*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (Message_LoginMessageResponse_Builder*) builder;
+ (Message_LoginMessageResponse_Builder*) builder;
+ (Message_LoginMessageResponse_Builder*) builderWithPrototype:(Message_LoginMessageResponse*) prototype;

+ (Message_LoginMessageResponse*) parseFromData:(NSData*) data;
+ (Message_LoginMessageResponse*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Message_LoginMessageResponse*) parseFromInputStream:(NSInputStream*) input;
+ (Message_LoginMessageResponse*) parseDelimitedFromInputStream:(NSInputStream*) input;
+ (Message_LoginMessageResponse*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Message_LoginMessageResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (Message_LoginMessageResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface Message_LoginMessageResponse_Builder : PBGeneratedMessage_Builder {
@private
  Message_LoginMessageResponse* result;
}

- (Message_LoginMessageResponse*) defaultInstance;

- (Message_LoginMessageResponse_Builder*) clear;
- (Message_LoginMessageResponse_Builder*) clone;

- (Message_LoginMessageResponse*) build;
- (Message_LoginMessageResponse*) buildPartial;

- (Message_LoginMessageResponse_Builder*) mergeFrom:(Message_LoginMessageResponse*) other;
- (Message_LoginMessageResponse_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (Message_LoginMessageResponse_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasStatus;
- (int32_t) status;
- (Message_LoginMessageResponse_Builder*) setStatus:(int32_t) value;
- (Message_LoginMessageResponse_Builder*) clearStatus;

- (BOOL) hasUserId;
- (NSString*) userId;
- (Message_LoginMessageResponse_Builder*) setUserId:(NSString*) value;
- (Message_LoginMessageResponse_Builder*) clearUserId;

- (BOOL) hasUserName;
- (NSString*) userName;
- (Message_LoginMessageResponse_Builder*) setUserName:(NSString*) value;
- (Message_LoginMessageResponse_Builder*) clearUserName;

- (BOOL) hasPassword;
- (NSString*) password;
- (Message_LoginMessageResponse_Builder*) setPassword:(NSString*) value;
- (Message_LoginMessageResponse_Builder*) clearPassword;

- (BOOL) hasNickName;
- (NSString*) nickName;
- (Message_LoginMessageResponse_Builder*) setNickName:(NSString*) value;
- (Message_LoginMessageResponse_Builder*) clearNickName;

- (BOOL) hasSex;
- (int32_t) sex;
- (Message_LoginMessageResponse_Builder*) setSex:(int32_t) value;
- (Message_LoginMessageResponse_Builder*) clearSex;

- (BOOL) hasBirthday;
- (NSString*) birthday;
- (Message_LoginMessageResponse_Builder*) setBirthday:(NSString*) value;
- (Message_LoginMessageResponse_Builder*) clearBirthday;

- (BOOL) hasAvatarUrl;
- (NSString*) avatarUrl;
- (Message_LoginMessageResponse_Builder*) setAvatarUrl:(NSString*) value;
- (Message_LoginMessageResponse_Builder*) clearAvatarUrl;

- (BOOL) hasAvatarId;
- (int32_t) avatarId;
- (Message_LoginMessageResponse_Builder*) setAvatarId:(int32_t) value;
- (Message_LoginMessageResponse_Builder*) clearAvatarId;

- (BOOL) hasAppId;
- (NSString*) appId;
- (Message_LoginMessageResponse_Builder*) setAppId:(NSString*) value;
- (Message_LoginMessageResponse_Builder*) clearAppId;
@end

@interface Message_LogoutMessageRequest : PBGeneratedMessage {
@private
  BOOL hasPhoneNumber_:1;
  BOOL hasEmail_:1;
  NSString* phoneNumber;
  NSString* email;
}
- (BOOL) hasPhoneNumber;
- (BOOL) hasEmail;
@property (readonly, retain) NSString* phoneNumber;
@property (readonly, retain) NSString* email;

+ (Message_LogoutMessageRequest*) defaultInstance;
- (Message_LogoutMessageRequest*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (Message_LogoutMessageRequest_Builder*) builder;
+ (Message_LogoutMessageRequest_Builder*) builder;
+ (Message_LogoutMessageRequest_Builder*) builderWithPrototype:(Message_LogoutMessageRequest*) prototype;

+ (Message_LogoutMessageRequest*) parseFromData:(NSData*) data;
+ (Message_LogoutMessageRequest*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Message_LogoutMessageRequest*) parseFromInputStream:(NSInputStream*) input;
+ (Message_LogoutMessageRequest*) parseDelimitedFromInputStream:(NSInputStream*) input;
+ (Message_LogoutMessageRequest*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Message_LogoutMessageRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (Message_LogoutMessageRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface Message_LogoutMessageRequest_Builder : PBGeneratedMessage_Builder {
@private
  Message_LogoutMessageRequest* result;
}

- (Message_LogoutMessageRequest*) defaultInstance;

- (Message_LogoutMessageRequest_Builder*) clear;
- (Message_LogoutMessageRequest_Builder*) clone;

- (Message_LogoutMessageRequest*) build;
- (Message_LogoutMessageRequest*) buildPartial;

- (Message_LogoutMessageRequest_Builder*) mergeFrom:(Message_LogoutMessageRequest*) other;
- (Message_LogoutMessageRequest_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (Message_LogoutMessageRequest_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasPhoneNumber;
- (NSString*) phoneNumber;
- (Message_LogoutMessageRequest_Builder*) setPhoneNumber:(NSString*) value;
- (Message_LogoutMessageRequest_Builder*) clearPhoneNumber;

- (BOOL) hasEmail;
- (NSString*) email;
- (Message_LogoutMessageRequest_Builder*) setEmail:(NSString*) value;
- (Message_LogoutMessageRequest_Builder*) clearEmail;
@end

@interface Message_LogoutMessageResponse : PBGeneratedMessage {
@private
  BOOL hasStatus_:1;
  int32_t status;
}
- (BOOL) hasStatus;
@property (readonly) int32_t status;

+ (Message_LogoutMessageResponse*) defaultInstance;
- (Message_LogoutMessageResponse*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (Message_LogoutMessageResponse_Builder*) builder;
+ (Message_LogoutMessageResponse_Builder*) builder;
+ (Message_LogoutMessageResponse_Builder*) builderWithPrototype:(Message_LogoutMessageResponse*) prototype;

+ (Message_LogoutMessageResponse*) parseFromData:(NSData*) data;
+ (Message_LogoutMessageResponse*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Message_LogoutMessageResponse*) parseFromInputStream:(NSInputStream*) input;
+ (Message_LogoutMessageResponse*) parseDelimitedFromInputStream:(NSInputStream*) input;
+ (Message_LogoutMessageResponse*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Message_LogoutMessageResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (Message_LogoutMessageResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface Message_LogoutMessageResponse_Builder : PBGeneratedMessage_Builder {
@private
  Message_LogoutMessageResponse* result;
}

- (Message_LogoutMessageResponse*) defaultInstance;

- (Message_LogoutMessageResponse_Builder*) clear;
- (Message_LogoutMessageResponse_Builder*) clone;

- (Message_LogoutMessageResponse*) build;
- (Message_LogoutMessageResponse*) buildPartial;

- (Message_LogoutMessageResponse_Builder*) mergeFrom:(Message_LogoutMessageResponse*) other;
- (Message_LogoutMessageResponse_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (Message_LogoutMessageResponse_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasStatus;
- (int32_t) status;
- (Message_LogoutMessageResponse_Builder*) setStatus:(int32_t) value;
- (Message_LogoutMessageResponse_Builder*) clearStatus;
@end

@interface Message_ForgetPasswordMessageRequest : PBGeneratedMessage {
@private
  BOOL hasPhoneNumber_:1;
  BOOL hasEmail_:1;
  NSString* phoneNumber;
  NSString* email;
}
- (BOOL) hasPhoneNumber;
- (BOOL) hasEmail;
@property (readonly, retain) NSString* phoneNumber;
@property (readonly, retain) NSString* email;

+ (Message_ForgetPasswordMessageRequest*) defaultInstance;
- (Message_ForgetPasswordMessageRequest*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (Message_ForgetPasswordMessageRequest_Builder*) builder;
+ (Message_ForgetPasswordMessageRequest_Builder*) builder;
+ (Message_ForgetPasswordMessageRequest_Builder*) builderWithPrototype:(Message_ForgetPasswordMessageRequest*) prototype;

+ (Message_ForgetPasswordMessageRequest*) parseFromData:(NSData*) data;
+ (Message_ForgetPasswordMessageRequest*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Message_ForgetPasswordMessageRequest*) parseFromInputStream:(NSInputStream*) input;
+ (Message_ForgetPasswordMessageRequest*) parseDelimitedFromInputStream:(NSInputStream*) input;
+ (Message_ForgetPasswordMessageRequest*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Message_ForgetPasswordMessageRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (Message_ForgetPasswordMessageRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface Message_ForgetPasswordMessageRequest_Builder : PBGeneratedMessage_Builder {
@private
  Message_ForgetPasswordMessageRequest* result;
}

- (Message_ForgetPasswordMessageRequest*) defaultInstance;

- (Message_ForgetPasswordMessageRequest_Builder*) clear;
- (Message_ForgetPasswordMessageRequest_Builder*) clone;

- (Message_ForgetPasswordMessageRequest*) build;
- (Message_ForgetPasswordMessageRequest*) buildPartial;

- (Message_ForgetPasswordMessageRequest_Builder*) mergeFrom:(Message_ForgetPasswordMessageRequest*) other;
- (Message_ForgetPasswordMessageRequest_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (Message_ForgetPasswordMessageRequest_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasPhoneNumber;
- (NSString*) phoneNumber;
- (Message_ForgetPasswordMessageRequest_Builder*) setPhoneNumber:(NSString*) value;
- (Message_ForgetPasswordMessageRequest_Builder*) clearPhoneNumber;

- (BOOL) hasEmail;
- (NSString*) email;
- (Message_ForgetPasswordMessageRequest_Builder*) setEmail:(NSString*) value;
- (Message_ForgetPasswordMessageRequest_Builder*) clearEmail;
@end

@interface Message_ForgetPasswordMessageResponse : PBGeneratedMessage {
@private
  BOOL hasStatus_:1;
  int32_t status;
}
- (BOOL) hasStatus;
@property (readonly) int32_t status;

+ (Message_ForgetPasswordMessageResponse*) defaultInstance;
- (Message_ForgetPasswordMessageResponse*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (Message_ForgetPasswordMessageResponse_Builder*) builder;
+ (Message_ForgetPasswordMessageResponse_Builder*) builder;
+ (Message_ForgetPasswordMessageResponse_Builder*) builderWithPrototype:(Message_ForgetPasswordMessageResponse*) prototype;

+ (Message_ForgetPasswordMessageResponse*) parseFromData:(NSData*) data;
+ (Message_ForgetPasswordMessageResponse*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Message_ForgetPasswordMessageResponse*) parseFromInputStream:(NSInputStream*) input;
+ (Message_ForgetPasswordMessageResponse*) parseDelimitedFromInputStream:(NSInputStream*) input;
+ (Message_ForgetPasswordMessageResponse*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Message_ForgetPasswordMessageResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (Message_ForgetPasswordMessageResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface Message_ForgetPasswordMessageResponse_Builder : PBGeneratedMessage_Builder {
@private
  Message_ForgetPasswordMessageResponse* result;
}

- (Message_ForgetPasswordMessageResponse*) defaultInstance;

- (Message_ForgetPasswordMessageResponse_Builder*) clear;
- (Message_ForgetPasswordMessageResponse_Builder*) clone;

- (Message_ForgetPasswordMessageResponse*) build;
- (Message_ForgetPasswordMessageResponse*) buildPartial;

- (Message_ForgetPasswordMessageResponse_Builder*) mergeFrom:(Message_ForgetPasswordMessageResponse*) other;
- (Message_ForgetPasswordMessageResponse_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (Message_ForgetPasswordMessageResponse_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasStatus;
- (int32_t) status;
- (Message_ForgetPasswordMessageResponse_Builder*) setStatus:(int32_t) value;
- (Message_ForgetPasswordMessageResponse_Builder*) clearStatus;
@end

@interface Message_Builder : PBGeneratedMessage_Builder {
@private
  Message* result;
}

- (Message*) defaultInstance;

- (Message_Builder*) clear;
- (Message_Builder*) clone;

- (Message*) build;
- (Message*) buildPartial;

- (Message_Builder*) mergeFrom:(Message*) other;
- (Message_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (Message_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasType;
- (Message_MessageType) type;
- (Message_Builder*) setType:(Message_MessageType) value;
- (Message_Builder*) clearType;

- (BOOL) hasSubRequest;
- (Message_SubMessageRequest*) subRequest;
- (Message_Builder*) setSubRequest:(Message_SubMessageRequest*) value;
- (Message_Builder*) setSubRequestBuilder:(Message_SubMessageRequest_Builder*) builderForValue;
- (Message_Builder*) mergeSubRequest:(Message_SubMessageRequest*) value;
- (Message_Builder*) clearSubRequest;

- (BOOL) hasSubResponse;
- (Message_SubMessageResponse*) subResponse;
- (Message_Builder*) setSubResponse:(Message_SubMessageResponse*) value;
- (Message_Builder*) setSubResponseBuilder:(Message_SubMessageResponse_Builder*) builderForValue;
- (Message_Builder*) mergeSubResponse:(Message_SubMessageResponse*) value;
- (Message_Builder*) clearSubResponse;

- (BOOL) hasLoginRequest;
- (Message_LoginMessageRequest*) loginRequest;
- (Message_Builder*) setLoginRequest:(Message_LoginMessageRequest*) value;
- (Message_Builder*) setLoginRequestBuilder:(Message_LoginMessageRequest_Builder*) builderForValue;
- (Message_Builder*) mergeLoginRequest:(Message_LoginMessageRequest*) value;
- (Message_Builder*) clearLoginRequest;

- (BOOL) hasLoginResponse;
- (Message_LoginMessageResponse*) loginResponse;
- (Message_Builder*) setLoginResponse:(Message_LoginMessageResponse*) value;
- (Message_Builder*) setLoginResponseBuilder:(Message_LoginMessageResponse_Builder*) builderForValue;
- (Message_Builder*) mergeLoginResponse:(Message_LoginMessageResponse*) value;
- (Message_Builder*) clearLoginResponse;

- (BOOL) hasLogoutRequest;
- (Message_LogoutMessageRequest*) logoutRequest;
- (Message_Builder*) setLogoutRequest:(Message_LogoutMessageRequest*) value;
- (Message_Builder*) setLogoutRequestBuilder:(Message_LogoutMessageRequest_Builder*) builderForValue;
- (Message_Builder*) mergeLogoutRequest:(Message_LogoutMessageRequest*) value;
- (Message_Builder*) clearLogoutRequest;

- (BOOL) hasLogoutResponse;
- (Message_LogoutMessageResponse*) logoutResponse;
- (Message_Builder*) setLogoutResponse:(Message_LogoutMessageResponse*) value;
- (Message_Builder*) setLogoutResponseBuilder:(Message_LogoutMessageResponse_Builder*) builderForValue;
- (Message_Builder*) mergeLogoutResponse:(Message_LogoutMessageResponse*) value;
- (Message_Builder*) clearLogoutResponse;

- (BOOL) hasForgetPwdRequest;
- (Message_ForgetPasswordMessageRequest*) forgetPwdRequest;
- (Message_Builder*) setForgetPwdRequest:(Message_ForgetPasswordMessageRequest*) value;
- (Message_Builder*) setForgetPwdRequestBuilder:(Message_ForgetPasswordMessageRequest_Builder*) builderForValue;
- (Message_Builder*) mergeForgetPwdRequest:(Message_ForgetPasswordMessageRequest*) value;
- (Message_Builder*) clearForgetPwdRequest;

- (BOOL) hasForgetPwdResponse;
- (Message_ForgetPasswordMessageResponse*) forgetPwdResponse;
- (Message_Builder*) setForgetPwdResponse:(Message_ForgetPasswordMessageResponse*) value;
- (Message_Builder*) setForgetPwdResponseBuilder:(Message_ForgetPasswordMessageResponse_Builder*) builderForValue;
- (Message_Builder*) mergeForgetPwdResponse:(Message_ForgetPasswordMessageResponse*) value;
- (Message_Builder*) clearForgetPwdResponse;
@end

